(()=>{"use strict";const $=id=>document.getElementById(id);let stops=[],budget=[],trip=null;
function addStop(){const x={id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2),start:$("start").value,end:$("end").value,place:$("place").value.trim(),kind:$("kind").value,bookingRef:$("booking-ref").value.trim(),cost:+$("cost").value||0,currency:$("currency").value.trim().toUpperCase()||"USD",notes:$("notes").value.trim()};if(!x.place||!x.start)return;stops.push(x);render()}
function render(){const list=$("stops");list.replaceChildren();stops.slice().sort((a,b)=>a.start.localeCompare(b.start)).forEach(x=>{const d=document.createElement("div");d.className="tf-stop";d.innerHTML=`<strong>${x.place}</strong> · ${x.kind}<div>${x.start}${x.end?` → ${x.end}`:""}</div><div class="fx-watermark">${x.bookingRef?`ref ${x.bookingRef} · `:""}${x.cost?`${x.cost} ${x.currency} · `:""}${x.notes}</div><button class="btn ghost" data-id="${x.id}">REMOVE</button>`;list.append(d)});list.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>{stops=stops.filter(x=>x.id!==b.dataset.id);render()});renderTimeline();renderBudget();$("stop-count").textContent=stops.length}
function renderTimeline(){const e=$("timeline");e.replaceChildren();stops.slice().sort((a,b)=>a.start.localeCompare(b.start)).forEach(x=>{const d=document.createElement("div");d.className="timeline-item";d.innerHTML=`<strong>${x.start}</strong><div>${x.place} · ${x.kind}</div>`;e.append(d)})}
$("add-stop").onclick=addStop;
$("add-budget").onclick=()=>{const x={id:Math.random().toString(36).slice(2),category:$("bcat").value.trim(),amount:+$("bamount").value||0,currency:$("bcurrency").value.trim().toUpperCase()||"USD",status:$("bstatus").value};if(!x.category)return;budget.push(x);renderBudget()};
function renderBudget(){const e=$("budget");e.replaceChildren();budget.forEach(x=>{const d=document.createElement("div");d.className="tf-budget";d.innerHTML=`<strong>${x.category}</strong> · ${x.amount} ${x.currency} · ${x.status}`;e.append(d)});const currencies={};[...budget,...stops.filter(s=>s.cost).map(s=>({amount:s.cost,currency:s.currency}))].forEach(x=>currencies[x.currency]=(currencies[x.currency]||0)+x.amount);$("budget-total").textContent=Object.entries(currencies).map(([c,v])=>`${v.toFixed(2)} ${c}`).join(" · ")||"0";$("budget-count").textContent=budget.length}
$("build").onclick=()=>{trip={schema:"zzx.tripforge.trip.v1",created:new Date().toISOString(),name:$("trip-name").value.trim(),travelers:Math.max(1,+$("travelers").value||1),homeBase:$("home").value.trim(),stops,budget,liveBooking:false,livePricing:false,currencyConversion:false};$("output").textContent=JSON.stringify(trip,null,2)};
function dl(text,name,type="application/json"){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("export-json").onclick=()=>{if(!trip)$("build").click();dl(JSON.stringify(trip,null,2),"tripforge-trip.json")};
$("export-ics").onclick=()=>{const esc=s=>String(s||"").replace(/[\\;,]/g,m=>"\\"+m).replace(/\n/g,"\\n"),fmt=s=>s?new Date(s).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"Z"):"";let out=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//ZZX-Labs//TripForge//EN"];for(const x of stops){out.push("BEGIN:VEVENT",`UID:${x.id}@tripforge`,`DTSTART:${fmt(x.start)}`,x.end?`DTEND:${fmt(x.end)}`:"",`SUMMARY:${esc(x.kind+" — "+x.place)}`,`DESCRIPTION:${esc(x.notes)}`,"END:VEVENT")}out.push("END:VCALENDAR");dl(out.filter(Boolean).join("\r\n"),"tripforge-itinerary.ics","text/calendar")};
$("start").value=new Date(Date.now()+7*86400000).toISOString().slice(0,16);render();window.TripForge=Object.freeze({version:"0.1.0-alpha-web",liveBooking:false});
})();
