(()=>{"use strict";const $=id=>document.getElementById(id);let peers=[],offers=[];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2);
$("add-peer").onclick=()=>{peers.push({id:$("peer-id").value.trim()||uid(),capacity:Math.max(0,+$("capacity").value||0),outbound:Math.max(0,+$("outbound").value||0),baseFee:Math.max(0,+$("base-fee").value||0),ppm:Math.max(0,+$("ppm").value||0),reliability:Math.max(0,Math.min(100,+$("reliability").value||100))});render()};
$("add-offer").onclick=()=>{offers.push({id:uid(),side:$("offer-side").value,price:+$("offer-price").value||0,qty:Math.max(0,+$("offer-qty").value||0),peer:$("offer-peer").value.trim(),created:new Date().toISOString(),simulated:true});render()};
function render(){const e=$("peers");e.replaceChildren();peers.forEach(p=>{const d=document.createElement("div");d.className="peer";d.innerHTML=`<strong>${p.id}</strong> · outbound ${p.outbound.toFixed(0)} sat / capacity ${p.capacity.toFixed(0)} sat<div class="fx-watermark">fee ${p.baseFee} sat + ${p.ppm} ppm · reliability ${p.reliability}%</div>`;e.append(d)});const o=$("offers");o.replaceChildren();offers.forEach(v=>{const d=document.createElement("div");d.className="peer";d.innerHTML=`<strong>${v.side.toUpperCase()} ${v.qty.toFixed(5)} BTC @ ${v.price.toFixed(2)}</strong> · ${v.peer||"anonymous synthetic peer"}`;o.append(d)});$("peer-count").textContent=peers.length;$("liq").textContent=peers.reduce((s,p)=>s+p.outbound,0).toLocaleString();$("offer-count").textContent=offers.length}
$("route").onclick=()=>{const amt=Math.max(1,+$("amount").value||1),max=Math.max(1,+$("max-hops").value||3),usable=peers.filter(p=>p.outbound>=amt).sort((a,b)=>(b.reliability-a.reliability)||((a.baseFee+a.ppm*amt/1e6)-(b.baseFee+b.ppm*amt/1e6))).slice(0,max);let fee=0,prob=1;usable.forEach(p=>{fee+=p.baseFee+p.ppm*amt/1e6;prob*=p.reliability/100});$("route-out").textContent=JSON.stringify({amountSat:amt,path:usable.map(p=>p.id),hops:usable.length,estimatedFeeSat:+fee.toFixed(3),syntheticSuccessProbability:+(prob*100).toFixed(2),simulationOnly:true,lnBroadcast:false},null,2)};
$("monte").onclick=()=>{const trials=Math.max(10,Math.min(100000,+$("trials").value||1000)),amt=Math.max(1,+$("amount").value||1);let ok=0,fees=[];for(let i=0;i<trials;i++){const p=peers[Math.floor(Math.random()*Math.max(1,peers.length))];if(!p)break;if(p.outbound>=amt&&Math.random()*100<p.reliability){ok++;fees.push(p.baseFee+p.ppm*amt/1e6)}}$("monte-out").textContent=JSON.stringify({trials,successes:ok,successRate:trials?+(ok/trials*100).toFixed(2):0,averageFeeSat:fees.length?+(fees.reduce((a,b)=>a+b,0)/fees.length).toFixed(3):null,simulationOnly:true},null,2)};
$("export").onclick=()=>{const t=JSON.stringify({schema:"zzx.dex.research.v1",exported:new Date().toISOString(),peers,offers,liveLightning:false,credentials:false,privateKeys:false},null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="zzxdex-research.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
[["peer-a",2500000,1800000,1,150,99.2],["peer-b",1700000,900000,0,300,96.5],["peer-c",4200000,2600000,2,80,98.4],["peer-d",900000,600000,1,250,94.0]].forEach(([id,capacity,outbound,baseFee,ppm,reliability])=>peers.push({id,capacity,outbound,baseFee,ppm,reliability}));render();window.ZZXDEX=Object.freeze({version:"0.1.0-alpha-web",liveLightning:false});
})();
