// __partials/widgets/btc-commits/js/sources.js
(function(){
  "use strict";

  const W=window;
  if(Number(W.ZZXBTCCommitsSources?.__version||0)>=2)return;

  W.ZZXBTCCommitsSources=Object.freeze({
    __version:2,

    // Canonical first-party mirrors generated by:
    // .github/workflows/zzx-bitcoin-core-github-activity.yml
    localPrimary:"/bitcoin/github/api/bitcoin-core/commits.json",
    localFallback:"/bitcoin/github/bitcoin-core/commits.json",

    // Legacy path retained as an explicit compatibility reference only.
    // It is NOT queried unless a caller deliberately opts into it.
    legacyLocal:"/bitcoin/bpi/api/btc_commits.json",

    github:"https://api.github.com/repos/bitcoin/bitcoin/commits?sha=master&per_page=100",
    repository:"https://github.com/bitcoin/bitcoin",
    commitsPage:"https://github.com/bitcoin/bitcoin/commits/master/",

    // Anonymous direct GitHub is disabled by default. Public visitors should
    // use the first-party mirror to avoid shared unauthenticated API limits.
    directFallbackFlag:"ZZXGitHubDirectFallback"
  });
})();
