(() => {
"use strict";
const $=id=>document.getElementById(id),state={files:[],volume:null,timer:null,frame:0};
function dl(t,n){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function addFiles(fs){for(const f of [...fs])state.files.push({name:f.webkitRelativePath||f.name,bytes:new Uint8Array(await f.arrayBuffer()),type:f.type||"application/octet-stream"});$("ov-output").textContent=`Loaded ${state.files.length} file(s).`;}
async function build(){
 const size=Math.max(64,Math.min(4096,+$("ov-size").value||512)),group=Math.max(2,Math.min(16,+$("ov-group").value||4)),copies=Math.max(1,Math.min(4,+$("ov-copies").value||1)),files=[];
 for(let i=0;i<state.files.length;i++){const f=state.files[i],sha=await OpticalCore.sha256(f.bytes),frames=OpticalCore.buildFrames(f.bytes,{chunkSize:size,groupSize:group});files.push({path:f.name,mime:f.type,bytes:f.bytes.length,sha256:sha,sequenceId:`SEQ-${String(i+1).padStart(4,"0")}`,frames,copies});}
 state.volume={schema:"zzx.bofs.volume.v1",version:"0.1.0-alpha",descriptor:{label:$("ov-label").value.trim(),archiveId:$("ov-id").value.trim(),profile:$("ov-profile").value,createdAt:new Date().toISOString(),chunkSize:size,parityGroup:group,sequenceCopies:copies,isoOriented:$("ov-profile").value==="iso-manifest"},files};
 renderIndex();selectors();show();$("ov-output").textContent=JSON.stringify({label:state.volume.descriptor.label,profile:state.volume.descriptor.profile,files:files.length,totalBytes:files.reduce((s,f)=>s+f.bytes,0),totalLogicalFrames:files.reduce((s,f)=>s+f.frames.length,0),sequenceCopies:copies},null,2);
}
function renderIndex(){const b=$("oi-body");b.replaceChildren();for(const f of state.volume?.files||[]){const tr=document.createElement("tr");[f.path,f.bytes,f.sha256.slice(0,24)+"…",f.sequenceId,f.frames.length].forEach(x=>{const td=document.createElement("td");td.textContent=x;tr.appendChild(td);});b.appendChild(tr);}if(!state.volume?.files?.length)b.innerHTML='<tr><td colspan="5">No volume built.</td></tr>';}
function selectors(){for(const id of ["of-seq","or-seq"]){const s=$(id),old=s.value;s.replaceChildren();for(const f of state.volume?.files||[]){const o=document.createElement("option");o.value=f.sequenceId;o.textContent=`${f.sequenceId} · ${f.path}`;s.appendChild(o);}if([...s.options].some(o=>o.value===old))s.value=old;}}
function seq(id){return state.volume?.files.find(f=>f.sequenceId===id);}
function frameBytes(f){const h=OpticalCore.te.encode(`BOFS|${f.index}|${f.total}|${f.kind}|${f.group}|${f.slot}|${f.length}|${f.crc32}|`);return OpticalCore.concat(h,OpticalCore.ub64(f.payload));}
function show(){const s=seq($("of-seq").value);if(!s?.frames.length)return;state.frame=((state.frame%s.frames.length)+s.frames.length)%s.frames.length;$("of-frame").value=state.frame;const f=s.frames[state.frame];OpticalCore.drawFrame($("of-canvas"),frameBytes(f),f);$("of-output").textContent=JSON.stringify({sequence:s.sequenceId,path:s.path,frame:{...f,payload:`${f.payload.slice(0,60)}…`}},null,2);}
function toggle(){if(state.timer){clearInterval(state.timer);state.timer=null;$("of-toggle").textContent="PLAY";}else{const fps=Math.max(1,Math.min(60,+$("of-fps").value||6));state.timer=setInterval(()=>{state.frame++;show();},1000/fps);$("of-toggle").textContent="STOP";}}
$("ov-files").addEventListener("change",()=>addFiles($("ov-files").files));$("ov-clear").addEventListener("click",()=>{state.files=[];state.volume=null;renderIndex();selectors();$("ov-output").textContent="Cleared.";});$("ov-build").addEventListener("click",()=>build().catch(e=>$("ov-output").textContent=`ERROR: ${e.message}`));
$("of-seq").addEventListener("change",()=>{state.frame=0;show();});$("of-frame").addEventListener("change",()=>{state.frame=+$("of-frame").value||0;show();});$("of-toggle").addEventListener("click",toggle);
$("or-run").addEventListener("click",async()=>{try{const s=seq($("or-seq").value);if(!s)throw new Error("Select sequence.");const drop=+$("or-drop").value,frames=s.frames.filter(f=>f.index!==drop),bytes=OpticalCore.recover(frames,state.volume.descriptor.chunkSize).slice(0,s.bytes),hash=await OpticalCore.sha256(bytes);$("or-output").textContent=JSON.stringify({path:s.path,droppedFrame:drop,recoveredBytes:bytes.length,sha256:hash,expectedSha256:s.sha256,match:hash===s.sha256},null,2);}catch(e){$("or-output").textContent=`ERROR: ${e.message}`;}});
$("oa-export").addEventListener("click",()=>{if(!state.volume)return;dl(JSON.stringify(state.volume,null,2),`${state.volume.descriptor.label||"volume"}.bofs.json`);});
$("oa-import").addEventListener("change",async()=>{const f=$("oa-import").files?.[0];if(!f)return;try{const v=JSON.parse(await f.text());if(v.schema!=="zzx.bofs.volume.v1")throw new Error("Unsupported BOFS schema.");state.volume=v;state.files=[];renderIndex();selectors();state.frame=0;show();$("oa-output").textContent=`Imported ${v.files.length} file sequence(s) from ${f.name}.`;}catch(e){$("oa-output").textContent=`ERROR: ${e.message}`;}$("oa-import").value="";});
renderIndex();selectors();
window.BOFS=Object.freeze({version:"0.1.0-alpha-web",buildFrames:OpticalCore.buildFrames,recover:OpticalCore.recover,getVolume:()=>state.volume});
window.ZZXHooks?.emit("bofs:ready",{version:"0.1.0-alpha-web"});
})();
