(()=>{"use strict";const $=id=>document.getElementById(id);let schema={name:"VideoRecord",version:"1.0",fields:[]},rules=[];
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
$("add-field").onclick=()=>{const f={name:$("field-name").value.trim(),type:$("field-type").value,required:$("field-required").checked,default:$("field-default").value,description:$("field-desc").value.trim()};if(!/^[A-Za-z_][A-Za-z0-9_]*$/.test(f.name)){$("schema-output").textContent="Field name must be a simple identifier.";return}schema.fields.push(f);render()};
function render(){schema.name=$("schema-name").value.trim()||"VideoRecord";schema.version=$("schema-version").value.trim()||"1.0";const e=$("fields");e.replaceChildren();schema.fields.forEach((f,i)=>{const d=document.createElement("div");d.className="pt-field";d.innerHTML=`<strong>${esc(f.name)}</strong> · ${esc(f.type)} · ${f.required?"required":"optional"}<p>${esc(f.description)}</p><button class="btn ghost" data-i="${i}">REMOVE</button>`;e.append(d)});e.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>{schema.fields.splice(+b.dataset.i,1);render()});$("schema-output").textContent=JSON.stringify(schema,null,2);$("field-count").textContent=schema.fields.length}
$("schema-name").oninput=render;$("schema-version").oninput=render;
$("add-rule").onclick=()=>{rules.push({field:$("rule-field").value.trim(),operator:$("rule-op").value,value:$("rule-value").value.trim(),tag:$("rule-tag").value.trim()});$("rules-output").textContent=JSON.stringify(rules,null,2)};
$("validate-sample").onclick=()=>{try{const sample=JSON.parse($("sample").value),issues=[];for(const f of schema.fields){if(f.required&&!(f.name in sample))issues.push(`${f.name}: required`);if(f.name in sample){const v=sample[f.name],ok=f.type==="string"?typeof v==="string":f.type==="number"?typeof v==="number":f.type==="boolean"?typeof v==="boolean":f.type==="array"?Array.isArray(v):f.type==="object"?v&&typeof v==="object"&&!Array.isArray(v):true;if(!ok)issues.push(`${f.name}: expected ${f.type}`)}}$("validation").textContent=JSON.stringify({valid:!issues.length,issues},null,2)}catch(e){$("validation").textContent="JSON ERROR: "+e.message}};
$("apply-rules").onclick=()=>{try{const obj=JSON.parse($("sample").value),tags=[];for(const r of rules){const v=obj[r.field],x=r.value;let ok=false;if(r.operator==="equals")ok=String(v)===x;else if(r.operator==="contains")ok=String(v).toLowerCase().includes(x.toLowerCase());else if(r.operator==="gt")ok=Number(v)>Number(x);else if(r.operator==="lt")ok=Number(v)<Number(x);if(ok&&r.tag)tags.push(r.tag)}$("rule-result").textContent=JSON.stringify({tags:[...new Set(tags)]},null,2)}catch(e){$("rule-result").textContent="JSON ERROR: "+e.message}};
function dl(obj,name){const t=JSON.stringify(obj,null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("export-schema").onclick=()=>dl(schema,"prototag-schema.json");$("export-rules").onclick=()=>dl(rules,"prototag-rules.json");render();window.ProtoTag=Object.freeze({version:"0.2.0-alpha-web"});
})();
