(() => {
  "use strict";
  const $=id=>document.getElementById(id),state={rows:[],result:null,timer:null};
  function cfg(){return{kind:$("ts-kind").value,fast:Math.max(2,+$("ts-fast").value||10),slow:Math.max(3,+$("ts-slow").value||30),capital:Math.max(1,+$("ts-capital").value||10000),feeBps:Math.max(0,+$("ts-fee").value||0),sizePct:Math.max(1,Math.min(100,+$("ts-size").value||100))};}
  function download(text,name,type){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  function parseCsv(text){const lines=text.trim().split(/\r?\n/),head=lines.shift().split(",").map(x=>x.trim().toLowerCase()),idx=k=>head.indexOf(k);const ti=idx("time")>=0?idx("time"):idx("date"),ci=idx("close");if(ci<0)throw new Error("CSV requires close column.");return lines.map((l,i)=>{const c=l.split(",");return{time:ti>=0?c[ti]:String(i),close:Number(c[ci]),open:idx("open")>=0?Number(c[idx("open")]):Number(c[ci]),high:idx("high")>=0?Number(c[idx("high")]):Number(c[ci]),low:idx("low")>=0?Number(c[idx("low")]):Number(c[ci]),volume:idx("volume")>=0?Number(c[idx("volume")]):0};}).filter(x=>Number.isFinite(x.close));}
  function sample(){let p=70000;state.rows=Array.from({length:240},(_,i)=>{p*=1+Math.sin(i/13)*.002+(Math.random()-.5)*.012;return{time:new Date(Date.now()-(239-i)*86400000).toISOString().slice(0,10),open:p,high:p*1.005,low:p*.995,close:p,volume:1000+Math.random()*500};});renderData();}
  function renderData(){const r=state.rows;$("td-rows").textContent=r.length;$("td-first").textContent=r.length?`$${r[0].close.toFixed(2)}`:"—";$("td-last").textContent=r.length?`$${r.at(-1).close.toFixed(2)}`:"—";$("td-range").textContent=r.length?`$${Math.min(...r.map(x=>x.close)).toFixed(0)}–$${Math.max(...r.map(x=>x.close)).toFixed(0)}`:"—";draw("td-canvas",r.map(x=>x.close));}
  function draw(id,vals){const c=$(id),ctx=c.getContext("2d"),dpr=Math.max(1,Math.min(2,devicePixelRatio||1)),r=c.getBoundingClientRect(),w=Math.max(320,Math.round(r.width)),h=Math.max(280,Math.round(r.height||340));c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#050505";ctx.fillRect(0,0,w,h);if(vals.length<2)return;const lo=Math.min(...vals),hi=Math.max(...vals),range=Math.max(hi-lo,1e-9),pad=40;ctx.strokeStyle="#c0d674";ctx.lineWidth=2;ctx.beginPath();vals.forEach((v,i)=>{const x=pad+(w-pad*2)*i/(vals.length-1),y=h-30-(v-lo)/range*(h-60);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}
  function preview(){const s=BitTraderCore.signals(state.rows,cfg()),n=s.reduce((a,x,i)=>a+(i&&x!==s[i-1]?1:0),0);$("ts-output").textContent=JSON.stringify({config:cfg(),rows:state.rows.length,signalChanges:n,lastSignal:s.at(-1)??null},null,2);}
  function backtest(){state.result=BitTraderCore.backtest(state.rows,cfg());$("tb-equity").textContent=`$${state.result.finalEquity.toFixed(2)}`;$("tb-return").textContent=`${state.result.returnPct.toFixed(2)}%`;$("tb-dd").textContent=`${state.result.maxDrawdownPct.toFixed(2)}%`;$("tb-trades").textContent=state.result.trades;$("tb-output").textContent=JSON.stringify({...state.result,equity:`${state.result.equity.length} rows`},null,2);draw("tb-canvas",state.result.equity.map(x=>x.equity));}
  async function live(){const e=$("tr-live");e.textContent="LIVE FEED: FETCHING";e.className="runtime-badge partial";try{const r=await fetch($("tl-url").value,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json(),v=Object.values(j.result||{})[0],price=v?Number(v.c?.[0]):null;$("tl-output").textContent=JSON.stringify({fetchedAt:new Date().toISOString(),priceUsd:price,raw:j},null,2);e.textContent="LIVE FEED: OK";e.className="runtime-badge ok";}catch(err){$("tl-output").textContent=`ERROR: ${err.message}`;e.textContent="LIVE FEED: ERROR";e.className="runtime-badge bad";}}
  function auto(){if(state.timer){clearInterval(state.timer);state.timer=null;$("tl-auto").textContent="AUTO: OFF";}else{state.timer=setInterval(live,10000);$("tl-auto").textContent="AUTO: 10S";}}
  $("td-file").addEventListener("change",async()=>{const f=$("td-file").files?.[0];if(!f)return;try{state.rows=parseCsv(await f.text());renderData();}catch(e){alert(e.message);}$("td-file").value="";});$("td-sample").addEventListener("click",sample);$("td-clear").addEventListener("click",()=>{state.rows=[];state.result=null;renderData();});$("ts-preview").addEventListener("click",()=>{try{preview();}catch(e){$("ts-output").textContent=`ERROR: ${e.message}`;}});$("tb-run").addEventListener("click",()=>{try{backtest();}catch(e){$("tb-output").textContent=`ERROR: ${e.message}`;}});$("ta-run").addEventListener("click",()=>{try{$("ta-output").textContent=JSON.stringify(BitTraderCore.analyze(state.rows),null,2);}catch(e){$("ta-output").textContent=`ERROR: ${e.message}`;}});$("tl-fetch").addEventListener("click",live);$("tl-auto").addEventListener("click",auto);$("te-json").addEventListener("click",()=>{if(state.result)download(JSON.stringify(state.result,null,2),`bittrader-backtest-${Date.now()}.json`,"application/json");});$("te-csv").addEventListener("click",()=>{if(state.result)download("time,equity,price,signal\n"+state.result.equity.map(x=>`${x.time},${x.equity},${x.price},${x.signal}`).join("\n")+"\n",`bittrader-equity-${Date.now()}.csv`,"text/csv");});sample();
  window.BitTrader=Object.freeze({version:"0.8.0-alpha-web",parseCsv,backtest:BitTraderCore.backtest,analyze:BitTraderCore.analyze,getState:()=>({rows:state.rows.length,result:state.result})});
  window.ZZXHooks?.emit("bittrader:ready",{version:"0.8.0-alpha-web"});
})();
