(() => {
  "use strict";
  function sma(a,p){const out=new Array(a.length).fill(null);let s=0;for(let i=0;i<a.length;i++){s+=a[i];if(i>=p)s-=a[i-p];if(i>=p-1)out[i]=s/p;}return out;}
  function rsi(a,p=14){const out=new Array(a.length).fill(null);if(a.length<=p)return out;let gain=0,loss=0;for(let i=1;i<=p;i++){const d=a[i]-a[i-1];if(d>0)gain+=d;else loss-=d;}gain/=p;loss/=p;out[p]=loss===0?100:100-100/(1+gain/loss);for(let i=p+1;i<a.length;i++){const d=a[i]-a[i-1],g=Math.max(d,0),l=Math.max(-d,0);gain=(gain*(p-1)+g)/p;loss=(loss*(p-1)+l)/p;out[i]=loss===0?100:100-100/(1+gain/loss);}return out;}
  function signals(rows,cfg){const c=rows.map(x=>x.close),out=new Array(c.length).fill(0);if(cfg.kind==="buyhold"){out.fill(1);return out;}if(cfg.kind==="sma"){const f=sma(c,cfg.fast),s=sma(c,cfg.slow);for(let i=0;i<c.length;i++)out[i]=f[i]!=null&&s[i]!=null&&f[i]>s[i]?1:0;return out;}const rr=rsi(c,cfg.fast);for(let i=0;i<c.length;i++){if(rr[i]==null)continue;if(i&&out[i-1]===1)out[i]=rr[i]>70?0:1;else out[i]=rr[i]<30?1:0;}return out;}
  function backtest(rows,cfg){if(rows.length<2)throw new Error("Need market data.");const sig=signals(rows,cfg),fee=(cfg.feeBps||0)/10000,size=(cfg.sizePct||100)/100;let cash=cfg.capital,btc=0,trades=0;const eq=[];for(let i=0;i<rows.length;i++){const p=rows[i].close,target=sig[i];if(target===1&&btc===0){const spend=cash*size,net=spend*(1-fee);btc=net/p;cash-=spend;trades++;}else if(target===0&&btc>0){cash+=btc*p*(1-fee);btc=0;trades++;}eq.push({time:rows[i].time,equity:cash+btc*p,price:p,signal:target});}const final=eq.at(-1).equity,ret=(final/cfg.capital-1);let peak=eq[0].equity,maxDD=0;for(const x of eq){peak=Math.max(peak,x.equity);maxDD=Math.max(maxDD,(peak-x.equity)/peak);}return{config:cfg,finalEquity:final,returnPct:ret*100,maxDrawdownPct:maxDD*100,trades,equity:eq};}
  function analyze(rows){const c=rows.map(x=>x.close),rets=[];for(let i=1;i<c.length;i++)rets.push(c[i]/c[i-1]-1);const mean=rets.reduce((s,x)=>s+x,0)/(rets.length||1),variance=rets.reduce((s,x)=>s+(x-mean)**2,0)/(rets.length||1),vol=Math.sqrt(variance);const fast=sma(c,10).at(-1),slow=sma(c,30).at(-1);return{rows:rows.length,lastClose:c.at(-1),meanReturnPerBar:mean,volatilityPerBar:vol,trend:fast&&slow?(fast>slow?"above 10/30 SMA trend":"below 10/30 SMA trend"):"insufficient",high:Math.max(...c),low:Math.min(...c)};}
  window.BitTraderCore=Object.freeze({sma,rsi,signals,backtest,analyze});
})();
