(()=>{"use strict";const $=id=>document.getElementById(id);const probes=[];let session={running:false,started:0,elapsed:0,duration:600000,lastProbe:0,raf:0},pacer={run:false,cycle:0,timer:0,phase:"READY"};
const pad=n=>String(Math.floor(n)).padStart(2,"0");const fmt=ms=>`${pad(ms/60000)}:${pad((ms%60000)/1000)}`;
function tick(){if(!session.running)return;const now=performance.now(),e=session.elapsed+(now-session.started),r=Math.max(0,session.duration-e);$("session-elapsed").textContent=fmt(e);$("session-remaining").textContent=fmt(r);const int=Math.max(10000,+$("probe-interval").value*1000);if(e-session.lastProbe>=int){session.lastProbe=e;$("probe-count").textContent=probes.length+" + due"}if(r<=0){session.running=false;cancelAnimationFrame(session.raf);$("session-remaining").textContent="00:00";return}session.raf=requestAnimationFrame(tick)}
$("start-session").onclick=()=>{session.duration=Math.max(60000,+$("session-minutes").value*60000);if(!session.running){session.running=true;session.started=performance.now();session.raf=requestAnimationFrame(tick)}};
$("pause-session").onclick=()=>{if(!session.running)return;session.elapsed+=performance.now()-session.started;session.running=false;cancelAnimationFrame(session.raf)};
$("reset-session").onclick=()=>{session.running=false;cancelAnimationFrame(session.raf);session.elapsed=0;session.lastProbe=0;session.duration=Math.max(60000,+$("session-minutes").value*60000);$("session-elapsed").textContent="00:00";$("session-remaining").textContent=fmt(session.duration);$("probe-count").textContent=probes.length};
function pacerStop(){pacer.run=false;clearTimeout(pacer.timer);$("breath-phase").textContent="READY";$("breath-orb").style.transform="scale(1)"}
function pacerStep(){if(!pacer.run)return;const inh=Math.max(1,+$("inhale").value),exh=Math.max(1,+$("exhale").value),max=Math.max(1,+$("cycles").value);if(pacer.phase==="READY"||pacer.phase==="EXHALE"){if(pacer.phase==="EXHALE")pacer.cycle++;if(pacer.cycle>=max){pacerStop();return}pacer.phase="INHALE";$("breath-phase").textContent="INHALE";$("breath-orb").style.transition=`transform ${inh}s linear`;$("breath-orb").style.transform="scale(1.28)";pacer.timer=setTimeout(()=>{pacer.phase="EXHALE";$("breath-phase").textContent="EXHALE";$("breath-orb").style.transition=`transform ${exh}s linear`;$("breath-orb").style.transform="scale(1)";pacer.timer=setTimeout(pacerStep,exh*1000)},inh*1000)}$("cycle-count").textContent=`${pacer.cycle+1} / ${max}`}
$("start-pacer").onclick=()=>{pacerStop();pacer={run:true,cycle:0,timer:0,phase:"READY"};const cadence=60/(Math.max(1,+$("inhale").value)+Math.max(1,+$("exhale").value));$("cadence").textContent=cadence.toFixed(1)+" bpm";pacerStep()};$("stop-pacer").onclick=pacerStop;
function render(){const el=$("probe-list");el.replaceChildren();probes.slice().reverse().forEach(p=>{const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${new Date(p.at).toLocaleTimeString()}</strong><p>stability ${p.stability}/5 · wandering ${p.wandering}/5 · effort ${p.effort}/5</p><p>${p.note||""}</p>`;el.append(a)});const mean=k=>probes.length?probes.reduce((s,p)=>s+p[k],0)/probes.length:null;for(const[k,id]of[["stability","mean-stability"],["wandering","mean-wandering"],["effort","mean-effort"]]){const m=mean(k);$(id).textContent=m===null?"—":m.toFixed(2)}draw()}
function draw(){const c=$("attention-chart"),x=c.getContext("2d"),w=c.width,h=c.height;x.clearRect(0,0,w,h);if(!probes.length)return;const keys=["stability","wandering","effort"];keys.forEach((k,j)=>{x.beginPath();probes.forEach((p,i)=>{const px=30+i/(Math.max(1,probes.length-1))*(w-60),py=h-30-(p[k]-1)/4*(h-60);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle=["#c0d674","#e6a42b","#e8e8e8"][j];x.lineWidth=2;x.stroke()})}
$("record-probe").onclick=()=>{probes.push({at:new Date().toISOString(),stability:+$("stability").value,wandering:+$("wandering").value,effort:+$("effort").value,note:$("probe-note").value.trim()});$("probe-note").value="";$("probe-count").textContent=probes.length;render()};
$("run-sim").onclick=()=>{const mins=Math.max(1,+$("sim-minutes").value),base=Math.max(0,Math.min(1,+$("sim-base").value)),rec=Math.max(0,Math.min(1,+$("sim-recovery").value));let s=base;const out=[];for(let m=0;m<mins;m++){const wander=0.12+0.08*Math.sin(m/4),drop=wander*(1-s),recover=rec*(1-s);s=Math.max(0,Math.min(1,s-drop+recover));out.push({minute:m+1,stability:+s.toFixed(4)})}$("sim-output").textContent=JSON.stringify({model:"toy attention-state simulation",parameters:{mins,base,recovery:rec},series:out},null,2)};
function dl(t,n,type){const b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("export-json").onclick=()=>{const doc={schema:"zzx.dharma-lab.session.v1",protocol:{name:$("protocol-name").value,instruction:$("instruction").value,minutes:+$("session-minutes").value,probeIntervalSeconds:+$("probe-interval").value},probes};const t=JSON.stringify(doc,null,2);dl(t,"dharma-lab-session.json","application/json");$("export-output").textContent=t};
$("export-csv").onclick=()=>{const t="timestamp,stability,wandering,effort,note\n"+probes.map(p=>[p.at,p.stability,p.wandering,p.effort,JSON.stringify(p.note)].join(",")).join("\n");dl(t,"dharma-lab-probes.csv","text/csv");$("export-output").textContent=t};
$("session-remaining").textContent=fmt(+$("session-minutes").value*60000);window.DharmaLab=Object.freeze({version:"0.1.0-alpha-web",getProbes:()=>probes.slice()});window.ZZXHooks?.emit("dharma-lab:ready",{version:"0.1.0-alpha-web"})})();
