(()=>{"use strict";const $=id=>document.getElementById(id);let rec=null,segments=[],mediaRecorder=null,chunks=[];
function add(text,source="browser",final=true){if(!text.trim())return;segments.push({start:null,end:null,speaker:"unknown",text:text.trim(),source,final});render()}
function render(){const e=$("segments");e.replaceChildren();segments.forEach((s,i)=>{const d=document.createElement("div");d.className="segment";d.innerHTML=`<strong>${i+1}. ${s.speaker}</strong> · ${s.source}<div>${s.text}</div>`;e.append(d)});$("count").textContent=segments.length;$("words").textContent=segments.reduce((n,s)=>n+s.text.split(/\s+/).filter(Boolean).length,0)}
$("start-browser").onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$("status").textContent="Browser SpeechRecognition API unavailable. Use the native engines or import a transcript.";return}rec=new SR();rec.continuous=true;rec.interimResults=true;rec.lang=$("lang").value;rec.onresult=e=>{for(let i=e.resultIndex;i<e.results.length;i++){if(e.results[i].isFinal)add(e.results[i][0].transcript,"browser-speechrecognition",true)}};rec.onerror=e=>$("status").textContent="STT ERROR: "+e.error;rec.onend=()=>{$("status").textContent="Browser STT stopped."};rec.start();$("status").textContent="Browser STT listening…"};
$("stop-browser").onclick=()=>{try{rec?.stop()}catch{}};
$("mic-record").onclick=async()=>{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>chunks.push(e.data);mediaRecorder.onstop=()=>{stream.getTracks().forEach(t=>t.stop());const b=new Blob(chunks,{type:mediaRecorder.mimeType}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="zzxstt-capture.webm";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};mediaRecorder.start();$("capture-state").textContent="RECORDING"};
$("mic-stop").onclick=()=>{if(mediaRecorder&&mediaRecorder.state!=="inactive"){mediaRecorder.stop();$("capture-state").textContent="STOPPED"}};
$("import").onchange=async()=>{const f=$("import").files[0];if(!f)return;const t=await f.text();try{const j=JSON.parse(t);const arr=Array.isArray(j)?j:(j.segments||[]);arr.forEach(s=>add(s.text||String(s),"import",true))}catch{t.split(/\r?\n/).filter(Boolean).forEach(line=>add(line,"import",true))}$("import").value=""};
$("job").onclick=()=>{$("job-out").textContent=JSON.stringify({schema:"zzx.stt.job.v1",engine:$("engine").value,language:$("lang").value,diarization:$("diarize").checked,segmentation:true,timestamps:true,input:"operator-selected local media",output:["json","txt","srt"],networkRequired:false},null,2)};
$("export").onclick=()=>{const t=JSON.stringify({schema:"zzx.stt.transcript.v1",language:$("lang").value,segments,exported:new Date().toISOString()},null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="zzxstt-transcript.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
render();window.ZZXSTT=Object.freeze({version:"0.1.0-alpha-web",fakeTranscription:false});
})();
