(()=>{"use strict";const $=id=>document.getElementById(id),video=$("video"),canvas=$("canvas"),ctx=canvas.getContext("2d",{willReadFrequently:true});let url=null,frames=[];
$("file").onchange=()=>{const f=$("file").files[0];if(!f)return;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);video.src=url;$("source").textContent=f.name;$("file").value="";frames=[];renderFrames()};
async function seek(t){video.currentTime=Math.max(0,Math.min(t,Math.max(0,(video.duration||0)-.02)));await new Promise(resolve=>{let done=false;const fin=()=>{if(done)return;done=true;resolve()};video.addEventListener("seeked",fin,{once:true});setTimeout(fin,1200)})}
function dims(){const maxW=Math.max(64,Math.min(640,+$("width").value||320)),ratio=video.videoWidth&&video.videoHeight?video.videoHeight/video.videoWidth:9/16,w=Math.round(maxW/2)*2,h=Math.max(2,Math.round(w*ratio/2)*2);canvas.width=w;canvas.height=h;return{w,h}}
$("capture").onclick=()=>{if(!video.videoWidth)return;const {w,h}=dims();ctx.drawImage(video,0,0,w,h);const data=ctx.getImageData(0,0,w,h);frames.push({time:video.currentTime,data});renderFrames()};
$("capture-range").onclick=async()=>{if(!video.videoWidth)return;frames=[];const start=Math.max(0,+$("start").value||0),end=Math.min(video.duration||0,+$("end").value||video.duration||0),fps=Math.max(.2,Math.min(20,+$("fps").value||4));if(end<=start)return;const {w,h}=dims(),count=Math.min(120,Math.max(1,Math.floor((end-start)*fps)+1));for(let i=0;i<count;i++){const t=Math.min(end,start+i/fps);await seek(t);ctx.drawImage(video,0,0,w,h);frames.push({time:t,data:ctx.getImageData(0,0,w,h)});$("state").textContent=`CAPTURE ${i+1}/${count}`}renderFrames();$("state").textContent="READY"};
function renderFrames(){const e=$("thumbs");e.replaceChildren();frames.forEach((f,i)=>{const c=document.createElement("canvas");c.width=f.data.width;c.height=f.data.height;c.getContext("2d").putImageData(f.data,0,0);const img=document.createElement("img");img.src=c.toDataURL("image/jpeg",.75);img.title=`${i+1}: ${f.time.toFixed(3)}s`;e.append(img)});$("frame-count").textContent=frames.length}
$("png").onclick=()=>{if(!frames.length)return;const f=frames[frames.length-1];canvas.width=f.data.width;canvas.height=f.data.height;ctx.putImageData(f.data,0,0);const a=document.createElement("a");a.href=canvas.toDataURL("image/png");a.download=`vidghee-frame-${f.time.toFixed(3)}.png`;a.click()};
$("gif").onclick=()=>{if(!frames.length)return;const w=frames[0].data.width,h=frames[0].data.height;if(frames.some(f=>f.data.width!==w||f.data.height!==h)){$("state").textContent="All frames must share dimensions.";return}const fps=Math.max(.2,Math.min(20,+$("fps").value||4)),delay=Math.max(2,Math.round(100/fps));$("state").textContent="ENCODING GIF";setTimeout(()=>{try{const bytes=GIF332.encode(frames.map(f=>f.data),w,h,delay,0),b=new Blob([bytes],{type:"image/gif"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="vidghee.gif";a.click();$("gif-bytes").textContent=bytes.length.toLocaleString();$("state").textContent="GIF EXPORTED";setTimeout(()=>URL.revokeObjectURL(u),3000)}catch(e){$("state").textContent="GIF ERROR: "+e.message}},20)};
$("thumbsheet").onclick=()=>{if(!frames.length)return;const tw=160,th=Math.round(tw*frames[0].data.height/frames[0].data.width),cols=Math.min(5,frames.length),rows=Math.ceil(frames.length/cols),c=document.createElement("canvas");c.width=cols*tw;c.height=rows*th;const x=c.getContext("2d");frames.forEach((f,i)=>{const tmp=document.createElement("canvas");tmp.width=f.data.width;tmp.height=f.data.height;tmp.getContext("2d").putImageData(f.data,0,0);x.drawImage(tmp,(i%cols)*tw,Math.floor(i/cols)*th,tw,th)});const a=document.createElement("a");a.href=c.toDataURL("image/png");a.download="vidghee-thumbnail-sheet.png";a.click()};
$("clear").onclick=()=>{frames=[];renderFrames()};video.onloadedmetadata=()=>{$("duration").textContent=(video.duration||0).toFixed(2)+" s";$("end").value=Math.min(video.duration||0,10).toFixed(2);$("resolution").textContent=`${video.videoWidth}×${video.videoHeight}`};renderFrames();window.VidGhee=Object.freeze({version:"0.3.0-alpha-web",gifEncoder:"GIF89a-332"});
})();
