(()=>{"use strict";
const R="23456789TJQKA",S="CDHS";
function deck(){const a=[];for(const r of R)for(const s of S)a.push(r+s);return a}
function cards(text){const a=String(text||"").toUpperCase().trim().split(/\s+/).filter(Boolean);for(const c of a)if(!/^[2-9TJQKA][CDHS]$/.test(c))throw new Error(`Invalid card: ${c}`);if(new Set(a).size!==a.length)throw new Error("Duplicate card.");return a}
function rank5(cs){const rs=cs.map(c=>R.indexOf(c[0])+2).sort((a,b)=>b-a),suits=cs.map(c=>c[1]),counts={};rs.forEach(r=>counts[r]=(counts[r]||0)+1);let uniq=[...new Set(rs)].sort((a,b)=>b-a);if(uniq[0]===14)uniq.push(1);let straight=0;for(let i=0;i<=uniq.length-5;i++)if(uniq[i]-uniq[i+4]===4){straight=uniq[i];break}const flush=suits.every(s=>s===suits[0]),groups=Object.entries(counts).map(([r,n])=>[+r,n]).sort((a,b)=>b[1]-a[1]||b[0]-a[0]);if(straight&&flush)return[8,straight];if(groups[0][1]===4)return[7,groups[0][0],groups[1][0]];if(groups[0][1]===3&&groups[1][1]===2)return[6,groups[0][0],groups[1][0]];if(flush)return[5,...rs];if(straight)return[4,straight];if(groups[0][1]===3)return[3,groups[0][0],...groups.filter(x=>x[1]===1).map(x=>x[0]).sort((a,b)=>b-a)];if(groups[0][1]===2&&groups[1][1]===2){const ps=[groups[0][0],groups[1][0]].sort((a,b)=>b-a),k=groups.find(x=>x[1]===1)[0];return[2,...ps,k]}if(groups[0][1]===2)return[1,groups[0][0],...groups.filter(x=>x[1]===1).map(x=>x[0]).sort((a,b)=>b-a)];return[0,...rs]}
function cmp(a,b){for(let i=0;i<Math.max(a.length,b.length);i++){const d=(a[i]||0)-(b[i]||0);if(d)return d>0?1:-1}return 0}
function best7(cs){let best=null;for(let a=0;a<cs.length-4;a++)for(let b=a+1;b<cs.length-3;b++)for(let c=b+1;c<cs.length-2;c++)for(let d=c+1;d<cs.length-1;d++)for(let e=d+1;e<cs.length;e++){const r=rank5([cs[a],cs[b],cs[c],cs[d],cs[e]]);if(!best||cmp(r,best)>0)best=r}return best}
function rng(seed=Date.now()){let x=seed>>>0;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function holdem({hero,board=[],iterations=10000,seed=12345,range=null}){hero=cards(hero.join?hero.join(" "):hero);board=cards(board.join?board.join(" "):board);if(hero.length!==2)throw new Error("Hero needs exactly 2 cards.");if(board.length>5)throw new Error("Board max 5.");const used=[...hero,...board];if(new Set(used).size!==used.length)throw new Error("Duplicate known card.");const base=deck().filter(c=>!used.includes(c)),rand=rng(seed);let win=0,tie=0,loss=0;
for(let n=0;n<iterations;n++){let opp,pool=[...base];if(range&&range.length){const viable=range.filter(x=>x.cards.every(c=>pool.includes(c)));if(!viable.length)throw new Error("No viable opponent range combos.");const total=viable.reduce((s,x)=>s+x.weight,0),r=rand()*total;let acc=0,chosen=viable[0];for(const x of viable){acc+=x.weight;if(r<=acc){chosen=x;break}}opp=chosen.cards;pool=pool.filter(c=>!opp.includes(c))}else{opp=[];for(let i=0;i<2;i++)opp.push(pool.splice(Math.floor(rand()*pool.length),1)[0])}const b=[...board];while(b.length<5)b.push(pool.splice(Math.floor(rand()*pool.length),1)[0]);const c=cmp(best7([...hero,...b]),best7([...opp,...b]));if(c>0)win++;else if(c===0)tie++;else loss++}
return{iterations,win, tie, loss, winPct:100*win/iterations,tiePct:100*tie/iterations,lossPct:100*loss/iterations,equityPct:100*(win+tie/2)/iterations}}
function parseRange(text){const out=[];for(const line of String(text||"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean)){const [cs,w="1"]=line.split(",");const c=cards(cs);if(c.length!==2)throw new Error(`Range combo must have 2 cards: ${line}`);const weight=Number(w);if(!(weight>0))throw new Error(`Invalid weight: ${line}`);out.push({cards:c,weight})}return out}
window.CasBraCore=Object.freeze({deck,cards,rank5,best7,holdem,parseRange})})();
