(()=>{"use strict";const $=id=>document.getElementById(id),state={result:null,range:null,annotations:null,media:null};
function dl(t,n){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$("validate").onclick=()=>{try{const k=CasBraCore.cards($("known").value),d=CasBraCore.cards($("dead").value),all=[...k,...d];if(new Set(all).size!==all.length)throw new Error("Duplicate between known/dead sets.");$("cards-output").textContent=JSON.stringify({game:$("game").value,known:k,dead:d,remaining:52-all.length},null,2)}catch(e){$("cards-output").textContent=`ERROR: ${e.message}`}};
$("reset-deck").onclick=()=>{$("known").value="";$("dead").value="";$("cards-output").textContent=""};
$("parse-range").onclick=()=>{try{state.range=CasBraCore.parseRange($("range").value);$("range-output").textContent=JSON.stringify(state.range,null,2)}catch(e){$("range-output").textContent=`ERROR: ${e.message}`}};
$("run-sim").onclick=()=>{try{const it=Math.max(100,Math.min(200000,+$("iters").value||20000));state.result=CasBraCore.holdem({hero:$("hero").value,board:$("board").value,iterations:it,seed:Date.now()>>>0,range:state.range});$("win").textContent=`${state.result.winPct.toFixed(2)}%`;$("tie").textContent=`${state.result.tiePct.toFixed(2)}%`;$("loss").textContent=`${state.result.lossPct.toFixed(2)}%`;$("equity").textContent=`${state.result.equityPct.toFixed(2)}%`;$("sim-output").textContent=JSON.stringify(state.result,null,2)}catch(e){$("sim-output").textContent=`ERROR: ${e.message}`}};
$("media").onchange=()=>{const f=$("media").files?.[0];if(!f)return;if(state.media)URL.revokeObjectURL(state.media);state.media=URL.createObjectURL(f);$("image").style.display=f.type.startsWith("image/")?"block":"none";$("video").style.display=f.type.startsWith("video/")?"block":"none";if(f.type.startsWith("image/"))$("image").src=state.media;else $("video").src=state.media;$("vision-output").textContent=JSON.stringify({name:f.name,type:f.type,bytes:f.size,mode:"local preview / manual-or-external annotations"},null,2)};
$("apply-annotations").onclick=()=>{try{state.annotations=JSON.parse($("annotations").value);$("vision-output").textContent=JSON.stringify({accepted:true,annotations:state.annotations,note:"Browser baseline does not infer hidden state from pixels."},null,2)}catch(e){$("vision-output").textContent=`ERROR: ${e.message}`}};
$("export-json").onclick=()=>{const x={schema:"zzx.casbra.session.v1",exportedAt:new Date().toISOString(),game:$("game").value,hero:$("hero").value,board:$("board").value,range:state.range,result:state.result,annotations:state.annotations};dl(JSON.stringify(x,null,2),`casbra-${Date.now()}.json`);$("export-output").textContent=JSON.stringify({...x,result:state.result?"included":null},null,2)};
window.CasBra=Object.freeze({version:"0.1.0-alpha-web",holdem:CasBraCore.holdem,parseRange:CasBraCore.parseRange,getResult:()=>state.result});window.ZZXHooks?.emit("casbra:ready",{version:"0.1.0-alpha-web"})})();
