#!/usr/bin/env python3
from pathlib import Path

ROOT=Path(__file__).resolve().parent
PARTS=[
    "js/sources.js",
    "js/fetch.js",
    "js/provider.js",
    "js/live.js",
    "js/analyzer.js",
    "js/model.js",
    "js/scaler.js",
    "js/sorter.js",
    "js/layout.js",
    "js/themes.js",
    "js/renderer.js",
    "js/animation.js",
    "js/txfetcher.js",
    "js/inspector.js",
    "js/reader-store.js",
    "js/controller.js",
]

banner="""/*
 * Mempool Tiles v1.6.2
 * ZZX-Labs / 0xdeadbeef
 * Production single-request bundle generated by build.py.
 * Preserves the regular square tile-grid viewer; transport aligned with Specs.
 */\n\n"""
body=banner+"\n\n".join((ROOT/part).read_text(encoding="utf-8") for part in PARTS)+"\n"
(ROOT/"widget.js").write_text(body,encoding="utf-8")
print(f"built widget.js: {len(body.encode('utf-8')):,} bytes")
