#!/usr/bin/env python3
from pathlib import Path

ROOT=Path(__file__).resolve().parent
PARTS=[
    "js/sources.js",
    "js/fetch.js",
    "js/analyzer.js",
    "js/provider.js",
    "js/live.js",
    "js/model.js",
    "js/scaler.js",
    "js/sorter.js",
    "js/layout.js",
    "js/themes.js",
    "js/renderer.js",
    "js/animation.js",
    "js/txfetcher.js",
    "js/inspector.js",
    "js/widget-shell.js",
]

banner="""/*\n * Mempool Tiles v2.0.0\n * ZZX-Labs / 0xdeadbeef\n * Production bundle generated by build.py.\n * Square-only exact-cover projected next-block visualizer.\n */\n\n"""
body=banner+"\n\n".join((ROOT/part).read_text(encoding="utf-8") for part in PARTS)+"\n"
(ROOT/"widget.js").write_text(body,encoding="utf-8")
print(f"built widget.js: {len(body.encode('utf-8')):,} bytes")
