(() => {
"use strict";
const $=id=>document.getElementById(id),KEY="zzx-bitpav-ledger-v1",state={entries:JSON.parse(localStorage.getItem(KEY)||"[]"),spot:100000,timer:null};
function save(){localStorage.setItem(KEY,JSON.stringify(state.entries));}
function dl(t,n,type){const b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function add(e){state.entries.push(e);save();render();}
function form(){return{id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),type:$("pl-type").value,btc:Math.max(.00000001,+$("pl-btc").value||.00000001),price:Math.max(.01,+$("pl-price").value||.01),fee:Math.max(0,+$("pl-fee").value||0),at:$("pl-date").value?new Date($("pl-date").value).toISOString():new Date().toISOString(),source:$("pl-source").value.trim()};}
function render(){
  const root=$("pl-list");root.replaceChildren();for(const e of state.entries.slice().reverse()){const x=document.createElement("article");x.className="z-list-item";x.innerHTML="<strong></strong><p></p>";x.querySelector("strong").textContent=`${e.type.toUpperCase()} ${e.btc} BTC @ $${e.price.toLocaleString()}`;x.querySelector("p").textContent=`fee $${e.fee} · ${e.source} · ${e.at}`;root.appendChild(x);}if(!state.entries.length)root.innerHTML='<div class="z-list-item"><p>No entries.</p></div>';
  const m=BitPavCore.metrics(state.entries,state.spot);$("pd-btc").textContent=m.btcHeld.toFixed(8);$("pd-cost").textContent=`$${m.costBasisUsd.toFixed(2)}`;$("pd-value").textContent=`$${m.marketValueUsd.toFixed(2)}`;$("pd-pnl").textContent=`$${m.totalPnlUsd.toFixed(2)}`;$("pd-output").textContent=JSON.stringify({...m,rows:`${m.rows.length} ledger rows`},null,2);draw(m.rows);
}
function draw(rows){const c=$("pc-canvas"),ctx=c.getContext("2d"),dpr=Math.max(1,Math.min(2,devicePixelRatio||1)),r=c.getBoundingClientRect(),w=Math.max(320,Math.round(r.width)),h=Math.max(280,Math.round(r.height||360));c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#050505";ctx.fillRect(0,0,w,h);if(!rows.length)return;const vals=rows.map(x=>x.btcAfter*state.spot),costs=rows.map(x=>x.costAfter),all=[...vals,...costs],lo=Math.min(...all,0),hi=Math.max(...all,1),range=hi-lo||1,pad=42;for(const [series,color] of [[costs,"#e6a42b"],[vals,"#c0d674"]]){ctx.strokeStyle=color;ctx.lineWidth=2;ctx.beginPath();series.forEach((v,i)=>{const x=pad+(w-pad*2)*(series.length===1?.5:i/(series.length-1)),y=h-30-(v-lo)/range*(h-60);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}}
async function fetchSpot(){const e=$("pv-net");e.textContent="PRICE: FETCHING";e.className="runtime-badge partial";try{const r=await fetch($("pp-url").value,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const j=await r.json();let p=Number(j?.data?.amount??j?.price??j?.last??j?.result?.price);if(!Number.isFinite(p)){const vals=[];(function walk(o){if(!o||typeof o!=="object")return;for(const [k,v] of Object.entries(o)){if(["price","last","amount"].includes(k.toLowerCase())&&Number.isFinite(Number(v)))vals.push(Number(v));else walk(v);}})(j);p=vals[0];}if(!Number.isFinite(p))throw new Error("Could not locate price in response.");state.spot=p;$("pp-manual").value=p;$("pp-output").textContent=JSON.stringify({spotUsd:p,fetchedAt:new Date().toISOString()},null,2);e.textContent="PRICE: LIVE";e.className="runtime-badge ok";render();}catch(err){$("pp-output").textContent=`ERROR: ${err.message}`;e.textContent="PRICE: ERROR";e.className="runtime-badge bad";}}
function auto(){if(state.timer){clearInterval(state.timer);state.timer=null;$("pp-auto").textContent="AUTO: OFF";}else{const ms=Math.max(250,+$("pp-ms").value||250);state.timer=setInterval(fetchSpot,ms);$("pp-auto").textContent=`AUTO: ${ms}MS`;}}
$("pl-add").addEventListener("click",()=>add(form()));$("pl-sample").addEventListener("click",()=>{state.entries=[{id:"s1",type:"buy",btc:.05,price:60000,fee:5,at:"2024-01-01T00:00:00.000Z",source:"sample"},{id:"s2",type:"buy",btc:.025,price:80000,fee:3,at:"2025-01-01T00:00:00.000Z",source:"sample"},{id:"s3",type:"sell",btc:.01,price:95000,fee:2,at:"2026-01-01T00:00:00.000Z",source:"sample"}];save();render();});
$("pp-apply").addEventListener("click",()=>{state.spot=Math.max(.01,+$("pp-manual").value||.01);$("pv-net").textContent="PRICE: MANUAL";$("pv-net").className="runtime-badge ok";render();});$("pp-fetch").addEventListener("click",fetchSpot);$("pp-auto").addEventListener("click",auto);
$("pe-json").addEventListener("click",()=>dl(JSON.stringify({schema:"zzx.bitpav.ledger.v1",spotUsd:state.spot,entries:state.entries},null,2),`bitpav-${Date.now()}.json`,"application/json"));$("pe-csv").addEventListener("click",()=>dl("type,btc,price_usd,fee_usd,at,source\n"+state.entries.map(e=>`${e.type},${e.btc},${e.price},${e.fee},${e.at},"${String(e.source).replace(/"/g,'""')}"`).join("\n")+"\n",`bitpav-${Date.now()}.csv`,"text/csv"));$("pe-import").addEventListener("change",async()=>{const f=$("pe-import").files?.[0];if(!f)return;try{const j=JSON.parse(await f.text());state.entries=Array.isArray(j)?j:j.entries;if(!Array.isArray(state.entries))throw new Error("No entries array.");if(Number.isFinite(+j.spotUsd))state.spot=+j.spotUsd;save();render();$("pe-output").textContent=`Imported ${state.entries.length} entries.`;}catch(e){$("pe-output").textContent=`ERROR: ${e.message}`;}$("pe-import").value="";});
render();
window.BitPav=Object.freeze({version:"0.1.0-alpha-web",metrics:BitPavCore.metrics,setSpot(p){state.spot=+p;render();},getLedger:()=>JSON.parse(JSON.stringify(state.entries))});
window.ZZXHooks?.emit("bitpav:ready",{version:"0.1.0-alpha-web"});
})();
