(() => {
"use strict";const $=id=>document.getElementById(id),state={seed:null,commitment:null,deck:null,pos:0,player:[],dealer:[],active:false,lastProof:null,provider:null};
function dl(t,n){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function render(hideDealer=false){$("bj-player").textContent=state.player.join(" ");$("bj-player-score").textContent=BitJackCore.score(state.player);$("bj-dealer").textContent=hideDealer&&state.dealer.length?`${state.dealer[0]} ??`:state.dealer.join(" ");$("bj-dealer-score").textContent=hideDealer?"?":BitJackCore.score(state.dealer);}
async function commit(){state.seed=$("bf-server").value.trim();if(!state.seed)throw new Error("Server seed required.");state.commitment=await BitJackCore.sha256(state.seed);$("bf-output").textContent=JSON.stringify({commitment:state.commitment,serverSeed:"hidden until hand proof"},null,2);}
async function newHand(){if(!state.commitment)throw new Error("Commit a server seed first.");state.deck=await BitJackCore.deck(state.seed,$("bj-client").value);state.pos=0;state.player=[state.deck[state.pos++],state.deck[state.pos++]];state.dealer=[state.deck[state.pos++],state.deck[state.pos++]];state.active=true;render(true);if(BitJackCore.score(state.player)===21)finish();}
function hit(){if(!state.active)return;state.player.push(state.deck[state.pos++]);render(true);if(BitJackCore.score(state.player)>=21)finish();}
function stand(){if(!state.active)return;while(BitJackCore.score(state.dealer)<17)state.dealer.push(state.deck[state.pos++]);finish();}
function finish(){state.active=false;while(BitJackCore.score(state.dealer)<17&&BitJackCore.score(state.player)<=21)state.dealer.push(state.deck[state.pos++]);const p=BitJackCore.score(state.player),d=BitJackCore.score(state.dealer);let outcome=p>21?"dealer":d>21||p>d?"player":p===d?"push":"dealer";state.lastProof={schema:"zzx.bitjack.hand.v1",commitment:state.commitment,serverSeed:state.seed,clientSeed:$("bj-client").value,deck:state.deck,player:state.player,dealer:state.dealer,outcome};$("bj-output").textContent=JSON.stringify({outcome,playerScore:p,dealerScore:d},null,2);$("bp-json").value=JSON.stringify(state.lastProof,null,2);render(false);}
async function verify(v){const c=await BitJackCore.sha256(v.serverSeed),d=await BitJackCore.deck(v.serverSeed,v.clientSeed);return{valid:c===v.commitment&&JSON.stringify(d)===JSON.stringify(v.deck),commitmentValid:c===v.commitment,deckValid:JSON.stringify(d)===JSON.stringify(v.deck)};}
$("bf-random").addEventListener("click",()=>{$("bf-server").value=BitJackCore.randomHex();});$("bf-commit").addEventListener("click",()=>commit().catch(e=>$("bf-output").textContent=`ERROR: ${e.message}`));$("bj-new").addEventListener("click",()=>newHand().catch(e=>$("bj-output").textContent=`ERROR: ${e.message}`));$("bj-hit").addEventListener("click",hit);$("bj-stand").addEventListener("click",stand);$("bp-verify").addEventListener("click",async()=>{try{$("bp-output").textContent=JSON.stringify(await verify(JSON.parse($("bp-json").value)),null,2);}catch(e){$("bp-output").textContent=`ERROR: ${e.message}`;}});$("bp-export").addEventListener("click",()=>{if(state.lastProof)dl(JSON.stringify(state.lastProof,null,2),`bitjack-hand-${Date.now()}.json`);});$("bs-send").addEventListener("click",async()=>{try{if(!state.provider)throw new Error("No settlement provider registered.");const x={player:$("bs-player").value,amountSats:+$("bs-sats").value||0,paymentReference:$("bs-ref").value,handProof:state.lastProof},r=await state.provider(x);$("bs-output").textContent=JSON.stringify({instruction:x,result:r},null,2);}catch(e){$("bs-output").textContent=`ERROR: ${e.message}`;}});$("bf-server").value=BitJackCore.randomHex();render();
window.BitJack=Object.freeze({version:"0.1.0-alpha-web",verify,shuffle:BitJackCore.deck,registerSettlementProvider(fn){state.provider=fn;},getProof:()=>state.lastProof});
window.ZZXHooks?.emit("bitjack:ready",{version:"0.1.0-alpha-web"});
})();
