(function(){
  "use strict";
  const W=window,D=document,ID="nodes-by-asn";
  const q=(r,s)=>r?.querySelector?.(s)||null,set=(r,s,v)=>{const e=q(r,s);if(e)e.textContent=v==null?"—":String(v)};
  const n=v=>Number.isFinite(Number(v))?Math.round(Number(v)).toLocaleString():"—",pct=v=>Number.isFinite(Number(v))?`${(Number(v)*100).toFixed(2)}%`:"—";
  async function ensure(){if(Number(W.ZZXBitnodes?.__version||0)>=8)return;await new Promise((ok,fail)=>{const s=D.createElement("script");s.src=W.ZZXAPI?.url?W.ZZXAPI.url("/__partials/widgets/_shared/zzx-bitnodes.js"):"/__partials/widgets/_shared/zzx-bitnodes.js";s.defer=true;s.onload=ok;s.onerror=fail;(D.head||D.documentElement).appendChild(s)})}
  function flag(code){if(!/^[A-Z]{2}$/.test(code||""))return "—";return String.fromCodePoint(...[...code].map(c=>127397+c.charCodeAt(0)))}
  function countryName(code){try{return new Intl.DisplayNames(["en"],{type:"region"}).of(code)||code}catch(_){return code||"Unlocated"}}
  function rows(snap){return Object.entries(snap.byAsn||{}).map(([key,count])=>{const [asn,org,country]=key.split("|");return{asn,org,country,nodes:Number(count)||0}}).sort((a,b)=>b.nodes-a.nodes)}
  function render(root,detail){const snap=detail?.snapshot;if(!snap)return;const total=Number(snap.reachableNodes??snap.nodeCount??0),all=rows(snap),needle=String(q(root,"[data-nba-search]")?.value||"").toLowerCase();const shown=needle?all.filter(r=>`${r.asn} ${r.org} ${r.country} ${countryName(r.country)}`.toLowerCase().includes(needle)):all;set(root,"[data-nba-total]",n(all.reduce((a,b)=>a+b.nodes,0)));set(root,"[data-nba-sub]",`${all.length.toLocaleString()} autonomous systems · ${pct(total?all.reduce((a,b)=>a+b.nodes,0)/total:NaN)} network coverage`);const body=q(root,"[data-nba-body]");if(body){body.replaceChildren();shown.slice(0,100).forEach((r,i)=>{const row=D.createElement("div");row.className="nodes-by-asn__row";row.innerHTML=`<div>${i+1}</div><div><span class="nodes-by-asn__asn">${r.asn}</span> · ${r.org}</div><div>${flag(r.country)} ${r.country==="--"?"Unlocated":countryName(r.country)} · ${r.country}</div><div class="nodes-by-asn__num">${n(r.nodes)}</div><div class="nodes-by-asn__num">${pct(total?r.nodes/total:NaN)}</div>`;body.appendChild(row)})}set(root,"[data-nba-meta]",`${detail.source||snap.source||"ZZXBitnodes"} · DB-IP ASN via Map Host · ${detail.stale?"stale":"live"}`);const st=q(root,"[data-nba-status]");if(st){st.textContent=detail.stale?"cached":"live";st.dataset.status=detail.stale?"warn":"ok"}}
  async function boot(root){if(!root)return;root.__zzxAsnState?.unsubscribe?.();try{await ensure();const state={unsubscribe:null};root.__zzxAsnState=state;q(root,"[data-nba-search]")?.addEventListener("input",()=>render(root,W.ZZXBitnodes.current()));q(root,"[data-nba-refresh]")?.addEventListener("click",()=>W.ZZXBitnodes.load(true).then(d=>render(root,d)));state.unsubscribe=W.ZZXBitnodes.subscribe(d=>{if(root.isConnected)render(root,d)},{immediate:true});if(!W.ZZXBitnodes.current()?.snapshot)render(root,await W.ZZXBitnodes.load(false))}catch(e){set(root,"[data-nba-meta]",String(e?.message||e))}}
  if(W.ZZXAPI?.register)W.ZZXAPI.register(ID,boot);else if(W.ZZXWidgetsCore?.onMount)W.ZZXWidgetsCore.onMount(ID,boot);else if(W.ZZXWidgets?.register)W.ZZXWidgets.register(ID,boot);
})();