(()=>{"use strict";const $=id=>document.getElementById(id),P=PtTPCore;let contract=null,events=[];
async function build(){const now=Date.now(),duration=Math.max(1,+$("duration").value||60),base=Math.max(1,+$("base").value||1),unit=$("unit").value,cap=Math.max(base,+$("cap").value||base),ramp=Math.max(0,+$("ramp").value||0);contract={schema:"zzx.pttp.contract.v1",id:P.uid(),created:new Date(now).toISOString(),service:$("service").value.trim(),resource:$("resource").value.trim(),meter:$("meter").value,pricing:{baseSats:base,unit,capSats:cap,rampSatsPerUnit:ramp},access:{durationSeconds:duration,startsOnPayment:true,expiresAt:null},payment:{asset:"BTC",rail:$("rail").value,invoiceOrPsbt:null,privateKeyHandled:false,walletCredentialsHandled:false},status:"draft"};contract.commitment=await P.sha256(JSON.stringify(contract));events=[{at:new Date().toISOString(),state:"draft"}];render()}
function price(q){if(!contract)return 0;const p=contract.pricing;return Math.min(p.capSats,p.baseSats+p.rampSatsPerUnit*Math.max(0,q-1))}
function render(){$("contract-output").textContent=JSON.stringify(contract,null,2);$("commitment").textContent=contract?.commitment||"—";$("price").textContent=price(Math.max(1,+$("quantity").value||1))+" sats";$("state").textContent=contract?.status||"—";document.querySelectorAll("#states span").forEach(s=>s.classList.toggle("active",s.dataset.s===contract?.status))}
$("build").onclick=build;$("quantity").oninput=render;
function step(next){if(!contract)return;const allowed={draft:"quoted",quoted:"payment-requested","payment-requested":"payment-proof-received","payment-proof-received":"access-granted","access-granted":"expired"};if(allowed[contract.status]!==next){$("event-output").textContent=`Invalid transition: ${contract.status} → ${next}`;return}contract.status=next;if(next==="payment-requested")contract.payment.invoiceOrPsbt="external-payment-request-reference-only";if(next==="access-granted")contract.access.expiresAt=new Date(Date.now()+contract.access.durationSeconds*1000).toISOString();events.push({at:new Date().toISOString(),state:next});render();$("event-output").textContent=JSON.stringify(events,null,2)}
$("quote").onclick=()=>step("quoted");$("request").onclick=()=>step("payment-requested");$("proof").onclick=()=>step("payment-proof-received");$("grant").onclick=()=>step("access-granted");$("expire").onclick=()=>step("expired");
$("export").onclick=()=>{if(!contract)return;P.download(JSON.stringify({contract,events,simulation:true,note:"No private keys, wallet credentials, invoice creation, broadcast, or custody."},null,2),"pttp-contract.json")};build();window.PtTP=Object.freeze({version:"0.3.0-alpha-web",custody:false,livePayments:false});
})();
