(()=>{"use strict";const $=id=>document.getElementById(id);let files=[],records=[],selected=-1;const hex=b=>[...b].map(x=>x.toString(16).padStart(2,"0")).join("");
$("files").onchange=async()=>{for(const f of [...$("files").files]){const hash=hex(new Uint8Array(await crypto.subtle.digest("SHA-256",await f.arrayBuffer()))),rec={id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2),name:f.name,size:f.size,type:f.type||"video/unknown",sha256:hash,duration:null,width:null,height:null,tags:[],notes:"",rating:null,posterDataUrl:null,lastModified:new Date(f.lastModified).toISOString()};files.push(f);records.push(rec)}$("files").value="";render();if(selected<0&&records.length)select(0)};
function render(){const e=$("list");e.replaceChildren();records.forEach((r,i)=>{const b=document.createElement("button");b.className="vt-item"+(i===selected?" active":"");b.innerHTML=`<strong>${r.name}</strong><div>${r.size.toLocaleString()} bytes · ${r.tags.length} tag(s)</div><small>${r.sha256.slice(0,16)}…</small>`;b.onclick=()=>select(i);e.append(b)});$("count").textContent=records.length;$("bytes").textContent=records.reduce((s,r)=>s+r.size,0).toLocaleString();$("tag-count").textContent=new Set(records.flatMap(r=>r.tags)).size;$("hashed").textContent=records.filter(r=>r.sha256).length}
function select(i){selected=i;render();const rec=records[i],f=files[i];$("name").value=rec.name;$("tags").value=rec.tags.join(", ");$("notes").value=rec.notes;$("rating").value=rec.rating??"";$("meta").textContent=JSON.stringify(rec,null,2);const v=$("video");URL.revokeObjectURL(v.dataset.url||"");const u=URL.createObjectURL(f);v.src=u;v.dataset.url=u;v.onloadedmetadata=()=>{rec.duration=v.duration;rec.width=v.videoWidth;rec.height=v.videoHeight;$("meta").textContent=JSON.stringify(rec,null,2)};$("poster").src=rec.posterDataUrl||"";$("poster").hidden=!rec.posterDataUrl}
$("save").onclick=()=>{if(selected<0)return;const r=records[selected];r.tags=$("tags").value.split(",").map(x=>x.trim()).filter(Boolean);r.notes=$("notes").value;r.rating=$("rating").value?Math.max(0,Math.min(5,+$("rating").value)):null;render();$("meta").textContent=JSON.stringify(r,null,2)};
$("capture").onclick=()=>{if(selected<0)return;const v=$("video");if(!v.videoWidth)return;const c=document.createElement("canvas");c.width=v.videoWidth;c.height=v.videoHeight;c.getContext("2d").drawImage(v,0,0);records[selected].posterDataUrl=c.toDataURL("image/jpeg",.88);$("poster").src=records[selected].posterDataUrl;$("poster").hidden=false;$("meta").textContent=JSON.stringify(records[selected],null,2)};
$("search").oninput=()=>{const q=$("search").value.toLowerCase();document.querySelectorAll(".vt-item").forEach((el,i)=>{el.hidden=q&&!JSON.stringify(records[i]).toLowerCase().includes(q)})};
function dl(text,name,type="application/json"){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("json").onclick=()=>dl(JSON.stringify({schema:"zzx.vidtag.catalog.v1",exported:new Date().toISOString(),records:records.map(({posterDataUrl,...r})=>r)},null,2),"vidtag-catalog.json");
$("csv").onclick=()=>{const esc=s=>`"${String(s??"").replace(/"/g,'""')}"`,rows=[["name","size","type","sha256","duration","width","height","tags","rating","notes"],...records.map(r=>[r.name,r.size,r.type,r.sha256,r.duration,r.width,r.height,r.tags.join("|"),r.rating,r.notes])];dl(rows.map(r=>r.map(esc).join(",")).join("\n"),"vidtag-catalog.csv","text/csv")};
$("sidecar").onclick=()=>{if(selected<0)return;const r=records[selected],base=r.name.replace(/\.[^.]+$/,"");dl(JSON.stringify({schema:"zzx.vidtag.sidecar.v1",file:{name:r.name,size:r.size,sha256:r.sha256},technical:{duration:r.duration,width:r.width,height:r.height,type:r.type},tags:r.tags,notes:r.notes,rating:r.rating},null,2),base+".vidtag.json")};
render();window.VidTag=Object.freeze({version:"0.1.0-alpha-web",localOnly:true,sha256:true});
})();
