(() => {
"use strict";
const $=id=>document.getElementById(id),KEY="zzx-blackbook-encrypted-v1";let vault=null,currentPass="";
function empty(label){return{schema:"zzx.blackbook.data.v1",label,profiles:[],medical:{},links:[],cryptoIds:{},updatedAt:new Date().toISOString()};}
async function persist(){if(!vault||!currentPass)return;vault.updatedAt=new Date().toISOString();localStorage.setItem(KEY,JSON.stringify(await BlackBookCrypto.encrypt(vault,currentPass)));}
function requireVault(){if(!vault)throw new Error("Unlock or create the vault first.");}
function dl(t,n){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function status(msg){$("bv-output").textContent=msg;}
function selectors(){for(const id of ["bm-profile","bc-profile","bn-from","bn-to"]){const s=$(id),old=s.value;s.replaceChildren();for(const p of vault?.profiles||[]){const o=document.createElement("option");o.value=p.id;o.textContent=p.name;s.appendChild(o);}if([...s.options].some(o=>o.value===old))s.value=old;}}
function render(){
  const root=$("bp-list");root.replaceChildren();for(const p of vault?.profiles||[]){const e=document.createElement("article");e.className="z-list-item";e.innerHTML="<strong></strong><p></p>";e.querySelector("strong").textContent=`${p.name} · ${p.role||"profile"} · ${p.verified}`;e.querySelector("p").textContent=`${p.contact||"no contact"} · ${(p.tags||[]).join(", ")}`;root.appendChild(e);}if(!vault?.profiles?.length)root.innerHTML='<div class="z-list-item"><p>Vault locked or no profiles.</p></div>';selectors();drawGraph();
}
function profile(){requireVault();const p={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name:$("bp-name").value.trim()||"Unnamed",pronouns:$("bp-pronouns").value.trim(),role:$("bp-role").value.trim(),contact:$("bp-contact").value.trim(),verified:$("bp-verified").value,tags:$("bp-tags").value.split(",").map(x=>x.trim()).filter(Boolean),notes:$("bp-notes").value,consentNotes:$("bp-consent").value,createdAt:new Date().toISOString()};vault.profiles.push(p);persist();render();}
function drawGraph(){const c=$("bn-canvas"),ctx=c.getContext("2d"),r=c.getBoundingClientRect(),w=Math.max(320,Math.round(r.width)),h=Math.max(280,Math.round(r.height||380)),dpr=Math.max(1,Math.min(2,devicePixelRatio||1));c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#050505";ctx.fillRect(0,0,w,h);const ps=vault?.profiles||[],pos={};ps.forEach((p,i)=>{const a=2*Math.PI*i/Math.max(1,ps.length)-Math.PI/2;pos[p.id]={x:w/2+Math.cos(a)*Math.min(w,h)*.33,y:h/2+Math.sin(a)*Math.min(w,h)*.33};});ctx.strokeStyle="#555";for(const l of vault?.links||[]){const a=pos[l.from],b=pos[l.to];if(a&&b){ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y);ctx.stroke();}}for(const p of ps){const q=pos[p.id];ctx.fillStyle="#c0d674";ctx.beginPath();ctx.arc(q.x,q.y,12,0,Math.PI*2);ctx.fill();ctx.fillStyle="#e8e8e8";ctx.font="11px monospace";ctx.fillText(p.name,q.x+16,q.y+4);}}
$("bv-create").addEventListener("click",async()=>{try{currentPass=$("bv-pass").value;if(!currentPass)throw new Error("Password required.");vault=empty($("bv-label").value.trim()||"blackbook");await persist();status("Created encrypted local vault.");render();}catch(e){status(`ERROR: ${e.message}`);}});
$("bv-unlock").addEventListener("click",async()=>{try{const raw=localStorage.getItem(KEY);if(!raw)throw new Error("No local vault exists.");currentPass=$("bv-pass").value;vault=await BlackBookCrypto.decrypt(JSON.parse(raw),currentPass);status(`Unlocked ${vault.label}. ${vault.profiles.length} profile(s).`);render();}catch(e){vault=null;status(`ERROR: ${e.message}`);render();}});
$("bv-lock").addEventListener("click",()=>{vault=null;currentPass="";$("bv-pass").value="";status("Vault locked; decrypted state removed from application memory.");render();});
$("bp-add").addEventListener("click",()=>{try{profile();}catch(e){alert(e.message);}});
$("bm-save").addEventListener("click",async()=>{try{requireVault();const id=$("bm-profile").value;if(!id)throw new Error("Select a profile.");vault.medical[id]={allergies:$("bm-allergies").value,medications:$("bm-meds").value,emergencyContact:$("bm-emergency").value,notes:$("bm-notes").value,updatedAt:new Date().toISOString()};await persist();$("bm-output").textContent=JSON.stringify({profileId:id,saved:true},null,2);}catch(e){$("bm-output").textContent=`ERROR: ${e.message}`;}});
$("bn-add").addEventListener("click",async()=>{try{requireVault();const f=$("bn-from").value,t=$("bn-to").value;if(!f||!t||f===t)throw new Error("Choose two distinct profiles.");vault.links.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),from:f,to:t,label:$("bn-label").value.trim(),createdAt:new Date().toISOString()});await persist();$("bn-output").textContent=JSON.stringify(vault.links,null,2);drawGraph();}catch(e){$("bn-output").textContent=`ERROR: ${e.message}`;}});
$("bc-save").addEventListener("click",async()=>{try{requireVault();const id=$("bc-profile").value;if(!id)throw new Error("Select a profile.");vault.cryptoIds[id]={pgpFingerprint:$("bc-pgp").value.trim(),note:$("bc-note").value.trim()};await persist();$("bc-output").textContent=JSON.stringify(vault.cryptoIds[id],null,2);}catch(e){$("bc-output").textContent=`ERROR: ${e.message}`;}});
$("bx-export").addEventListener("click",()=>{const raw=localStorage.getItem(KEY);if(raw)dl(raw,`blackbook-encrypted-${Date.now()}.json`);else $("bx-output").textContent="No encrypted vault to export.";});
$("bx-import").addEventListener("change",async()=>{const f=$("bx-import").files?.[0];if(!f)return;try{const e=JSON.parse(await f.text());if(e.schema!=="zzx.blackbook.vault.v1")throw new Error("Unsupported vault schema.");localStorage.setItem(KEY,JSON.stringify(e));vault=null;currentPass="";$("bx-output").textContent=`Imported encrypted vault ${f.name}. Unlock it from Vault.`;}catch(e){$("bx-output").textContent=`ERROR: ${e.message}`;}$("bx-import").value="";render();});
render();
window.BlackBook=Object.freeze({version:"0.1.0-alpha-web",isUnlocked:()=>Boolean(vault),getProfileCount:()=>vault?.profiles.length||0});
window.ZZXHooks?.emit("blackbook:ready",{version:"0.1.0-alpha-web"});
})();
