(()=>{"use strict";
const $=id=>document.getElementById(id),P=PRONERCore;let items=[],selected=null;
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
async function add(){const f=$("media").files[0]||null,rec={id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2),created:new Date().toISOString(),title:$("title").value.trim(),kind:$("kind").value,tags:[...new Set($("tags").value.split(",").map(x=>x.trim().toLowerCase()).filter(Boolean))],bookmark:$("bookmark").value.trim(),notes:$("notes").value.trim(),adult:true,lawfulAdultContentAttested:$("adult-attest").checked,rightsStatus:$("rights").value,media:null};if(!rec.title){$("output").textContent="Title is required.";return}if(f)rec.media={name:f.name,type:f.type||"unknown",bytes:f.size,sha256:await P.sha256(f),referenceOnly:true};items.push(rec);render();$("output").textContent=JSON.stringify(rec,null,2);$("media").value=""}
function render(){const q=$("search").value.trim().toLowerCase(),list=items.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q));const e=$("library");e.replaceChildren();list.forEach(x=>{const d=document.createElement("div");d.className="proner-card";d.innerHTML=`<strong>${esc(x.title)}</strong><div class="fx-watermark">${esc(x.kind)} · ${esc(x.rightsStatus)} · ${x.media?esc(x.media.type):"no media"}</div><div>${x.tags.map(t=>`<span class="proner-tag">${esc(t)}</span>`).join("")}</div><p>${esc(x.notes)}</p><button class="btn ghost" data-id="${x.id}">OPEN</button>`;e.append(d)});e.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>{selected=items.find(x=>x.id===b.dataset.id);$("selected").textContent=JSON.stringify(selected,null,2)});$("count").textContent=items.length;$("visible").textContent=list.length;$("tag-count").textContent=new Set(items.flatMap(x=>x.tags)).size;$("hashed").textContent=items.filter(x=>x.media?.sha256).length}
$("add").onclick=add;$("search").oninput=render;
$("export-plain").onclick=()=>P.download(JSON.stringify({schema:"zzx.proner.library.v1",exported:new Date().toISOString(),items},null,2),"proner-library.json");
$("export-encrypted").onclick=async()=>{const pass=$("pass").value;if(pass.length<8){$("crypto-output").textContent="Use a passphrase of at least 8 characters.";return}const pkg=await P.encrypt({schema:"zzx.proner.library.v1",items},pass),t=JSON.stringify(pkg,null,2);P.download(t,"proner-library.encrypted.json");$("crypto-output").textContent=t};
$("import-encrypted").onchange=async()=>{const f=$("import-encrypted").files[0];if(!f)return;try{const pkg=JSON.parse(await f.text()),data=await P.decrypt(pkg,$("pass").value);items=[...(data.items||[]),...items];render();$("crypto-output").textContent=`Imported ${data.items?.length||0} encrypted record(s).`}catch(e){$("crypto-output").textContent="IMPORT ERROR: "+e.message}$("import-encrypted").value=""};
render();window.PRONER=Object.freeze({version:"0.1.0-alpha-web",storesMedia:false});
})();
