(()=>{"use strict";const $=id=>document.getElementById(id),r=new ZZXRecorder(),te=new TextEncoder();let analyser,actx,src,meterRaf=0,elapsedTimer=0,recordStarted=0;
const fmt=ms=>{const s=Math.max(0,Math.floor(ms/1000));return`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`};const b64=b=>{let s="";for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(s)};
async function listDevices(){const ds=await r.devices(),e=$("device");e.replaceChildren();for(const d of ds){const o=document.createElement("option");o.value=d.deviceId;o.textContent=d.label||`Microphone ${e.options.length+1}`;e.append(o)}}
async function permission(){await r.acquire();await listDevices();setupMeter()}
function setupMeter(){if(!r.stream)return;actx??=new AudioContext();if(src)src.disconnect();src=actx.createMediaStreamSource(r.stream);analyser=actx.createAnalyser();analyser.fftSize=1024;src.connect(analyser);drawMeter()}
function drawMeter(){cancelAnimationFrame(meterRaf);const c=$("meter"),x=c.getContext("2d"),buf=new Uint8Array(analyser?.frequencyBinCount||512);const loop=()=>{x.clearRect(0,0,c.width,c.height);if(analyser){analyser.getByteTimeDomainData(buf);x.beginPath();for(let i=0;i<buf.length;i++){const px=i/(buf.length-1)*c.width,py=(buf[i]/255)*c.height;i?x.lineTo(px,py):x.moveTo(px,py)}x.strokeStyle="#c0d674";x.lineWidth=2;x.stroke()}meterRaf=requestAnimationFrame(loop)};loop()}
$("permission").onclick=()=>permission().then(()=>$("status").textContent="MIC READY").catch(e=>$("status").textContent="ERROR: "+e.message);
$("start").onclick=async()=>{try{if(!r.stream)await permission();const s=await r.start($("device").value);recordStarted=Date.now();$("status").textContent="RECORDING";$("codec").textContent=s.mime||"browser default";clearInterval(elapsedTimer);elapsedTimer=setInterval(()=>{$("elapsed").textContent=fmt(Date.now()-recordStarted)},250)}catch(e){$("status").textContent="ERROR: "+e.message}};
$("pause").onclick=()=>{r.pause();$("status").textContent="PAUSED"};$("resume").onclick=()=>{r.resume();$("status").textContent="RECORDING"};
$("stop").onclick=async()=>{try{const s=await r.stop();clearInterval(elapsedTimer);$("elapsed").textContent=fmt(s.durationMs);$("status").textContent="STOPPED";renderSessions()}catch(e){$("status").textContent="ERROR: "+e.message}};
function renderSessions(){const list=$("session-list"),sel=$("encrypt-session");list.replaceChildren();sel.replaceChildren();r.sessions.forEach((s,i)=>{const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${$("project").value || "recording"} #${r.sessions.length-i}</strong><p>${new Date(s.started).toLocaleString()} · ${fmt(s.durationMs)} · ${(s.bytes/1048576).toFixed(2)} MiB · ${s.mime}</p><p>SHA-256 ${s.sha256}</p><button class="btn ghost" data-d="${s.id}">DOWNLOAD</button>`;list.append(a);const o=document.createElement("option");o.value=s.id;o.textContent=`${new Date(s.started).toLocaleString()} · ${(s.bytes/1048576).toFixed(2)} MiB`;sel.append(o)});list.querySelectorAll("[data-d]").forEach(b=>b.onclick=()=>{const s=r.sessions.find(x=>x.id===b.dataset.d);if(!s)return;const u=URL.createObjectURL(s.blob),a=document.createElement("a");a.href=u;a.download=`${$("project").value||"field"}-${s.started.replace(/[:.]/g,"-")}.${s.mime.includes("ogg")?"ogg":s.mime.includes("mp4")?"m4a":"webm"}`;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)})}
async function key(pass,salt,it){const k=await crypto.subtle.importKey("raw",te.encode(pass),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",hash:"SHA-256",salt,iterations:it},k,{name:"AES-GCM",length:256},false,["encrypt"])}
$("export-encrypted").onclick=async()=>{try{const s=r.sessions.find(x=>x.id===$("encrypt-session").value);if(!s)throw new Error("Select a recording.");const pass=$("pass").value;if(pass.length<8)throw new Error("Use at least 8 characters.");const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),it=Math.max(100000,+$("iterations").value||310000),k=await key(pass,salt,it),plain=new Uint8Array(await s.blob.arrayBuffer()),ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},k,plain)),doc={schema:"zzx.fieldrecorder.encrypted.v1",recording:{started:s.started,durationMs:s.durationMs,mime:s.mime,bytes:s.bytes,sha256:s.sha256},kdf:{name:"PBKDF2",hash:"SHA-256",iterations:it,salt:b64(salt)},cipher:{name:"AES-GCM",iv:b64(iv)},ciphertext:b64(ct)},t=JSON.stringify(doc),blob=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="fieldrecorder.enc.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800);$("encrypt-output").textContent=JSON.stringify({...doc,ciphertext:`<${ct.length} encrypted bytes>`},null,2)}catch(e){$("encrypt-output").textContent="ERROR: "+e.message}};
$("build-backup").onclick=()=>{const doc={schema:"zzx.fieldrecorder.backup-plan.v1",created:new Date().toISOString(),destination:$("backup-dest").value.trim(),copies:Math.max(1,+$("backup-copies").value||2),verification:$("backup-verify").value,recordings:r.sessions.map(s=>({started:s.started,durationMs:s.durationMs,mime:s.mime,bytes:s.bytes,sha256:s.sha256})),automaticUpload:false};$("backup-output").textContent=JSON.stringify(doc,null,2)};
window.FieldRecorder=Object.freeze({version:"0.8.0-alpha-web",getSessions:()=>r.sessions.map(({blob,...x})=>({...x}))});window.ZZXHooks?.emit("fieldrecorder:ready",{version:"0.8.0-alpha-web"})})();
