// __partials/widgets/btc-prs/js/sources.js
(function(){
  "use strict";

  const W=window;
  if(Number(W.ZZXBitcoinPRSources?.__version||0)>=2)return;

  W.ZZXBitcoinPRSources=Object.freeze({
    __version:2,

    // Canonical first-party mirrors generated by:
    // .github/workflows/zzx-bitcoin-core-github-activity.yml
    localPrimary:"/bitcoin/github/api/bitcoin-core/pulls.json",
    localFallback:"/bitcoin/github/bitcoin-core/pulls.json",

    github:"https://api.github.com/repos/bitcoin/bitcoin/pulls?state=all&sort=updated&direction=desc&per_page=100",
    repository:"https://github.com/bitcoin/bitcoin",
    pullsPage:"https://github.com/bitcoin/bitcoin/pulls",

    // Anonymous direct GitHub is disabled by default. The public HUD should
    // consume the first-party mirror and not share GitHub's anonymous quota.
    directFallbackFlag:"ZZXGitHubDirectFallback"
  });
})();
