/* Isolated application tests with source JSON, a minimal DOM, and a command-recording canvas.
   This does not launch a browser or claim GPU, layout, or visual validation. No npm dependencies. */
'use strict';
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=process.env.WFB_TEST_ROOT?path.resolve(process.env.WFB_TEST_ROOT):path.resolve(__dirname,'..','worldfactbook');
const frames=[];let tests=0,skips=0;
const hasProfiles=fs.existsSync(path.join(root,'api/verified-html/countries/US/2007.json'));
const leaderRoot=process.env.WFB_LEADERS_TEST_ROOT?path.resolve(process.env.WFB_LEADERS_TEST_ROOT):root;
const leaderFixture=path.join(leaderRoot,'api/leaders/countries/IN/2012/part-0001.json');
const hasLeaders=fs.existsSync(leaderFixture)&&JSON.parse(fs.readFileSync(leaderFixture,'utf8')).terms.some(row=>Number(row.parser_version)>=2);
function matches(node,selector){
  selector=selector.trim().replace(/^:scope > /,'');
  const attr=selector.match(/\[([^=\]]+)(?:=["']?([^\]"']+)["']?)?\]/);
  const tag=selector.match(/^[a-z][a-z0-9]*/i)?.[0];
  if(tag&&node.tagName!==tag.toUpperCase())return false;
  const cls=selector.match(/^\.([A-Za-z0-9-]+)/)?.[1];
  if(cls&&!node.classList.contains(cls))return false;
  if(attr){const val=node.getAttribute(attr[1]);if(val===null||attr[2]!==undefined&&val!==attr[2])return false;}
  return !!(tag||cls||attr);
}
class Element{
 constructor(tag='div'){this.tagName=tag.toUpperCase();this.children=[];this.parentNode=null;this.dataset={};this.attrs={};this.style={setProperty(){}};this.events={};this._text='';this.className='';this.value='';this.hidden=false;this.clientWidth=1000;this.clientHeight=600;this.width=1000;this.height=600;this.offsetWidth=280;this.offsetHeight=180;
 this.classList={contains:c=>this.className.split(/\s+/).includes(c),add:c=>{if(!this.classList.contains(c))this.className+=' '+c;},remove:c=>{this.className=this.className.split(/\s+/).filter(x=>x!==c).join(' ');},toggle:(c,yes)=>{const on=yes===undefined?!this.classList.contains(c):yes;on?this.classList.add(c):this.classList.remove(c);return on;}};
 }
 get textContent(){return this._text+this.children.map(c=>typeof c==='string'?c:c.textContent).join('');}
 set textContent(v){this._text=String(v??'');this.children=[];}
 get childNodes(){return this.children;}get childElementCount(){return this.children.length;}get parentElement(){return this.parentNode;}get options(){return this.children.filter(c=>c.tagName==='OPTION');}
 append(...nodes){for(let n of nodes){if(n==null)continue;if(typeof n==='string'){const text=new Element('span');text.textContent=n;n=text;}if(n.parentNode){n.parentNode.children=n.parentNode.children.filter(c=>c!==n);}n.parentNode=this;this.children.push(n);}}
 appendChild(n){this.append(n);return n;}replaceChildren(...n){this.children.forEach(c=>{c.parentNode=null;});this.children=[];this._text='';this.append(...n);}
 setAttribute(k,v){this.attrs[k]=String(v);if(k.startsWith('data-'))this.dataset[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())]=String(v);}
 getAttribute(k){if(k.startsWith('data-')){const v=this.dataset[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase())];return v===undefined?null:String(v);}return this.attrs[k]??null;}
 removeAttribute(k){delete this.attrs[k];}addEventListener(k,f){(this.events[k]??=[]).push(f);}async fire(k,event={}){for(const f of this.events[k]||[])await f({target:this,button:0,clientX:500,clientY:300,pointerId:1,preventDefault(){},...event});}
 querySelectorAll(selector){return selector.split(',').flatMap(sel=>{const result=[];function visit(n){for(const c of n.children){if(matches(c,sel))result.push(c);visit(c);}}visit(this);return result;});}querySelector(s){return this.querySelectorAll(s)[0]||null;}
 after(node){if(!this.parentNode)return;node.parentNode=this.parentNode;this.parentNode.children.splice(this.parentNode.children.indexOf(this)+1,0,node);}remove(){if(this.parentNode)this.parentNode.children=this.parentNode.children.filter(n=>n!==this);this.parentNode=null;}
 scrollIntoView(){}setPointerCapture(){}releasePointerCapture(){}getBoundingClientRect(){return {left:0,top:0,width:this.clientWidth,height:this.clientHeight};}
 getContext(){if(!this.ctx)this.ctx=canvasContext(this);return this.ctx;}
}
function canvasContext(node){const commands=[];return new Proxy({commands,drawImage(image){this.image=image;},getImageData(){return {data:this.image?.pixels||new Uint8ClampedArray(node.width*node.height*4)};},putImageData(value){this.output=value;},createImageData(w,h){return {width:w,height:h,data:new Uint8ClampedArray(w*h*4)};},createLinearGradient(){return {addColorStop(){}};},createRadialGradient(){return {addColorStop(){}};},fillText(...args){commands.push(['label',...args]);},arc(...args){commands.push(['arc',...args]);},ellipse(...args){commands.push(['ellipse',...args]);},clearRect(){commands.length=0;}},{get(target,key){return key in target?target[key]:()=>{};}});}
const nodes=new Map(),body=new Element('body');
function get(selector){const match=selector.match(/\[(data-[^=\]]+)(?:=["']?([^\]"']+)["']?)?\]/);if(!match)return null;const key=match[1]+(match[2]?'='+match[2]:'');if(nodes.has(key))return nodes.get(key);const tag=/canvas|markers/.test(match[1])?'canvas':/country$|layer$|theme$|rate$/.test(match[1])?'select':'div';const n=new Element(tag);n.setAttribute(match[1],match[2]||'');nodes.set(key,n);body.append(n);return n;}
// Install only actual controls from HTML; this catches selector/markup mismatches.
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
for(const attr of html.matchAll(/(data-wfb-[a-z-]+)(?:="([^"]*)")?/g))get(`[${attr[1]}${attr[2]?'="'+attr[2]+'"':''}]`);
const doc={body,head:new Element('head'),documentElement:new Element('html'),readyState:'complete',hidden:false,currentScript:{src:'https://example.invalid/worldfactbook/worldfactbook.js'},querySelector:s=>{if(/data-wfb-/.test(s)){const m=s.match(/\[(data-[^=\]]+)(?:=["']?([^\]"']+)["']?)?\]/);return m?nodes.get(m[1]+(m[2]?'='+m[2]:''))||null:null;}return body.querySelector(s);},querySelectorAll:s=>s.includes('data-wfb-view')?[get('[data-wfb-view="2d"]'),get('[data-wfb-view="3d"]')]:body.querySelectorAll(s),createElement:t=>new Element(t),createDocumentFragment:()=>new Element('fragment'),addEventListener(){},dispatchEvent(){}};
class ImageMock{constructor(){this.naturalWidth=2;this.naturalHeight=1;}set src(v){this._src=v;queueMicrotask(()=>this.onload?.());}get src(){return this._src;}}
const fetches=[];
async function fakeFetch(url){const u=new URL(url);fetches.push(u.href);let relative=u.pathname.replace(/^\/worldfactbook\//,'');relative=relative.replace(/^worldfactbook-data\/(?:years\/\d{4}|indexes)\/worldfactbook\//,'');const fixtureRoot=relative.startsWith('api/leaders/')?leaderRoot:root;const file=path.join(fixtureRoot,relative);if(!file.startsWith(fixtureRoot+path.sep))throw Error('Unsafe fixture');if(!fs.existsSync(file))return {ok:false,status:404};return {ok:true,status:200,json:async()=>JSON.parse(fs.readFileSync(file,'utf8'))};}
const context={window:null,document:doc,location:new URL('https://example.invalid/worldfactbook/'),URL,Map,Set,Date,Intl,Math,Number,String,Boolean,Array,Object,JSON,Error,Promise,Uint8ClampedArray,Float32Array,AbortController,Image:ImageMock,console:{warn(){},info(){},error(...v){throw Error(v.join(' '));}},setTimeout,clearTimeout,requestAnimationFrame:f=>{frames.push(f);return frames.length;},ResizeObserver:class{observe(){}},MutationObserver:class{observe(){}},fetch:fakeFetch,devicePixelRatio:1,matchMedia:()=>({matches:false}),addEventListener(){}};
context.window=context;context.WFB={state:{archive:null},$:s=>doc.querySelector(s),dispatch(){}};context.WFBGlobeRenderer={create:async()=>({kind:'fixture renderer',setTexture(){},setRelief(){},draw(){},destroy(){}})};
vm.createContext(context);
function load(name,transform=s=>s){vm.runInContext(transform(fs.readFileSync(path.join(root,name),'utf8')),context,{filename:name});}
async function settle(){for(let i=0;i<12;i++)await new Promise(resolve=>setImmediate(resolve));}
function fixtureTest(available,name,fn){if(available)return test(name,fn);skips++;process.stdout.write('SKIP '+name+' (source fixtures moved to private archives)\n');return Promise.resolve();}
function test(name,fn){return Promise.resolve().then(fn).then(()=>{tests++;process.stdout.write('PASS '+name+'\n');});}
(async()=>{
 load('worldfactbook.js');load('js/globe-config.js');load('js/country-feed.js');load('js/water-boundaries.js');
 load('js/globe.js',s=>s.replace('  W.globe=Object.freeze', '  W.__test={state,project,geoAt,selectAt,frame,setZoom,setAxis,setBodySpeed,setOrbitControl,draw,loadProfile};\n  W.globe=Object.freeze'));
 await context.WFB.globe.init();await settle();const g=context.WFB.__test;
 await fixtureTest(hasProfiles,'full initialization and real edition fields',()=>{assert.equal(g.state.year,2007);assert.equal(g.state.country,'IN');assert(doc.querySelector('[data-wfb-country-profile]').textContent.includes('India'));assert(doc.querySelector('[data-wfb-country-profile]').querySelectorAll('.wfb-country-field').length>100);assert.equal(g.state.waterGeometry.features.length,11656);});
 await test('Sun and Moon visibility switches are independent',async()=>{const sun=get('[data-wfb-toggle="sun"]'),moon=get('[data-wfb-toggle="moon"]');await sun.fire('click');assert.equal(g.state.showSun,false);assert.equal(g.state.showMoon,true);assert.equal(sun.getAttribute('aria-checked'),'false');assert.equal(sun.textContent,'Sun hidden');await moon.fire('click');assert.equal(g.state.showMoon,false);await sun.fire('click');await moon.fire('click');});
 await test('orbits share pause, reverse and continuous speed controls',async()=>{g.state.axis=0;g.state.playing=true;g.state.lastFrame=1000;g.frame(1200);const a=g.state.sunElapsedMs,b=g.state.moonElapsedMs;assert(a>0&&b>0);g.setBodySpeed('moon',4);assert.equal(g.state.moonElapsedMs,b);g.state.lastFrame=1200;g.frame(1400);assert.equal(g.state.moonElapsedMs-b,4*(g.state.sunElapsedMs-a));g.state.playing=false;g.frame(1600);assert.equal(g.state.sunElapsedMs,2*a);g.state.playing=true;g.state.direction=-1;g.frame(1800);assert.equal(g.state.sunElapsedMs,a);g.state.playing=false;g.state.direction=1;g.setZoom(6);g.draw();const labels=get('[data-wfb-globe-markers]').ctx.commands.filter(x=>x[0]==='label'&&['Sun','Moon'].includes(x[1]));assert.equal(labels.length,2);for(const [,label,x,y] of labels){assert(x>=0&&x<=1000,label);assert(y>=0&&y<=600,label);}});
 await test('3D and 2D geography round trips, including tilted latitude and date line',()=>{for(const flat of [false,true])for(const lon of [10,179,-179]){g.state.flat=flat;g.state.yaw=lon*Math.PI/180;g.state.pitchOffset=.7;g.state.flatLat=.7;g.state.axis=0;const point={lon,lat:40};const screen=g.project(point,1000,600),geo=g.geoAt(screen.x,screen.y,1000,600);assert(Math.abs(geo.lon-lon)<1e-8);assert(Math.abs(geo.lat-40)<1e-8);}});
 await test('Thames exact river selection preserves zoom and click coordinates',async()=>{g.state.flat=true;g.state.flatLat=51.5*Math.PI/180;g.state.yaw=-.1*Math.PI/180;g.setZoom(6);const p=g.project({lon:-.1,lat:51.5},1000,600);assert(p.x>=0&&p.x<=1000&&p.y>=0&&p.y<=600);await g.selectAt(p.x,p.y,1000,600);await settle();const feature=g.state.waterFeatures.get(g.state.country);assert.equal(feature.name,'Thames');assert.equal(feature.kind,'river');assert.equal(g.state.zoom,6);assert(doc.querySelector('[data-wfb-country-profile]').textContent.includes('51.50000'));});
 await test('Lake Erie uses source polygon and low zoom excludes river picking',async()=>{g.state.flatLat=42.1*Math.PI/180;g.state.yaw=-81.2*Math.PI/180;const p=g.project({lon:-81.2,lat:42.1},1000,600);await g.selectAt(p.x,p.y,1000,600);await settle();assert.match(g.state.waterFeatures.get(g.state.country).name,/Erie$/);const river=await g.state.waterGeometry.hit(-.1,51.5,500,300,p=>g.project(p,1000,600),1000,600,1,true);assert.equal(river,null);});
 await test('water dropdown revisits preserve the detailed source outline',async()=>{const waterCode=g.state.country;context.WFB.globe.choose('US');await settle();context.WFB.globe.choose(waterCode);await settle();assert.equal(g.state.country,waterCode);assert(g.state.selectedRings.length>0);assert(get('[data-wfb-country-profile]').textContent.includes('Erie'));});
 await test('Atlantic and Pacific source subdivisions use five ocean identities',()=>{const oceans=g.state.waterGeometry.features.filter(f=>f.kind==='ocean');assert.equal(new Set(oceans.map(f=>f.code)).size,5);assert(oceans.filter(f=>/Atlantic/.test(f.name)).every(f=>f.code==='X-ATLANTIC-OCEAN'));});
 await test('hover and 2D latitude dragging are wired and release state',async()=>{const canvas=get('[data-wfb-globe-canvas]');await canvas.fire('pointermove');g.state.flat=true;g.state.flatLat=0;g.state.zoom=4;await canvas.fire('pointerdown',{clientX:500,clientY:300});await canvas.fire('pointermove',{clientX:500,clientY:400});assert(g.state.flatLat>0);await canvas.fire('pointerup',{clientX:500,clientY:400});assert.equal(g.state.dragging,false);});
 await fixtureTest(hasProfiles,'rapid edition changes keep the newest country profile and callout',async()=>{context.WFB.globe.choose('US');context.WFB.globe.setYear(2005);context.WFB.globe.setYear(2007);await settle();const panel=get('[data-wfb-country-profile]');assert(panel.textContent.includes('301,139,947'));assert(!panel.textContent.includes('295,734,134'));assert(get('[data-wfb-globe-callout]').textContent.includes('301,139,947'));});
 load('js/reading-room.js');
 await fixtureTest(hasProfiles,'reading-room initialization builds navigation without replacing chapter IDs',()=>{const chapters=get('[data-wfb-country-profile]').querySelectorAll('.wfb-feed-chapter');assert(chapters.length>8);const ids=chapters.map(c=>c.id);context.WFB.readingRoom.init();const nav=get('[data-wfb-reading-nav]');assert(nav.querySelectorAll('button').length>8);assert.deepEqual(chapters.map(c=>c.id),ids);for(const c of chapters){assert(c.dataset.category);assert(c.querySelector('h4'));assert(c.id.startsWith('wfb-chapter-'));}});
 await test('private year routes cover country, leaders, media, monthly facts and historical maps',async()=>{const client=context.ZZXWorldFactbook;for(const resource of ['api/verified-html/countries/US/2007.json','api/leaders/years/2012/index.json','media/verified-html/2007/US-flag.png','api/daily-archive/months/2025-12.json','boundaries/editions/2007/index.json']){assert((await client.resourceURL(resource)).includes('/worldfactbook-data/years/'+client.resourceYear(resource)+'/'));}assert.throws(()=>client.resourceYear('../token'),/Invalid/);assert(!fs.readFileSync(path.join(root,'archive-config.json'),'utf8').includes('TOKEN'));});
 await test('loader initializes the country feed before globe with a captured script root',()=>{const loader=fs.readFileSync(path.join(root,'script.js'),'utf8');assert(loader.indexOf('"js/country-feed.js"')<loader.indexOf('"js/globe.js"'));assert(loader.includes('new URL(path, moduleRoot)'));assert.equal(loader.match(/"js\/water-boundaries.js"/g).length,1);const preview=fs.readFileSync(path.join(root,'globe-preview/index.html'),'utf8');assert(preview.includes('../worldfactbook.js'));assert(preview.includes('../js/country-feed.js'));});
 load('js/daily-archive.js');context.WFB.api={probe:p=>context.ZZXWorldFactbook.optionalJSON(p)};
 await test('daily archive fills Fact and Place and resolves singular Flag markup',async()=>{await context.WFB.dailyArchive.init();assert(!get('[data-wfb-fact-readout]').textContent.includes('Awaiting'));assert(!get('[data-wfb-place-readout]').textContent.includes('Awaiting'));assert.equal(get('[data-wfb-flag-status]').textContent,'Dated index open');assert.equal(get('[data-wfb-daily-date]').min,'1962-01-01');});
 await fixtureTest(hasLeaders,'monthly PDF leader observations render with filename, page and checksum',async()=>{const probe=context.WFB.api.probe;context.WFB.api={probe:p=>p==='verified-html/index.json'?Promise.resolve({countries:{IN:[]}}):probe(p)};await context.WFB.dailyArchive.setDate('2012-01-20');const panel=get('[data-wfb-leaders-readout]');assert(panel.textContent.includes('January2012ChiefsDirectory.pdf'));assert(panel.textContent.includes('SHA-256'));assert(panel.textContent.includes('term dates not inferred'));assert(!panel.textContent.includes('No source-cited officeholder'));context.WFB.api={probe};});
 await test('CPU projection draws latitude changes immediately while paused',()=>{load('js/globe-renderer.js');const canvas=new Element('canvas');body.append(canvas);const renderer=context.WFBGlobeRenderer.createCPU(canvas);const pixels=new Uint8ClampedArray(4*8*4);for(let y=0;y<8;y++)for(let x=0;x<4;x++){const i=(y*4+x)*4;pixels[i]=24*y;pixels[i+3]=255;}renderer.setTexture({width:4,height:8,pixels});const settings={flat:true,flatLat:0,yaw:0,pitch:0,zoom:2,realism:0,tactical:false};renderer.draw(9,9,settings);const overlay=canvas.parentNode.children[canvas.parentNode.children.indexOf(canvas)+1];const equator=overlay.ctx.image.ctx.output.data[(4*9+4)*4];renderer.draw(9,9,{...settings,flatLat:.7});const north=overlay.ctx.image.ctx.output.data[(4*9+4)*4];assert(north<equator);renderer.destroy();});
 await test('an archive initialization failure does not stop globe or daily initialization',async()=>{const calls=[],errors=[];const isolated={window:null,document:{hidden:false},console:{error:(...args)=>errors.push(args)},setInterval(){},Promise};isolated.window=isolated;isolated.WFB={state:{archive:null},archive:{init:async()=>{throw Error('fixture failure');}},globe:{init:async()=>calls.push('globe')},dailyArchive:{init:async()=>calls.push('daily')},dispatch:()=>calls.push('ready')};vm.createContext(isolated);vm.runInContext(fs.readFileSync(path.join(root,'js/core.js'),'utf8'),isolated);await isolated.WFBCore.init();assert.deepEqual(calls,['globe','daily','ready']);assert.equal(errors.length,1);});
 await test('legacy monthly assignments cannot appear as verified leaders',async()=>{const probe=context.WFB.api.probe;const old={country:'JO',month:'2012-01',person:'Unreviewed assignment',office:'Prime Min.',source_name:'January2012ChiefsDirectory.pdf',source_sha256:'a'.repeat(64)};context.WFB.api={probe:p=>p==='leaders/index.json'?Promise.resolve({records:[old]}):p==='verified-html/index.json'?Promise.resolve({countries:{}}):probe(p)};await context.WFB.dailyArchive.init();await context.WFB.dailyArchive.setDate('2012-01-20');assert(!get('[data-wfb-leaders-readout]').textContent.includes('Unreviewed assignment'));const panel=new Element('article');context.WFB.CountryFeed.leaders(panel,[{...old,position:old.office}],2012);assert(panel.textContent.includes('await verification'));assert(!panel.textContent.includes('Unreviewed assignment'));context.WFB.api={probe};});
 // Inject an explicitly cited, reviewed historical flag to test actual rendering through the lazy year route.
 const probe=context.WFB.api.probe;context.WFB.api={probe:async p=>p==='flags/index.json'?{years:{'2007':{path:'flags/years/2007/index.json'}}}:p==='flags/years/2007/index.json'?{parts:['flags/years/2007/part-0001.json']}:p==='flags/years/2007/part-0001.json'?{records:[{country:'United States',edition_year:2007,source_url:'https://www.cia.gov/the-world-factbook/',asset:{path:'media/verified-html/2007/US-flag.png',rights:'public domain'}}]}:probe(p)};
 await test('year-sharded daily flag renders a reviewed edition image',async()=>{await context.WFB.dailyArchive.init();await context.WFB.dailyArchive.setDate('2007-07-01');await settle();assert(get('[data-wfb-flag-readout]').textContent.includes('United States'));assert(get('[data-wfb-flag-readout]').querySelector('img').src.includes('/years/2007/'));assert(get('[data-wfb-flag-readout]').textContent.includes('edition 2007'));});
 process.stdout.write(`${tests} isolated runtime tests passed; ${skips} source fixture tests skipped. Browser/GPU/layout validation was not performed.\n`);
})().catch(error=>{process.stderr.write(error.stack+'\n');process.exitCode=1;});
