(()=>{"use strict";const $=id=>document.getElementById(id);let ctx,stream,src,an,raf,delay,gain,wave,filter;
async function start(){stop();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});ctx=new (window.AudioContext||window.webkitAudioContext)();src=ctx.createMediaStreamSource(stream);filter=ctx.createBiquadFilter();filter.type="bandpass";filter.frequency.value=+($("formant").value);filter.Q.value=.7;delay=ctx.createDelay(1);delay.delayTime.value=+($("delay").value)/1000;gain=ctx.createGain();gain.gain.value=+($("gain").value);wave=ctx.createWaveShaper();updateCurve();an=ctx.createAnalyser();an.fftSize=1024;src.connect(filter).connect(wave).connect(delay).connect(gain).connect(an);an.connect(ctx.destination);$("state").textContent="RUNNING";meter()}
function updateCurve(){if(!wave)return;const amount=+($("drive").value),n=44100,c=new Float32Array(n);for(let i=0;i<n;i++){const x=i*2/n-1;c[i]=Math.tanh(x*(1+amount*20))}wave.curve=c}
function meter(){if(!an)return;const b=new Uint8Array(an.fftSize);an.getByteTimeDomainData(b);let p=0;for(const v of b)p=Math.max(p,Math.abs((v-128)/128));$("meter").style.width=(p*100)+"%";raf=requestAnimationFrame(meter)}
function stop(){cancelAnimationFrame(raf);stream?.getTracks().forEach(t=>t.stop());try{ctx?.close()}catch{}ctx=stream=src=an=null;$("state").textContent="STOPPED"}
$("start").onclick=()=>start().catch(e=>$("state").textContent="ERROR: "+e.message);$("stop").onclick=stop;
$("formant").oninput=()=>{if(filter)filter.frequency.value=+$("formant").value};$("delay").oninput=()=>{if(delay)delay.delayTime.value=+$("delay").value/1000};$("gain").oninput=()=>{if(gain)gain.gain.value=+$("gain").value};$("drive").oninput=updateCurve;
$("profile").onclick=()=>{$("profile-out").textContent=JSON.stringify({schema:"zzx.vcs.profile.v1",name:$("profile-name").value||"custom",effects:[{type:"bandpass",frequency:+$("formant").value},{type:"distortion",drive:+$("drive").value},{type:"delay",ms:+$("delay").value},{type:"gain",value:+$("gain").value}],pitchSemitones:+$("pitch").value,chorusDepth:+$("chorus").value,bitcrushBits:+$("bits").value,specificPersonClone:false},null,2)};
$("midi").onclick=()=>{$("midi-out").textContent=JSON.stringify({schema:"zzx.vcs.midi-map.v1",mappings:[{cc:1,param:"formant"},{cc:2,param:"delay"},{cc:3,param:"drive"},{cc:4,param:"gain"}],browserWebMIDIAvailable:!!navigator.requestMIDIAccess},null,2)};
window.ZZXVCS=Object.freeze({version:"0.1.0-alpha-web",specificPersonClone:false,webAudio:true});
})();
