(()=>{"use strict";const $=id=>document.getElementById(id),state={ctx:null,source:null,stream:null,nodes:null,raf:null,url:null,midi:null};
function values(){return{drive:+$("drive").value,ring:+$("ring").value,filter:+$("filter").value,delay:+$("delay").value,wet:+$("wet").value,glitch:+$("glitch").value}}
async function ensure(){if(!state.ctx)state.ctx=new (window.AudioContext||window.webkitAudioContext)();if(state.ctx.state==="suspended")await state.ctx.resume();return state.ctx}
function teardown(){if(state.raf)cancelAnimationFrame(state.raf);state.raf=null;try{state.source?.disconnect()}catch{};state.stream?.getTracks().forEach(t=>t.stop());state.stream=null;state.source=null;state.nodes=null;$("audio-state").textContent="AUDIO: IDLE";$("audio-state").className="runtime-badge partial"}
function build(source){const ctx=state.ctx,inGain=ctx.createGain(),shaper=ctx.createWaveShaper(),filter=ctx.createBiquadFilter(),delay=ctx.createDelay(.25),wet=ctx.createGain(),dry=ctx.createGain(),mix=ctx.createGain(),ringGain=ctx.createGain(),osc=ctx.createOscillator(),an=ctx.createAnalyser();filter.type="bandpass";filter.Q.value=1.2;osc.type="square";osc.connect(ringGain.gain);osc.start();source.connect(inGain);inGain.connect(shaper);shaper.connect(filter);filter.connect(delay);delay.connect(ringGain);ringGain.connect(wet);source.connect(dry);wet.connect(mix);dry.connect(mix);mix.connect(an);an.connect(ctx.destination);state.nodes={inGain,shaper,filter,delay,wet,dry,mix,ringGain,osc,an};update();visualize()}
function update(){if(!state.nodes)return;const v=values(),n=state.nodes;n.shaper.curve=ChappieCore.curve(v.drive);n.filter.frequency.setTargetAtTime(v.filter,state.ctx.currentTime,.015);n.delay.delayTime.setTargetAtTime(v.delay/1000,state.ctx.currentTime,.015);n.osc.frequency.setTargetAtTime(v.ring,state.ctx.currentTime,.015);n.wet.gain.setTargetAtTime(v.wet/100,state.ctx.currentTime,.015);n.dry.gain.setTargetAtTime(1-v.wet/100,state.ctx.currentTime,.015);n.ringGain.gain.value=.65;$("live-output").textContent=JSON.stringify({...v,note:"Web Audio DSP; native neural pitch/formant stack not emulated."},null,2)}
function visualize(){const c=$("spectrum"),ctx=c.getContext("2d"),an=state.nodes?.an;if(!an)return;an.fftSize=2048;const a=new Uint8Array(an.frequencyBinCount);function frame(){state.raf=requestAnimationFrame(frame);an.getByteFrequencyData(a);const r=c.getBoundingClientRect(),w=Math.max(320,Math.round(r.width)),h=Math.max(250,Math.round(r.height||360)),dpr=Math.max(1,Math.min(2,devicePixelRatio||1));if(c.width!==w*dpr||c.height!==h*dpr){c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0)}ctx.fillStyle="#050505";ctx.fillRect(0,0,w,h);ctx.fillStyle="#c0d674";const bars=96,bw=w/bars;for(let i=0;i<bars;i++){const idx=Math.floor(i*a.length/bars),bh=(a[idx]/255)*(h-20);ctx.fillRect(i*bw,h-bh,bw-1,bh)}}frame()}
$("mic").onclick=async()=>{try{teardown();await ensure();state.stream=await navigator.mediaDevices.getUserMedia({audio:true});state.source=state.ctx.createMediaStreamSource(state.stream);build(state.source);$("audio-state").textContent="AUDIO: MIC";$("audio-state").className="runtime-badge ok"}catch(e){$("live-output").textContent=`ERROR: ${e.message}`}};
$("stop").onclick=teardown;$("file").onchange=async()=>{const f=$("file").files?.[0];if(!f)return;teardown();await ensure();if(state.url)URL.revokeObjectURL(state.url);state.url=URL.createObjectURL(f);$("player").src=state.url;state.source=state.ctx.createMediaElementSource($("player"));build(state.source);$("player").play();$("audio-state").textContent="AUDIO: FILE";$("audio-state").className="runtime-badge ok"};
for(const id of ["drive","ring","filter","delay","wet","glitch"])$(id).oninput=update;
document.querySelectorAll(".preset").forEach(b=>b.onclick=()=>{const p=ChappieCore.PRESETS[b.dataset.preset];for(const [k,v] of Object.entries(p))$(k).value=v;update();$("preset-output").textContent=JSON.stringify({preset:b.dataset.preset,...p},null,2)});
$("midi").onclick=async()=>{try{if(!navigator.requestMIDIAccess)throw new Error("Web MIDI unavailable.");state.midi=await navigator.requestMIDIAccess();for(const input of state.midi.inputs.values())input.onmidimessage=e=>{const [status,cc,val]=e.data;if((status&0xf0)!==0xb0)return;const x=val/127;if(cc===1)$("filter").value=Math.round(300+x*7700);if(cc===2)$("ring").value=Math.round(10+x*240);if(cc===3)$("delay").value=Math.round(x*180);if(cc===4)$("wet").value=Math.round(x*100);update()};$("midi-output").textContent=`Enabled ${state.midi.inputs.size} MIDI input(s). CC1=filter, CC2=ring, CC3=delay, CC4=wet.`}catch(e){$("midi-output").textContent=`ERROR: ${e.message}`}};
$("export-preset").onclick=()=>{const x={schema:"zzx.chappievc.preset.v1",status:"INTERNAL – Not for public distribution.",...values()},t=JSON.stringify(x,null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`chappievc-preset-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$("export-output").textContent=t};
window.ChappieVC=Object.freeze({version:"0.1.0-alpha-web",status:"INTERNAL – Not for public distribution.",presets:ChappieCore.PRESETS,getSettings:values});window.ZZXHooks?.emit("chappievc:ready",{version:"0.1.0-alpha-web",internal:true})})();
