(() => {
"use strict";const $=id=>document.getElementById(id),state={venues:[],lastRoute:null,plans:[]};
function download(t,n,type){const b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function upsert(){const v={name:$("bv-name").value.trim(),bid:+$("bv-bid").value,ask:+$("bv-ask").value,depthBtc:Math.max(0,+$("bv-depth").value||0),feeBps:Math.max(0,+$("bv-fee").value||0),latencyMs:Math.max(0,+$("bv-latency").value||0)};const i=state.venues.findIndex(x=>x.name===v.name);i>=0?state.venues[i]=v:state.venues.push(v);render();}
function samples(){state.venues=[{name:"venue-a",bid:99950,ask:100050,depthBtc:2,feeBps:10,latencyMs:80},{name:"venue-b",bid:99980,ask:100020,depthBtc:.6,feeBps:18,latencyMs:45},{name:"venue-c",bid:99920,ask:100000,depthBtc:4,feeBps:7,latencyMs:130}];render();}
function render(){const body=$("bv-body");body.replaceChildren();for(const v of state.venues){const tr=document.createElement("tr");[v.name,v.bid.toFixed(2),v.ask.toFixed(2),v.depthBtc,v.feeBps,v.latencyMs+" ms"].forEach(x=>{const td=document.createElement("td");td.textContent=x;tr.appendChild(td);});body.appendChild(tr);}if(!state.venues.length)body.innerHTML='<tr><td colspan="6">No venues.</td></tr>';}
function route(){state.lastRoute=BitBrokerCore.route(state.venues,$("br-side").value,Math.max(.0001,+$("br-qty").value||.25),Math.max(0,+$("br-slip").value||0));$("br-output").textContent=JSON.stringify(state.lastRoute,null,2);return state.lastRoute;}
function accumulate(){if(!state.venues.length)throw new Error("Load venue quotes.");const budget=Math.max(1,+$("ba-budget").value||1),slices=Math.max(1,Math.floor(+$("ba-slices").value||1)),cadence=Math.max(1,+$("ba-cadence").value||1),best=Math.min(...state.venues.map(v=>BitBrokerCore.effective(v,"buy",+$("br-slip").value||5,Math.min(v.depthBtc,1)))),usd=budget/slices,plan={type:"TWAP",budgetUsd:budget,slices,cadenceMinutes:cadence,usdPerSlice:usd,estimatedBtcPerSlice:usd/best,estimatedTotalBtc:budget/best,referenceEffectivePrice:best};state.plans.push(plan);$("ba-output").textContent=JSON.stringify(plan,null,2);}
function rebalance(){if(!state.venues.length)throw new Error("Load venue quotes.");const mid=state.venues.reduce((s,v)=>s+(v.bid+v.ask)/2,0)/state.venues.length,r=BitBrokerCore.rebalance(+$("bb-btc").value||0,+$("bb-usd").value||0,mid,+$("bb-target").value||0);$("bb-output").textContent=JSON.stringify({...r,referencePrice:mid},null,2);}
function micro(){if(!state.venues.length)throw new Error("No venues.");const rows=state.venues.map(v=>({venue:v.name,spreadUsd:v.ask-v.bid,spreadBps:((v.ask-v.bid)/((v.ask+v.bid)/2))*10000,mid:(v.ask+v.bid)/2,depthBtc:v.depthBtc,feeBps:v.feeBps,latencyMs:v.latencyMs}));$("bm-output").textContent=JSON.stringify(rows,null,2);draw(rows);}
function draw(rows){const c=$("bm-canvas"),ctx=c.getContext("2d"),dpr=Math.max(1,Math.min(2,devicePixelRatio||1)),r=c.getBoundingClientRect(),w=Math.max(320,Math.round(r.width)),h=Math.max(260,Math.round(r.height||320));c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#050505";ctx.fillRect(0,0,w,h);const max=Math.max(...rows.map(x=>x.spreadBps),1),pad=40,bw=(w-pad*2)/rows.length*.55;rows.forEach((x,i)=>{const bh=x.spreadBps/max*(h-80),px=pad+(w-pad*2)*(i+.5)/rows.length;ctx.fillStyle="#c0d674";ctx.fillRect(px-bw/2,h-35-bh,bw,bh);ctx.fillStyle="#969696";ctx.font="10px monospace";ctx.fillText(x.venue,px-bw/2,h-12);});}
$("bv-add").addEventListener("click",upsert);$("bv-sample").addEventListener("click",samples);$("br-run").addEventListener("click",()=>{try{route();}catch(e){$("br-output").textContent=`ERROR: ${e.message}`;}});$("ba-plan").addEventListener("click",()=>{try{accumulate();}catch(e){$("ba-output").textContent=`ERROR: ${e.message}`;}});$("bb-run").addEventListener("click",()=>{try{rebalance();}catch(e){$("bb-output").textContent=`ERROR: ${e.message}`;}});$("bm-run").addEventListener("click",()=>{try{micro();}catch(e){$("bm-output").textContent=`ERROR: ${e.message}`;}});$("bx-json").addEventListener("click",()=>download(JSON.stringify({schema:"zzx.bitbroker.research.v1",venues:state.venues,lastRoute:state.lastRoute,plans:state.plans},null,2),`bitbroker-${Date.now()}.json`,"application/json"));$("bx-csv").addEventListener("click",()=>download("venue,bid,ask,depth_btc,fee_bps,latency_ms\n"+state.venues.map(v=>`${v.name},${v.bid},${v.ask},${v.depthBtc},${v.feeBps},${v.latencyMs}`).join("\n")+"\n",`bitbroker-venues-${Date.now()}.csv`,"text/csv"));samples();
window.BitBroker=Object.freeze({version:"0.2.0-beta-web",route:BitBrokerCore.route,rebalance:BitBrokerCore.rebalance,setVenues(v){state.venues=JSON.parse(JSON.stringify(v));render();},getState:()=>({venues:state.venues,lastRoute:state.lastRoute,plans:state.plans})});
window.ZZXHooks?.emit("bitbroker:ready",{version:"0.2.0-beta-web"});
})();
