(function(){
  "use strict";
  const W=window,D=document;
  if(W.ZZXBitcoinTickerWidgetModules?.__version>=5)return;
  const STORAGE="zzx.widget.bitcoin-ticker.widget-visibility.v4";
  const PRESETS="zzx.widget.bitcoin-ticker.presets.v1";
  const LAYOUT="zzx.widget.bitcoin-ticker.layout.v1";
  const jsonGet=(k,f)=>{try{const v=JSON.parse(localStorage.getItem(k)||"");return v&&typeof v==="object"?v:f}catch(_){return f}};
  const jsonSet=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
  const esc=id=>{try{return CSS.escape(id)}catch(_){return String(id).replace(/["\\]/g,"\\$&")}};
  const slotFor=id=>D.querySelector(`.btc-slot[data-widget="${esc(id)}"]`)||D.querySelector(`[data-widget-slot="${esc(id)}"]`);
  const loadState=()=>jsonGet(STORAGE,{}),saveState=v=>jsonSet(STORAGE,v);
  function setSlotVisibility(slot,visible){if(!slot)return;slot.hidden=!visible;slot.setAttribute("data-ticker-visible",visible?"true":"false");try{W.dispatchEvent(new CustomEvent("zzx:widget-visibility",{detail:{id:slot.dataset.widget,visible:!!visible}}))}catch(_){}}
  function requestedVisible(id){const s=loadState();if(Object.prototype.hasOwnProperty.call(s,id))return !!s[id];const slot=slotFor(id);return slot?!slot.hidden:false}
  function setVisible(id,visible,{persist=true,mount=true}={}){const slot=slotFor(id);if(persist){const s=loadState();s[id]=!!visible;saveState(s)}if(slot){setSlotVisibility(slot,visible);if(visible&&mount)requestMount(id,slot)}return !!slot}
  function requestMount(id,slot){const core=W.ZZXWidgetsCore;if(!slot||typeof core?.mountWidget!=="function"||slot.children.length||String(slot.textContent||"").trim())return;slot.dataset.status="loading";Promise.resolve(core.mountWidget(id)).then(()=>{if(slot.dataset.status==="loading")delete slot.dataset.status}).catch(e=>{slot.dataset.status="error";slot.dataset.widgetError=String(e?.message||e)})}
  function runtimeState(id){const slot=slotFor(id);if(!slot)return {state:"error",label:"slot missing"};if(!requestedVisible(id)||slot.hidden)return {state:"off",label:"off"};const r=String(slot.dataset.status||slot.querySelector("[data-status]")?.dataset.status||"").toLowerCase();if(/load|pending|refresh|connect|sync|start|initializ/.test(r))return {state:"loading",label:r||"loading"};if(/error|offline|fail|stale|unavailable|warn/.test(r))return {state:"error",label:r||"error"};return {state:(slot.children.length||slot.textContent.trim())?"on":"loading",label:r||"live"}}
  async function loadRegistry(){const p="/__partials/widgets/bitcoin-ticker/widget-integrations.json",u=W.ZZXAPI?.url?W.ZZXAPI.url(p):p;if(W.ZZXAPI?.jsonStrict)return await W.ZZXAPI.jsonStrict(u,{cacheBust:true,timeoutMs:7000,retries:1});const r=await fetch(u,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);return r.json()}
  function applyStoredVisibility(reg){const s=loadState();for(const item of reg.widgets||[]){if(item.available===false){setSlotVisibility(slotFor(item.id),false);continue}const v=Object.prototype.hasOwnProperty.call(s,item.id)?!!s[item.id]:item.default!==false;setSlotVisibility(slotFor(item.id),v);if(v)requestMount(item.id,slotFor(item.id))}}
  function captureLayout(){return [...D.querySelectorAll("[data-hud-root] > .btc-slot[data-widget]")].map(x=>x.dataset.widget)}
  function applyLayout(order){const root=D.querySelector("[data-hud-root]");if(!root||!Array.isArray(order))return;const bar=root.querySelector(":scope > [data-hud-bar]");let anchor=bar?.nextSibling||root.firstChild;for(const id of order){const slot=slotFor(id);if(slot?.parentElement===root){root.insertBefore(slot,anchor);anchor=slot.nextSibling}}jsonSet(LAYOUT,captureLayout())}
  function savePreset(name,registry){name=String(name||"").trim();if(!name)return false;const p=jsonGet(PRESETS,{});p[name]={version:1,savedAt:new Date().toISOString(),visibility:loadState(),layout:captureLayout(),hudMode:W.ZZXHUD?.read?.().mode||"full"};jsonSet(PRESETS,p);renderPresetOptions(D.querySelector("[data-widget-preset-select]"));return true}
  function loadPreset(name,registry){const p=jsonGet(PRESETS,{})[name];if(!p)return false;saveState(p.visibility||{});applyLayout(p.layout||[]);applyStoredVisibility(registry);W.ZZXHUD?.write?.(p.hudMode||"full");return true}
  function deletePreset(name){const p=jsonGet(PRESETS,{});if(!p[name])return false;delete p[name];jsonSet(PRESETS,p);return true}
  function renderPresetOptions(select){if(!select)return;const current=select.value;select.replaceChildren();const blank=D.createElement("option");blank.value="";blank.textContent="preset…";select.append(blank);for(const name of Object.keys(jsonGet(PRESETS,{})).sort()){const o=D.createElement("option");o.value=name;o.textContent=name;select.append(o)}if([...select.options].some(o=>o.value===current))select.value=current}
  function createToggle(item){const b=D.createElement("button");b.type="button";b.className="bitcoin-ticker__widget-switch";b.dataset.widgetToggle=item.id;b.dataset.moduleLabel=item.label||item.id;if(item.available===false)b.disabled=true;const led=D.createElement("span");led.className="bitcoin-ticker__module-led";led.dataset.moduleLed="";const track=D.createElement("span");track.className="bitcoin-ticker__micro-switch";const lever=D.createElement("span");lever.className="bitcoin-ticker__micro-switch-lever";track.append(lever);const lab=D.createElement("span");lab.className="bitcoin-ticker__widget-switch-label";lab.textContent=item.label||item.id;const st=D.createElement("span");st.className="bitcoin-ticker__widget-switch-state";st.dataset.moduleStatus="";b.append(led,track,lab,st);b.onclick=()=>{if(item.available===false)return;setVisible(item.id,!requestedVisible(item.id));applyButtonState(b,item.id,item)};applyButtonState(b,item.id,item);return b}
  function applyButtonState(b,id,item={}){if(item.available===false){b.dataset.moduleState="off";b.setAttribute("aria-pressed","false");const t=b.querySelector("[data-module-status]");if(t)t.textContent="PLANNED";return}const r=runtimeState(id),on=requestedVisible(id);b.dataset.moduleState=on?r.state:"off";b.setAttribute("aria-pressed",on?"true":"false");const t=b.querySelector("[data-module-status]");if(t)t.textContent=on?(r.state==="on"?"LIVE":r.state.toUpperCase()):"OFF"}
  function updateAll(root,registry){for(const b of root.querySelectorAll("[data-widget-toggle]")){const item=(registry?.widgets||[]).find(x=>x.id===b.dataset.widgetToggle)||{};applyButtonState(b,b.dataset.widgetToggle,item)}}
  function setAll(root,registry,on){for(const item of registry.widgets||[])if(item.available!==false)setVisible(item.id,on);updateAll(root,registry)}
  function render(root,registry){const host=root.querySelector("[data-widget-groups]");if(!host)return;host.replaceChildren();const bar=D.createElement("div");bar.className="bitcoin-ticker__module-toolbar";const on=D.createElement("button");on.type="button";on.className="zzx-widgets__btn";on.textContent="All ON";on.onclick=()=>setAll(root,registry,true);const off=D.createElement("button");off.type="button";off.className="zzx-widgets__btn";off.textContent="All OFF";off.onclick=()=>setAll(root,registry,false);const name=D.createElement("input");name.type="text";name.placeholder="preset name";name.maxLength=48;name.dataset.widgetPresetName="";const select=D.createElement("select");select.dataset.widgetPresetSelect="";renderPresetOptions(select);const save=D.createElement("button");save.type="button";save.className="zzx-widgets__btn";save.textContent="Save preset";save.onclick=()=>{if(savePreset(name.value,registry)){select.value=name.value;name.value=""}};const load=D.createElement("button");load.type="button";load.className="zzx-widgets__btn";load.textContent="Load preset";load.onclick=()=>{if(loadPreset(select.value,registry))updateAll(root,registry)};const del=D.createElement("button");del.type="button";del.className="zzx-widgets__btn";del.textContent="Delete preset";del.onclick=()=>{if(deletePreset(select.value)){renderPresetOptions(select)}};bar.append(on,off,name,select,save,load,del);host.append(bar);const groups=new Map();for(const item of registry.widgets||[]){const g=item.group||"Other";if(!groups.has(g))groups.set(g,[]);groups.get(g).push(item)}for(const [g,items] of groups){const sec=D.createElement("section");sec.className="bitcoin-ticker__widget-group";const h=D.createElement("h4");h.textContent=g;const buttons=D.createElement("div");buttons.className="bitcoin-ticker__widget-buttons";for(const item of items)buttons.append(createToggle(item));sec.append(h,buttons);host.append(sec)}}
  function patchSelection(s){if(!s)return;W.ZZXSelectedPriceUsd=Number(s.priceUsd);W.ZZXSelectedQuoteCurrency=String(s.currency||"USD");W.ZZXSelectedQuotePrice=Number(s.priceQuote)}
  async function mount(root){const reg=await loadRegistry();const layout=jsonGet(LAYOUT,[]);if(layout.length)applyLayout(layout);applyStoredVisibility(reg);render(root,reg);W.addEventListener("zzx:bpi-selection",e=>patchSelection(e.detail));W.addEventListener("zzx:widget-status",()=>updateAll(root,reg));W.addEventListener("zzx:ticker-widget-toggle",()=>updateAll(root,reg));if(W.ZZXBPISelection)patchSelection(W.ZZXBPISelection);updateAll(root,reg);return reg}
  const api=Object.freeze({__version:5,mount,setVisible,visible:requestedVisible,runtimeState,updateAll,setAll,savePreset,loadPreset,deletePreset,captureLayout,applyLayout});W.ZZXBitcoinTickerWidgetModules=api;W.ZZXBitcoinTickerWidgetBridge=api;
})();
