(()=>{"use strict";const $=id=>document.getElementById(id);let files=[],rows=[],selected=null,ops=[];
const ext=n=>n.includes(".")?n.split(".").pop().toLowerCase():"";
const hex=b=>[...b].map(x=>x.toString(16).padStart(2,"0")).join("");
function kind(f){if(f.type.startsWith("image/"))return"image";if(f.type.startsWith("audio/"))return"audio";if(f.type.startsWith("video/"))return"video";if(["txt","md","json","csv","log","html","css","js","py"].includes(ext(f.name)))return"text";return"binary"}
$("dir").onchange=()=>{files=[...$("dir").files];rows=files.map((f,i)=>({i,name:f.name,path:f.webkitRelativePath||f.name,size:f.size,type:f.type||"",kind:kind(f),tags:[],sha256:null,lastModified:f.lastModified}));$("dir").value="";render()};
function visible(){const q=$("search").value.trim().toLowerCase(),tag=$("tag-filter").value.trim().toLowerCase(),k=$("kind").value;return rows.filter(r=>(!q||(r.name+" "+r.path).toLowerCase().includes(q))&&(!k||r.kind===k)&&(!tag||r.tags.some(t=>t.toLowerCase().includes(tag))))}
function render(){const list=visible(),e=$("list");e.replaceChildren();list.forEach(r=>{const b=document.createElement("button");b.className="des-item"+(selected?.i===r.i?" active":"");b.innerHTML=`<strong>${r.name}</strong><br><small>${r.path}<br>${r.kind} · ${r.size} bytes${r.tags.length?` · #${r.tags.join(" #")}`:""}</small>`;b.onclick=()=>preview(r);e.append(b)});$("count").textContent=rows.length;$("visible").textContent=list.length;$("bytes").textContent=rows.reduce((s,r)=>s+r.size,0).toLocaleString();$("tag-count").textContent=new Set(rows.flatMap(r=>r.tags)).size}
["search","tag-filter","kind"].forEach(id=>$(id).oninput=render);
async function preview(r){selected=r;const f=files[r.i],e=$("preview");e.replaceChildren();const meta=document.createElement("pre");meta.className="z-log";meta.textContent=JSON.stringify(r,null,2);e.append(meta);if(r.kind==="text"){const p=document.createElement("pre");p.textContent=(await f.text()).slice(0,250000);e.append(p)}else if(r.kind==="image"){const img=document.createElement("img"),u=URL.createObjectURL(f);img.src=u;img.onload=()=>URL.revokeObjectURL(u);e.append(img)}else if(r.kind==="audio"||r.kind==="video"){const el=document.createElement(r.kind),u=URL.createObjectURL(f);el.src=u;el.controls=true;e.append(el)}render()}
$("tag").onclick=()=>{if(!selected)return;const tags=$("tag-input").value.split(",").map(x=>x.trim()).filter(Boolean);selected.tags=[...new Set([...selected.tags,...tags])];render();preview(selected)};
$("hash").onclick=async()=>{if(!selected)return;selected.sha256=hex(new Uint8Array(await crypto.subtle.digest("SHA-256",await files[selected.i].arrayBuffer())));preview(selected)};
$("bulk").onclick=()=>{const action=$("action").value,pattern=$("pattern").value.trim(),replacement=$("replacement").value.trim();ops=visible().map(r=>{let target=r.path;if(action==="rename"&&pattern){target=r.path.replace(new RegExp(pattern,"g"),replacement)}else if(action==="move"&&replacement){target=replacement.replace(/\/+$/,"")+"/"+r.name}return{source:r.path,action,target,reviewRequired:true,executed:false}});$("ops").textContent=JSON.stringify({schema:"zzx.des.bulk-plan.v1",operations:ops},null,2)};
function dl(text,name,type="application/json"){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("index").onclick=()=>dl(JSON.stringify({schema:"zzx.des.index.v1",exported:new Date().toISOString(),records:rows.map(({i,...x})=>x),contentsIncluded:false},null,2),"zzxdes-index.json");
$("ops-export").onclick=()=>dl(JSON.stringify({schema:"zzx.des.bulk-plan.v1",operations:ops},null,2),"zzxdes-bulk-plan.json");
render();window.ZZXDES=Object.freeze({version:"0.3.0-alpha-web",directBulkMutation:false});
})();
