(()=>{"use strict";const $=id=>document.getElementById(id);let files=[],evidence=[],audit=[];
const hex=b=>[...b].map(x=>x.toString(16).padStart(2,"0")).join("");
function log(action,detail){audit.push({at:new Date().toISOString(),action,detail})}
$("files").onchange=async()=>{for(const f of [...$("files").files]){const bytes=new Uint8Array(await f.arrayBuffer()),hash=hex(new Uint8Array(await crypto.subtle.digest("SHA-256",bytes))),ev={id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2),name:f.name,size:f.size,type:f.type||"unknown",lastModified:new Date(f.lastModified).toISOString(),sha256:hash,headHex:hex(bytes.slice(0,128)),selected:true};evidence.push(ev);files.push(f);log("ingest",{name:f.name,size:f.size,sha256:hash})}$("files").value="";render()};
function render(){const e=$("evidence");e.replaceChildren();evidence.forEach(v=>{const d=document.createElement("div");d.className="ffk-item";d.innerHTML=`<strong>${v.name}</strong> · ${v.size} bytes<div class="fx-watermark">${v.type} · ${v.sha256}</div><button class="btn ghost" data-id="${v.id}">INSPECT</button>`;e.append(d)});e.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>inspect(b.dataset.id));$("count").textContent=evidence.length;$("bytes").textContent=evidence.reduce((s,v)=>s+v.size,0).toLocaleString();$("audit-count").textContent=audit.length}
function inspect(id){const v=evidence.find(x=>x.id===id);if(!v)return;log("inspect",{id,name:v.name});$("inspect").textContent=JSON.stringify(v,null,2)+"\n\nHEAD[128] HEX\n"+v.headHex;render()}
$("process-import").onchange=async()=>{const f=$("process-import").files[0];if(!f)return;try{const t=await f.text(),j=JSON.parse(t);$("process-out").textContent=JSON.stringify(j,null,2);log("process-snapshot-import",{name:f.name})}catch(e){$("process-out").textContent="IMPORT ERROR: "+e.message}$("process-import").value=""};
$("pcap").onchange=async()=>{const f=$("pcap").files[0];if(!f)return;const b=new Uint8Array(await f.slice(0,24).arrayBuffer()),magic=hex(b.slice(0,4));$("pcap-out").textContent=JSON.stringify({name:f.name,size:f.size,headerMagic:magic,recognizedClassicPcap:["d4c3b2a1","a1b2c3d4","4d3cb2a1","a1b23c4d"].includes(magic),packetDecode:"not performed in browser",networkCapture:false},null,2);log("pcap-metadata",{name:f.name,size:f.size,magic});$("pcap").value=""};
$("timeline").onclick=()=>{$("timeline-out").textContent=JSON.stringify([...evidence.map(v=>({time:v.lastModified,event:"file-mtime",name:v.name,sha256:v.sha256})),...audit.map(a=>({time:a.at,event:a.action,detail:a.detail}))].sort((a,b)=>Date.parse(a.time)-Date.parse(b.time)),null,2)};
$("export").onclick=()=>{const t=JSON.stringify({schema:"zzx.ffk.case.v1",exported:new Date().toISOString(),evidence,audit,contentsIncluded:false,readOnly:true},null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="zzxffk-case.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
render();window.ZZXFFK=Object.freeze({version:"0.4.0-alpha-web",readOnly:true});
})();
