(()=>{"use strict";const $=id=>document.getElementById(id),state={sites:[],services:[],edges:[]},uid=()=>crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const site=i=>state.sites.find(x=>x.id===i),svc=i=>state.services.find(x=>x.id===i);
function render(){const sl=$("sites-list");sl.replaceChildren();state.sites.forEach(s=>{const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${esc(s.name)}</strong><p>${esc(s.env)} · ${esc(s.endpoint)}</p>`;sl.append(a)});const ss=$("service-site"),ef=$("edge-from"),et=$("edge-to");for(const e of[ss,ef,et])e.replaceChildren();state.sites.forEach(s=>{const o=document.createElement("option");o.value=s.id;o.textContent=s.name;ss.append(o)});state.services.forEach(s=>{for(const e of[ef,et]){const o=document.createElement("option");o.value=s.id;o.textContent=`${site(s.site)?.name||"?"} / ${s.name}`;e.append(o)}});const sv=$("services-list");sv.replaceChildren();state.services.forEach(s=>{const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${esc(s.name)}</strong><p>${esc(site(s.site)?.name)} · ${esc(s.kind)}</p><pre>${esc(s.meta)}</pre>`;sv.append(a)});const tb=$("edges-body");tb.replaceChildren();state.edges.forEach(e=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${esc(svc(e.from)?.name)}</td><td>${esc(e.kind)}</td><td>${esc(svc(e.to)?.name)}</td>`;tb.append(tr)})}
$("add-site").onclick=()=>{const name=$("site-name").value.trim();if(!name)return;state.sites.push({id:uid(),name,env:$("site-env").value,endpoint:$("site-endpoint").value.trim()});render()};
$("demo-sites").onclick=()=>{Object.assign(state,{sites:[],services:[],edges:[]});for(const [name,env,endpoint] of[["Scranton","production","scranton-control"],["Lab","lab","lab-vpn"],["Backup","staging","backup-site"]])state.sites.push({id:uid(),name,env,endpoint});render()};
$("add-service").onclick=()=>{if(!$("service-site").value)return;state.services.push({id:uid(),site:$("service-site").value,kind:$("service-kind").value,name:$("service-name").value.trim()||$("service-kind").value.toLowerCase().replace(/\W+/g,"-"),meta:$("service-meta").value.trim()});render()};
$("add-edge").onclick=()=>{const f=$("edge-from").value,t=$("edge-to").value;if(!f||!t||f===t)return;state.edges.push({from:f,to:t,kind:$("edge-kind").value});render()};
function topo(){const indeg=Object.fromEntries(state.services.map(s=>[s.id,0])),adj=Object.fromEntries(state.services.map(s=>[s.id,[]]));state.edges.filter(e=>e.kind==="depends-on").forEach(e=>{if(e.from in indeg&&e.to in indeg){indeg[e.from]++;adj[e.to].push(e.from)}});const q=Object.keys(indeg).filter(k=>indeg[k]===0),out=[];while(q.length){const n=q.shift();out.push(n);for(const v of adj[n])if(--indeg[v]===0)q.push(v)}return{order:out,cycles:Object.keys(indeg).filter(k=>indeg[k]>0)}}
$("build-runbook").onclick=()=>{const t=topo(),lines=["gNee SAFE OPERATOR RUNBOOK","","Declarative checklist only; the browser executes nothing.",""];t.order.forEach((sid,i)=>{const s=svc(sid),st=site(s.site);lines.push(`${i+1}. VERIFY ${st?.name} / ${s.name} (${s.kind})`,`   - confirm authorized operator session`,`   - review config diff`,`   - verify backup / rollback point`,`   - run native health check`,`   - record audit result`)});if(t.cycles.length)lines.push("","WARNING dependency cycle: "+t.cycles.map(x=>svc(x)?.name).join(", "));$("runbook").value=lines.join("\n")};
function yaml(){const q=s=>JSON.stringify(String(s));let y="schema: zzx.gnee.plan.v1\nsites:\n";state.sites.forEach(s=>y+=`  - id: ${q(s.id)}\n    name: ${q(s.name)}\n    environment: ${q(s.env)}\n    endpoint: ${q(s.endpoint)}\n`);y+="services:\n";state.services.forEach(s=>y+=`  - id: ${q(s.id)}\n    site: ${q(s.site)}\n    kind: ${q(s.kind)}\n    name: ${q(s.name)}\n    metadata: ${q(s.meta)}\n`);y+="relationships:\n";state.edges.forEach(e=>y+=`  - from: ${q(e.from)}\n    to: ${q(e.to)}\n    kind: ${q(e.kind)}\n`);return y}
function dl(t,n,type){const b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("export-json").onclick=()=>{const t=JSON.stringify({schema:"zzx.gnee.plan.v1",...state,execution:false},null,2);dl(t,"gnee-plan.json","application/json");$("export-output").textContent=t};$("export-yaml").onclick=()=>{const t=yaml();dl(t,"gnee-plan.yaml","text/yaml");$("export-output").textContent=t};render();window.gNee=Object.freeze({version:"0.1.0-alpha-web",getState:()=>JSON.parse(JSON.stringify(state)),remoteExecution:false});window.ZZXHooks?.emit("gnee:ready",{version:"0.1.0-alpha-web"})})();
