(() => {
  "use strict";
  const $=id=>document.getElementById(id),state={agreement:null,actions:[],signatures:[],escrow:null,lastHash:null};
  function renderActions(){const root=$("ac-list");root.replaceChildren();for(const x of state.actions){const e=document.createElement("article");e.className="z-list-item";e.innerHTML="<strong></strong><p></p>";e.querySelector("strong").textContent=`${x.type} · ${x.amountSats.toLocaleString()} sats`;e.querySelector("p").textContent=`${x.condition} · ${x.reference||"no reference"}`;root.appendChild(e);}if(!state.actions.length)root.innerHTML='<div class="z-list-item"><p>No actions.</p></div>';}
  function renderSigs(){const root=$("sg-list");root.replaceChildren();for(const x of state.signatures){const e=document.createElement("article");e.className="z-list-item";e.innerHTML="<strong></strong><p></p>";e.querySelector("strong").textContent=`${x.signer} · ${x.scheme}`;e.querySelector("p").textContent=`agreement hash: ${x.agreementHash} · ref: ${x.reference||"none"}`;root.appendChild(e);}if(!state.signatures.length)root.innerHTML='<div class="z-list-item"><p>No signature-binding records.</p></div>';}
  function build(){state.agreement={id:$("lg-id").value.trim(),title:$("lg-title").value.trim(),jurisdictionNote:$("lg-jur").value.trim(),terms:$("lg-terms").value,updatedAt:new Date().toISOString()};$("lg-output").textContent=JSON.stringify(state.agreement,null,2);return state.agreement;}
  function snapshot(){return{schema:"zzx.bitlegal.agreement.v1",agreement:state.agreement||build(),actions:state.actions,signatures:state.signatures,bitEscrow:state.escrow};}
  async function hash(){state.lastHash=await BitLegalCore.sha256Hex(BitLegalCore.canonical({agreement:state.agreement||build(),actions:state.actions,bitEscrow:state.escrow}));$("nt-output").textContent=JSON.stringify({sha256:state.lastHash,canonicalScope:["agreement","actions","bitEscrow"]},null,2);return state.lastHash;}
  $("lg-build").addEventListener("click",build);$("ac-add").addEventListener("click",()=>{state.actions.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),type:$("ac-type").value,amountSats:Math.max(0,+$("ac-sats").value||0),reference:$("ac-ref").value.trim(),condition:$("ac-condition").value.trim()});renderActions();});$("sg-add").addEventListener("click",async()=>{const h=state.lastHash||await hash();state.signatures.push({signer:$("sg-name").value.trim(),scheme:$("sg-scheme").value.trim(),reference:$("sg-ref").value.trim(),agreementHash:h,recordedAt:new Date().toISOString()});renderSigs();});$("nt-hash").addEventListener("click",()=>hash());$("be-link").addEventListener("click",()=>{state.escrow={id:$("be-id").value.trim(),clause:$("be-clause").value.trim()};$("be-output").textContent=JSON.stringify(state.escrow,null,2);});$("lg-export-json").addEventListener("click",()=>{const txt=JSON.stringify(snapshot(),null,2),b=new Blob([txt],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`bitlegal-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$("lg-export-output").textContent=txt;});$("lg-export-text").addEventListener("click",()=>{const s=snapshot(),txt=`${s.agreement.title}\nAgreement ID: ${s.agreement.id}\nJurisdiction note: ${s.agreement.jurisdictionNote}\n\n${s.agreement.terms}\n\nActions:\n${s.actions.map((x,i)=>`${i+1}. ${x.type} ${x.amountSats} sats — ${x.condition} — ${x.reference}`).join("\n")}\n`;const b=new Blob([txt],{type:"text/plain"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`bitlegal-${Date.now()}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);$("lg-export-output").textContent=txt;});build();renderActions();renderSigs();
  window.BitLegal=Object.freeze({version:"0.1.0-alpha-web",getAgreement:snapshot,hashAgreement:hash});
  window.ZZXHooks?.emit("bitlegal:ready",{version:"0.1.0-alpha-web"});
})();
