(()=>{"use strict";
const $=id=>document.getElementById(id);
let schedule=[],chat=[],clips=[],tips=[],videoURL=null;
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function dl(text,name,type="application/json"){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("add-show").onclick=()=>{const x={id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2),title:$("show-title").value.trim(),dj:$("dj").value.trim(),start:$("show-start").value,durationMinutes:+$("show-duration").value||60,channel:$("channel").value,notes:$("show-notes").value.trim(),created:new Date().toISOString()};if(!x.title||!x.start)return;schedule.push(x);renderSchedule()};
function renderSchedule(){const tb=$("schedule-body");tb.replaceChildren();schedule.sort((a,b)=>a.start.localeCompare(b.start)).forEach((x,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${esc(x.start)}</td><td>${esc(x.title)}</td><td>${esc(x.dj)}</td><td>${x.durationMinutes} min</td><td>${esc(x.channel)}</td><td><button class="btn ghost" data-i="${i}">REMOVE</button></td>`;tb.append(tr)});tb.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>{schedule.splice(+b.dataset.i,1);renderSchedule()});$("show-count").textContent=schedule.length}
$("send-chat").onclick=()=>{const text=$("chat-text").value.trim(),name=$("chat-name").value.trim()||"guest";if(!text)return;const blocked=/\b(spamword1|spamword2)\b/i.test(text);chat.push({at:new Date().toISOString(),name,text,status:blocked?"held":"visible"});$("chat-text").value="";renderChat()};
function renderChat(){const e=$("chat-log");e.replaceChildren();chat.slice(-100).forEach(x=>{const d=document.createElement("div");d.className="sc-msg";d.innerHTML=`<strong>${esc(x.name)}</strong> <span class="fx-watermark">${esc(x.status)}</span><div>${esc(x.text)}</div>`;e.append(d)});$("chat-count").textContent=chat.length;$("held-count").textContent=chat.filter(x=>x.status==="held").length}
$("video-file").onchange=()=>{const f=$("video-file").files[0];if(!f)return;if(videoURL)URL.revokeObjectURL(videoURL);videoURL=URL.createObjectURL(f);$("video").src=videoURL;$("video-name").textContent=f.name;$("video-file").value=""};
$("mark-in").onclick=()=>{$("clip-in").value=$("video").currentTime.toFixed(3)};
$("mark-out").onclick=()=>{$("clip-out").value=$("video").currentTime.toFixed(3)};
$("add-clip").onclick=()=>{const a=+$("clip-in").value,b=+$("clip-out").value;if(!Number.isFinite(a)||!Number.isFinite(b)||b<=a){$("clip-output").textContent="Valid OUT time must be greater than IN.";return}const x={id:Math.random().toString(36).slice(2),title:$("clip-title").value.trim()||`Clip ${clips.length+1}`,inSeconds:a,outSeconds:b,durationSeconds:b-a,source:$("video-name").textContent,created:new Date().toISOString()};clips.push(x);$("clip-output").textContent=JSON.stringify(x,null,2);renderClips()};
function renderClips(){const tb=$("clip-body");tb.replaceChildren();clips.forEach(x=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${esc(x.title)}</td><td>${x.inSeconds.toFixed(2)}</td><td>${x.outSeconds.toFixed(2)}</td><td>${x.durationSeconds.toFixed(2)}</td><td>${esc(x.source)}</td>`;tb.append(tr)});$("clip-count").textContent=clips.length}
$("add-tip").onclick=()=>{const x={id:Math.random().toString(36).slice(2),at:new Date().toISOString(),from:$("tip-from").value.trim()||"anonymous",sats:Math.max(0,+$("tip-sats").value||0),message:$("tip-message").value.trim(),rail:"Lightning",status:"simulated/local-ledger",invoiceReference:$("invoice-ref").value.trim()||null,paymentExecuted:false};tips.push(x);renderTips()};
function renderTips(){const total=tips.reduce((s,x)=>s+x.sats,0);$("tip-count").textContent=tips.length;$("tip-total").textContent=total.toLocaleString()+" sats";$("tips-output").textContent=JSON.stringify(tips,null,2)}
$("export").onclick=()=>dl(JSON.stringify({schema:"zzx.subcircus.workspace.v1",exported:new Date().toISOString(),schedule,chat,clips,tips,liveStreaming:false,liveLightning:false,credentialsStored:false},null,2),"subcircus-workspace.json");
const d=new Date(Date.now()+3600000);$("show-start").value=d.toISOString().slice(0,16);renderSchedule();renderChat();renderClips();renderTips();
window.SubCircus=Object.freeze({version:"0.3.0-alpha-web",liveStreaming:false,liveLightning:false});
})();
