(() => {
  "use strict";
  const $=id=>document.getElementById(id),KEY="zzx-bitpet-state-v1";
  const state={pet:null,history:[],lightningProvider:null};
  function save(){localStorage.setItem(KEY,JSON.stringify({pet:state.pet,history:state.history}));}
  function log(type,detail={}){state.history.push({at:new Date().toISOString(),type,...detail});if(state.history.length>1000)state.history=state.history.slice(-1000);save();renderHistory();}
  function mood(p){if(!p)return"—";if(p.happiness>=80)return"excellent";if(p.happiness>=60)return"good";if(p.happiness>=40)return"neutral";if(p.happiness>=20)return"low";return"miserable";}
  function create(){state.pet={schema:"zzx.bitpet.pet.v1",id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name:$("bp-name").value.trim()||"BitPet",species:$("bp-species").value,chainRef:$("bp-chainref").value.trim(),xp:0,level:1,energy:100,happiness:70,discipline:20,collectiblePoints:0,traits:null,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()};state.history=[];log("create",{name:state.pet.name,species:state.pet.species});render();return state.pet;}
  function render(){const p=state.pet;if(!p){$("bp-level").textContent=$("bp-xp").textContent=$("bp-energy").textContent=$("bp-mood").textContent="—";$("bp-output").textContent="Create a BitPet.";return;}$("bp-level").textContent=p.level;$("bp-xp").textContent=p.xp;$("bp-energy").textContent=`${p.energy}%`;$("bp-mood").textContent=mood(p);$("bp-output").textContent=JSON.stringify(p,null,2);renderTraits();renderHistory();}
  function doAction(type){if(!state.pet)create();const before={...state.pet};state.pet=BitPetCore.action(state.pet,type);state.pet.updatedAt=new Date().toISOString();log("action",{action:type,xpDelta:state.pet.xp-before.xp,energyDelta:state.pet.energy-before.energy});render();$("train-output").textContent=JSON.stringify({action:type,before,after:state.pet},null,2);}
  async function genTraits(){if(!state.pet)create();state.pet.traits=await BitPetCore.traits(state.pet.name,state.pet.species,state.pet.chainRef);log("traits",{seed:state.pet.traits.seed});render();}
  function renderTraits(){const root=$("traits-list");root.replaceChildren();const t=state.pet?.traits;if(!t){root.innerHTML='<div class="z-list-item"><p>No generated traits.</p></div>';return;}for(const [k,v] of Object.entries(t)){const e=document.createElement("article");e.className="z-list-item";const h=document.createElement("strong");h.textContent=k;const p=document.createElement("p");p.textContent=String(v);e.append(h,p);root.appendChild(e);}}
  function applyEvent(event){if(!state.pet)create();state.pet=BitPetCore.applyLightning(state.pet,event);state.pet.updatedAt=new Date().toISOString();log("lightning-event",{event});render();$("ln-output").textContent=JSON.stringify({event,pet:state.pet},null,2);}
  function renderHistory(){$("history-output").textContent=JSON.stringify(state.history.slice().reverse(),null,2);}
  function tick(){if(!state.pet)return;state.pet.energy=BitPetCore.clamp(state.pet.energy-2);state.pet.happiness=BitPetCore.clamp(state.pet.happiness-1);state.pet.updatedAt=new Date().toISOString();log("time-advance");render();}
  function download(){const value={schema:"zzx.bitpet.export.v1",exportedAt:new Date().toISOString(),pet:state.pet,history:state.history};const b=new Blob([JSON.stringify(value,null,2)],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`bitpet-${state.pet?.name||"pet"}-${Date.now()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  $("bp-create").addEventListener("click",create);$("bp-tick").addEventListener("click",tick);document.querySelectorAll("[data-action]").forEach(b=>b.addEventListener("click",()=>doAction(b.dataset.action)));$("traits-generate").addEventListener("click",()=>genTraits().catch(e=>alert(e.message)));$("ln-apply").addEventListener("click",()=>applyEvent({id:`manual-${Date.now()}`,amountSats:Math.max(1,Number($("ln-sats").value)||1),memo:$("ln-memo").value.trim(),type:$("ln-type").value}));$("bp-export").addEventListener("click",download);$("bp-import").addEventListener("change",async()=>{const f=$("bp-import").files?.[0];if(!f)return;const v=JSON.parse(await f.text());if(v.schema!=="zzx.bitpet.export.v1")throw new Error("Unsupported BitPet export.");state.pet=v.pet;state.history=v.history||[];save();render();$("export-output").textContent=`Imported ${f.name}`;$("bp-import").value="";});
  const saved=JSON.parse(localStorage.getItem(KEY)||"null");if(saved?.pet){state.pet=saved.pet;state.history=saved.history||[];}render();
  window.BitPet=Object.freeze({version:"0.1.0-alpha-web",create,action:doAction,generateTraits:genTraits,applyLightningEvent:applyEvent,registerLightningProvider(fn){state.lightningProvider=fn;},async pollLightning(){if(!state.lightningProvider)throw new Error("No Lightning provider registered.");const events=await state.lightningProvider();for(const e of events||[])applyEvent(e);return events?.length||0;},getState:()=>({pet:state.pet?JSON.parse(JSON.stringify(state.pet)):null,history:JSON.parse(JSON.stringify(state.history))})});
  window.ZZXHooks?.emit("bitpet:ready",{version:"0.1.0-alpha-web"});
})();
