(()=>{"use strict";
const $=id=>document.getElementById(id);
let watchId=null,motionOn=false,motionHandler=null,track=[],motionSamples=0,stepLike=0,lastPeak=0,sessionStart=null,sessionTimer=null,media=[];
function hav(a,b){const R=6371000,toR=x=>x*Math.PI/180,dlat=toR(b.lat-a.lat),dlon=toR(b.lon-a.lon),q=Math.sin(dlat/2)**2+Math.cos(toR(a.lat))*Math.cos(toR(b.lat))*Math.sin(dlon/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function distance(){let d=0;for(let i=1;i<track.length;i++)d+=hav(track[i-1],track[i]);return d}
function render(){ $("gps-points").textContent=track.length;$("distance").textContent=distance().toFixed(1)+" m";$("motion-samples").textContent=motionSamples;$("steps").textContent=stepLike;drawTrack() }
function drawTrack(){const c=$("track-canvas"),x=c.getContext("2d"),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.fillStyle="#050505";x.fillRect(0,0,w,h);x.strokeStyle="#202020";for(let i=0;i<=10;i++){x.beginPath();x.moveTo(i*w/10,0);x.lineTo(i*w/10,h);x.stroke();x.beginPath();x.moveTo(0,i*h/10);x.lineTo(w,i*h/10);x.stroke()}if(track.length<2)return;const lons=track.map(p=>p.lon),lats=track.map(p=>p.lat),minx=Math.min(...lons),maxx=Math.max(...lons),miny=Math.min(...lats),maxy=Math.max(...lats),dx=Math.max(.00001,maxx-minx),dy=Math.max(.00001,maxy-miny);x.strokeStyle="#c0d674";x.lineWidth=2;x.beginPath();track.forEach((p,i)=>{const px=30+(p.lon-minx)/dx*(w-60),py=h-30-(p.lat-miny)/dy*(h-60);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
$("gps-start").onclick=()=>{if(!navigator.geolocation){$("sensor-output").textContent="Geolocation unavailable.";return}if(watchId!=null)return;watchId=navigator.geolocation.watchPosition(pos=>{track.push({at:new Date(pos.timestamp).toISOString(),lat:pos.coords.latitude,lon:pos.coords.longitude,accuracy:pos.coords.accuracy,speed:pos.coords.speed});render()},e=>$("sensor-output").textContent="GPS ERROR: "+e.message,{enableHighAccuracy:true,maximumAge:0,timeout:15000});$("gps-state").textContent="WATCHING"};
$("gps-stop").onclick=()=>{if(watchId!=null){navigator.geolocation.clearWatch(watchId);watchId=null}$("gps-state").textContent="STOPPED"};
async function enableMotion(){if(motionOn)return;if(typeof DeviceMotionEvent==="undefined"){$("sensor-output").textContent="DeviceMotion unavailable.";return}if(typeof DeviceMotionEvent.requestPermission==="function"){const p=await DeviceMotionEvent.requestPermission();if(p!=="granted")return}motionHandler=e=>{const a=e.accelerationIncludingGravity||e.acceleration;if(!a)return;const m=Math.sqrt((a.x||0)**2+(a.y||0)**2+(a.z||0)**2);motionSamples++;const now=performance.now(),threshold=+$("threshold").value||12;if(m>threshold&&now-lastPeak>300){stepLike++;lastPeak=now}render()};window.addEventListener("devicemotion",motionHandler);motionOn=true;$("motion-state").textContent="ACTIVE"}
$("motion-start").onclick=enableMotion;$("motion-stop").onclick=()=>{if(motionHandler)window.removeEventListener("devicemotion",motionHandler);motionHandler=null;motionOn=false;$("motion-state").textContent="STOPPED"};
function tick(){if(!sessionStart)return;const s=Math.floor((Date.now()-sessionStart)/1000),m=Math.floor(s/60),r=s%60;$("session-time").textContent=`${String(m).padStart(2,"0")}:${String(r).padStart(2,"0")}`}
$("session-start").onclick=()=>{sessionStart=Date.now();clearInterval(sessionTimer);sessionTimer=setInterval(tick,1000);tick()};
$("session-stop").onclick=()=>{clearInterval(sessionTimer);sessionTimer=null;tick()};
$("media").onchange=async()=>{for(const f of [...$("media").files]){const hash=await crypto.subtle.digest("SHA-256",await f.arrayBuffer());media.push({name:f.name,type:f.type||"unknown",bytes:f.size,sha256:[...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,"0")).join(""),capturedAt:new Date().toISOString()})}$("media-output").textContent=JSON.stringify(media,null,2);$("media").value=""};
$("export").onclick=()=>{const doc={schema:"zzx.rosebud.mobile-session.v1",exported:new Date().toISOString(),track,motion:{samples:motionSamples,stepLikeEvents:stepLike,threshold:+$("threshold").value||12,note:"step-like events are a rough acceleration threshold model, not a certified pedometer"},media,sessionStart:sessionStart?new Date(sessionStart).toISOString():null,apkIncluded:false},t=JSON.stringify(doc,null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="rosebud-mobile-session.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
render();tick();window.RoseBudAPK=Object.freeze({version:"0.1.0-alpha-web",apkIncluded:false});
})();
