(()=>{"use strict";const $=id=>document.getElementById(id),FX=FreedomXCore,REGION="CA",MODE="CEX",PAIR="BTC/CAD",market=new FX.OrderBook(REGION),quorum=new FX.Quorum(3),events=[],settlements=[];let research=new CEXResearchEngine(42),researchBook=null,lastExecution=null,lastBacktest=null;
const ev=(type,data={})=>{events.unshift({at:FX.now(),type,...data});renderEvents()};const money=n=>new Intl.NumberFormat(REGION==="CA"?"en-CA":"en-US",{maximumFractionDigits:2}).format(+n||0);
function renderLive(){const s=market.snapshot();for(const[id,arr]of[["live-bids",s.bids],["live-asks",s.asks]]){const tb=$(id);tb.replaceChildren();arr.slice(0,20).forEach(o=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${FX.esc(o.owner)}</td><td>${money(o.price)}</td><td>${o.remaining.toFixed(8)}</td>`;tb.append(tr)})}const tt=$("trades");tt.replaceChildren();s.trades.forEach(t=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${t.id.slice(0,8)}</td><td>${money(t.price)}</td><td>${t.qty.toFixed(8)}</td><td>${FX.esc(t.buyer)}</td><td>${FX.esc(t.seller)}</td>`;tt.append(tr)})}
async function seedLive(){const base=REGION==="CA"?115000:84000;for(let i=0;i<10;i++)await market.add({owner:`buyer-${i+1}`,side:"buy",price:base-(i+1)*45,qty:+(.02+i*.007).toFixed(8),pair:PAIR});for(let i=0;i<10;i++)await market.add({owner:`seller-${i+1}`,side:"sell",price:base+(i+1)*50,qty:+(.02+i*.006).toFixed(8),pair:PAIR});renderLive();ev("matching_engine_seeded",{pair:PAIR})}
$("seed-live-book").onclick=seedLive;$("meme-toggle").onclick=()=>FreedomXMeme.toggle();$("submit-order").onclick=async()=>{try{const o=await market.add({owner:$("owner").value.trim(),side:$("side").value,price:+$("price").value,qty:+$("qty").value,pair:PAIR});$("order-output").textContent=JSON.stringify({intent:o,exchangeCustody:false,userPrivateKeyReceived:false},null,2);renderLive();ev("order_intent_accepted",{id:o.id,hash:o.intentHash})}catch(e){$("order-output").textContent="ERROR: "+e.message}};
function makeResearchBook(){research=new CEXResearchEngine((+$("seed").value||42)>>>0);researchBook=research.orderBook(+$("mid").value||115000,Math.max(3,+$("levels").value||12),Math.max(.01,+$("tick").value||10),1.5);const tb=$("research-book-body");tb.replaceChildren();for(let i=0;i<researchBook.bids.length;i++){const tr=document.createElement("tr");tr.innerHTML=`<td>${researchBook.bids[i].btc.toFixed(6)}</td><td>${researchBook.bids[i].price.toFixed(2)}</td><td>${researchBook.asks[i].price.toFixed(2)}</td><td>${researchBook.asks[i].btc.toFixed(6)}</td>`;tb.append(tr)}}
$("gen-book").onclick=makeResearchBook;$("simulate-order").onclick=()=>{if(!researchBook)makeResearchBook();lastExecution=research.execute(researchBook,$("research-side").value,Math.max(.000001,+$("amount").value||.25),Math.max(0,+$("fee").value||20));$("execution-output").textContent=JSON.stringify(lastExecution,null,2)};
function draw(series){const c=$("chart"),x=c.getContext("2d"),w=c.width,h=c.height;x.clearRect(0,0,w,h);if(!series.length)return;const vals=series.map(v=>v.equity),mn=Math.min(...vals),mx=Math.max(...vals),span=mx-mn||1;x.beginPath();series.forEach((v,i)=>{const px=20+i/(series.length-1||1)*(w-40),py=h-20-(v.equity-mn)/span*(h-40);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle="#c0d674";x.lineWidth=2;x.stroke()}
$("run-backtest").onclick=()=>{research=new CEXResearchEngine((+$("seed").value||42)>>>0);lastBacktest=research.backtest({days:Math.max(10,+$("days").value||180),start:+$("mid").value||115000,vol:Math.max(0,+$("vol").value||.035),drift:+$("drift").value||0,feeBps:Math.max(0,+$("fee").value||20),strategy:$("strategy").value,cash:Math.max(100,+$("cash").value||10000)});draw(lastBacktest.series);$("backtest-output").textContent=JSON.stringify(lastBacktest.summary,null,2)};
$("run-risk").onclick=()=>{const btc=+$("risk-btc").value,entry=+$("risk-entry").value,move=+$("stress").value/100,stressed=entry*(1+move),pnl=btc*(stressed-entry);$("risk-output").textContent=JSON.stringify({region:"Canada",pair:PAIR,positionBTC:btc,entryPrice:entry,stressMovePct:move*100,stressedPrice:stressed,pnlQuote:pnl,notionalAtEntry:btc*entry},null,2)};
$("make-settlement").onclick=()=>{const t=market.snapshot().trades[0];if(!t){$("settlement-output").textContent="Create a matched trade first.";return}const p=new FX.Settlement(t,REGION,MODE);settlements.unshift(p);showSettlement();ev("settlement_plan_created",{id:p.id})};function showSettlement(){const p=settlements[0];if(!p)return;$("settlement-output").textContent=JSON.stringify({id:p.id,current:p.current(),states:p.states,asset:p.asset,quote:p.quote,customerCustody:p.customerCustody,exchangePrivateKeys:p.exchangePrivateKeys,withdrawalWallet:p.withdrawalWallet},null,2)}$("advance-settlement").onclick=()=>{const p=settlements[0];if(p){p.advance();showSettlement();ev("settlement_advanced",{id:p.id,state:p.current()})}};
document.querySelectorAll("[data-approver]").forEach(b=>b.onclick=()=>{$("quorum-output").textContent=JSON.stringify(quorum.approve(b.dataset.approver),null,2);ev("operator_approval",{role:b.dataset.approver})});$("reset-quorum").onclick=()=>{$("quorum-output").textContent=JSON.stringify(quorum.reset(),null,2)};
function renderEvents(){const e=$("event-log");e.replaceChildren();events.slice(0,40).forEach(v=>{const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${FX.esc(v.type)}</strong><p>${new Date(v.at).toLocaleString()}</p><pre>${FX.esc(JSON.stringify(v,null,2))}</pre>`;e.append(a)})}
$("export-state").onclick=()=>{const doc={schema:"zzx.freedomx.cex.v3",project:"freedomgewsecex",region:REGION,mode:MODE,pair:PAIR,bitcoinOnly:true,noncustodial:true,market:market.snapshot(),research:{book:researchBook,lastExecution,lastBacktest},settlements:settlements.map(s=>({id:s.id,current:s.current(),trade:s.trade})),quorum:quorum.status(),events};const t=JSON.stringify(doc,null,2);FX.download(t,"freedomgewsecex-state.json");$("export-output").textContent=t};
makeResearchBook();renderLive();renderEvents();$("quorum-output").textContent=JSON.stringify(quorum.status(),null,2);window.FreedomXApp=Object.freeze({version:"0.3.0-alpha-web",region:REGION,mode:MODE,bitcoinOnly:true,noncustodial:true});window.ZZXHooks?.emit("freedomgewsecex:ready",{version:"0.3.0-alpha-web"}) })();
