(()=>{"use strict";const $=id=>document.getElementById(id);let records=[];const norm=x=>({name:String(x.name||x.full_name||"").trim(),aliases:Array.isArray(x.aliases)?x.aliases:String(x.aliases||"").split(/[|;]/).map(s=>s.trim()).filter(Boolean),agency:String(x.agency||x.source_agency||"").trim(),notice_id:String(x.notice_id||x.id||"").trim(),status:String(x.status||"").trim(),charges_or_reason:String(x.charges_or_reason||x.reason||x.charges||"").trim(),source_url:String(x.source_url||x.url||"").trim(),published_date:String(x.published_date||x.date||"").trim(),jurisdiction:String(x.jurisdiction||"").trim(),notes:String(x.notes||"").trim()});
function csv(t){const lines=t.split(/\r?\n/).filter(Boolean),head=lines.shift().split(",").map(x=>x.trim());return lines.map(line=>{const vals=line.match(/(".*?"|[^,]*)(?:,|$)/g)?.map(s=>s.replace(/,$/,"").replace(/^"|"$/g,"").replace(/""/g,'"'))||[];return Object.fromEntries(head.map((h,i)=>[h,vals[i]||""]))})}
function parseText(t){let arr;if(t.trim().startsWith("[")||t.trim().startsWith("{")){const x=JSON.parse(t);arr=Array.isArray(x)?x:(x.records||x.notices||[])}else arr=csv(t);records=arr.map(norm).filter(x=>x.name||x.notice_id);render();return records}
$("parse").onclick=()=>{try{parseText($("text").value);$("import-output").textContent=JSON.stringify({imported:records.length,scope:"public/authorized notices only"},null,2)}catch(e){$("import-output").textContent="ERROR: "+e.message}};$("file").onchange=async()=>{const f=$("file").files[0];if(!f)return;$("text").value=await f.text();$("parse").click()};
$("demo").onclick=()=>{$("text").value=JSON.stringify([{name:"Example Person",aliases:["Example Alias"],agency:"Example Agency",notice_id:"ABC-123",status:"wanted",charges_or_reason:"Demonstration record only",source_url:"https://agency.example/notice/ABC-123",published_date:"2026-01-01",jurisdiction:"Example Jurisdiction",notes:"Synthetic demo record."},{name:"Second Example",agency:"Partner Agency",notice_id:"XYZ-456",status:"located",source_url:"https://partner.example/bulletin/XYZ-456",published_date:"2026-02-01",jurisdiction:"Example"}],null,2);$("parse").click()};
function filtered(){const q=$("query").value.toLowerCase(),a=$("agency-filter").value.toLowerCase(),s=$("status-filter").value.toLowerCase();return records.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!a||x.agency.toLowerCase().includes(a))&&(!s||x.status.toLowerCase().includes(s)))}
function render(){const tb=$("results"),sel=$("selected"),sb=$("source-body");tb.replaceChildren();sel.replaceChildren();sb.replaceChildren();filtered().forEach((x,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${x.name}</td><td>${x.agency}</td><td>${x.notice_id}</td><td>${x.status}</td>`;tb.append(tr)});records.forEach((x,i)=>{const o=document.createElement("option");o.value=i;o.textContent=`${x.name||"Unnamed"} · ${x.notice_id}`;sel.append(o);const tr=document.createElement("tr"),link=/^https?:\/\//i.test(x.source_url)?`<a href="${x.source_url}" target="_blank" rel="noopener noreferrer">${x.source_url}</a>`:x.source_url;tr.innerHTML=`<td>${x.agency}</td><td>${x.notice_id}</td><td>${link}</td><td>${x.published_date}</td>`;sb.append(tr)})}
for(const id of["query","agency-filter","status-filter"])$(id).oninput=render;$("show").onclick=()=>{$("record-output").textContent=JSON.stringify(records[+$("selected").value]||null,null,2)};$("print").onclick=()=>{const r=records[+$("selected").value];if(!r)return;const w=open("","_blank","noopener,noreferrer");if(!w)return;w.document.write(`<pre>${JSON.stringify(r,null,2).replace(/</g,"&lt;")}</pre>`);w.document.close();w.print()};
function dl(t,n,type){const b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}$("json").onclick=()=>{const t=JSON.stringify({schema:"zzx.huah.public-notices.v1",generated:new Date().toISOString(),records,scope:"public and authorized sources only"},null,2);dl(t,"huah-notices.json","application/json");$("export-output").textContent=t};$("csv").onclick=()=>{const t="name,aliases,agency,notice_id,status,charges_or_reason,source_url,published_date,jurisdiction,notes\n"+records.map(x=>[x.name,x.aliases.join("|"),x.agency,x.notice_id,x.status,x.charges_or_reason,x.source_url,x.published_date,x.jurisdiction,x.notes].map(v=>JSON.stringify(v)).join(",")).join("\n");dl(t,"huah-notices.csv","text/csv");$("export-output").textContent=t};render();window.Huah=Object.freeze({version:"0.1.0-alpha-web",parseText,getRecords:()=>records.slice(),publicSourcesOnly:true});window.ZZXHooks?.emit("huah:ready",{version:"0.1.0-alpha-web"})})();
