(()=>{"use strict";const $=id=>document.getElementById(id),state={messages:[],jobs:[],plugins:[],emotion:{valence:0,arousal:.4,trust:.5}};
function renderMessages(){const e=$("chat-log");e.replaceChildren();state.messages.slice().reverse().forEach(x=>{const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${GPWebCore.esc(x.kind)} · ${new Date(x.at).toLocaleTimeString()}</strong><p>${GPWebCore.esc(x.text)}</p>`;e.append(a)})}
$("queue-text").onclick=()=>{const text=$("message").value.trim();if(!text)return;const mode=$("mode").value;if(mode.startsWith("Adult")){state.messages.push({at:new Date().toISOString(),kind:"adult-mode-policy",text:"Adult mode selected: adults-only, consensual content; no minors, exploitative sexual content, or identity impersonation."})}state.messages.push({at:new Date().toISOString(),kind:"user",text});state.jobs.push(GPWebCore.job("text",text,{profile:$("profile").value,mode,systemRole:$("role").value,emotion:state.emotion}));renderMessages()};
$("speak").onclick=()=>{try{GPWebCore.speak($("message").value)}catch(e){alert(e.message)}};$("listen").onclick=()=>{const r=GPWebCore.recognition();if(!r){alert("Speech recognition unavailable.");return}r.onresult=e=>{$("message").value=e.results[0][0].transcript};r.start()};
$("queue-media").onclick=()=>{const j=GPWebCore.job($("modality").value,$("media-prompt").value,{adapter:$("adapter").value,seed:+$("seed").value||0,mode:$("mode").value});state.jobs.push(j);$("job-output").textContent=JSON.stringify(j,null,2)};
$("save-emotion").onclick=()=>{state.emotion={valence:+$("valence").value,arousal:+$("arousal").value,trust:+$("trust").value};$("emotion-output").textContent=JSON.stringify({...state.emotion,note:"User-controlled conversational state; not sentience."},null,2)};
function renderPlugins(){const e=$("plugin-list");e.replaceChildren();state.plugins.forEach(p=>{const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${GPWebCore.esc(p.name)} ${GPWebCore.esc(p.version)}</strong><p>${GPWebCore.esc(p.permission)} · ${GPWebCore.esc(p.description)}</p>`;e.append(a)})}
$("add-plugin").onclick=()=>{state.plugins.push({name:$("plugin-name").value.trim(),version:$("plugin-version").value.trim(),permission:$("plugin-perm").value,description:$("plugin-desc").value.trim(),enabled:true});renderPlugins()};
$("export-session").onclick=()=>{const doc={schema:"zzx.gp.session.v1",exported:new Date().toISOString(),profile:$("profile").value,mode:$("mode").value,state},t=JSON.stringify(doc,null,2);GPWebCore.dl(t,"gp-session.json");$("export-output").textContent=t};
renderMessages();renderPlugins();window.GP=Object.freeze({version:"0.2.0-alpha-web",getState:()=>JSON.parse(JSON.stringify(state))});window.ZZXHooks?.emit("gp:ready",{version:"0.2.0-alpha-web"})})();
