(() => {
  "use strict";
  const $=id=>document.getElementById(id),DEFAULT="https://mempool.space/api";
  const state={api:localStorage.getItem("zzx-bit-clock-api")||DEFAULT,height:null,timer:null};
  function status(t,k){const e=$("bc-net");e.textContent=t;e.className=`runtime-badge ${k}`;}
  async function refresh(){status("CHAIN: FETCHING","partial");try{const r=await fetch(`${state.api}/blocks/tip/height`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);apply(Number(await r.text()));status("CHAIN: LIVE","ok");}catch(e){status("CHAIN: ERROR","bad");$("bc-output").textContent=`ERROR: ${e.message}`;}}
  function apply(h){if(!Number.isFinite(h)||h<0)throw new Error("Invalid height.");state.height=Math.floor(h);render();}
  function fmtEta(blocks){const s=blocks*600,d=Math.floor(s/86400),hrs=Math.floor((s%86400)/3600);return`${d.toLocaleString()}d ${hrs}h (estimate)`;}
  function render(){
    const h=state.height;if(h==null)return;const nh=BitClockCore.nextHalving(h),sub=BitClockCore.subsidy(h),issued=BitClockCore.issuedThroughHeight(h),pct=issued/BitClockCore.MAX_BTC*100;
    $("bc-height").textContent=h.toLocaleString();$("bc-subsidy").textContent=`${sub.toFixed(8)} BTC`;$("bc-next").textContent=nh.nextHeight.toLocaleString();$("bc-eta").textContent=fmtEta(nh.blocksRemaining);$("bc-progress").style.width=`${Math.max(0,Math.min(100,nh.progress*100))}%`;
    $("bc-output").textContent=JSON.stringify({height:h,epoch:nh.epoch,subsidyBtc:sub,nextHalvingHeight:nh.nextHeight,blocksRemaining:nh.blocksRemaining,epochProgress:nh.progress,estimatedSecondsRemaining:nh.blocksRemaining*600},null,2);
    $("ep-index").textContent=nh.epoch;$("ep-block").textContent=(h-nh.epoch*BitClockCore.HALVING).toLocaleString();$("ep-remain").textContent=nh.blocksRemaining.toLocaleString();$("ep-progress").textContent=`${(nh.progress*100).toFixed(3)}%`;
    $("em-issued").textContent=`${issued.toLocaleString(undefined,{maximumFractionDigits:8})} BTC`;$("em-remain").textContent=`${Math.max(0,BitClockCore.MAX_BTC-issued).toLocaleString(undefined,{maximumFractionDigits:8})} BTC`;$("em-percent").textContent=`${pct.toFixed(6)}%`;$("em-next").textContent=`${BitClockCore.subsidy(h+1).toFixed(8)} BTC`;drawEpoch(nh);drawEmission(h);
  }
  function renderSchedule(){const body=$("sub-body");body.replaceChildren();for(const r of BitClockCore.schedule(12)){const tr=document.createElement("tr");[r.epoch,r.startHeight.toLocaleString(),r.endHeight.toLocaleString(),r.subsidyBtc.toFixed(8),r.epochIssuanceBtc.toLocaleString(undefined,{maximumFractionDigits:8})].forEach(v=>{const td=document.createElement("td");td.textContent=v;tr.appendChild(td);});body.appendChild(tr);}}
  function canvas(id,h=320){const c=$(id),ctx=c.getContext("2d"),dpr=Math.max(1,Math.min(2,devicePixelRatio||1)),r=c.getBoundingClientRect(),w=Math.max(320,Math.round(r.width)),hh=Math.max(260,Math.round(r.height||h));c.width=w*dpr;c.height=hh*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#050505";ctx.fillRect(0,0,w,hh);return{c,ctx,w,h:hh};}
  function drawEpoch(nh){const {ctx,w,h}=canvas("ep-canvas"),pad=50;ctx.fillStyle="#222";ctx.fillRect(pad,h/2-18,w-pad*2,36);ctx.fillStyle="#c0d674";ctx.fillRect(pad,h/2-18,(w-pad*2)*nh.progress,36);ctx.fillStyle="#969696";ctx.font="11px monospace";ctx.fillText(`epoch ${nh.epoch} · ${(nh.progress*100).toFixed(3)}%`,pad,h/2+45);}
  function drawEmission(height){const {ctx,w,h}=canvas("em-canvas",340),pad=44,pts=[];for(let e=0;e<=12;e++){const ht=e*BitClockCore.HALVING;pts.push([ht,BitClockCore.issuedThroughHeight(Math.max(0,ht-1))]);}pts.push([height,BitClockCore.issuedThroughHeight(height)]);pts.sort((a,b)=>a[0]-b[0]);const maxH=Math.max(...pts.map(x=>x[0]),1);ctx.strokeStyle="#c0d674";ctx.lineWidth=2;ctx.beginPath();pts.forEach(([xv,yv],i)=>{const x=pad+(w-pad*2)*xv/maxH,y=h-35-(yv/BitClockCore.MAX_BTC)*(h-70);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();}
  function auto(){if(state.timer){clearInterval(state.timer);state.timer=null;$("bc-auto").textContent="AUTO: OFF";}else{state.timer=setInterval(refresh,30000);$("bc-auto").textContent="AUTO: 30S";}}
  $("bc-api").value=state.api;$("bc-source-output").textContent=JSON.stringify({api:state.api},null,2);$("bc-refresh").addEventListener("click",refresh);$("bc-auto").addEventListener("click",auto);$("manual-apply").addEventListener("click",()=>{try{apply(Number($("manual-height").value));}catch(e){alert(e.message);}});$("bc-save").addEventListener("click",()=>{state.api=$("bc-api").value.trim().replace(/\/+$/,"")||DEFAULT;localStorage.setItem("zzx-bit-clock-api",state.api);$("bc-source-output").textContent=JSON.stringify({api:state.api},null,2);});$("bc-reset").addEventListener("click",()=>{state.api=DEFAULT;$("bc-api").value=DEFAULT;localStorage.removeItem("zzx-bit-clock-api");$("bc-source-output").textContent=JSON.stringify({api:state.api},null,2);});renderSchedule();apply(Number($("manual-height").value));
  window.BitClock=Object.freeze({version:"0.1.0-alpha-web",refresh,setHeight:apply,subsidy:BitClockCore.subsidy,issuedThroughHeight:BitClockCore.issuedThroughHeight,nextHalving:BitClockCore.nextHalving,getState:()=>({api:state.api,height:state.height})});
  window.ZZXHooks?.emit("bit-clock:ready",{version:"0.1.0-alpha-web"});
})();
