(()=>{"use strict";const $=id=>document.getElementById(id),state={vault:null,password:"",imported:null};function empty(){return{schema:"zzx.cryptainer.vault.v1",label:$("vault-label").value.trim()||"cryptainer",network:$("network").value,identities:[],policy:{threshold:1,approvers:1,mode:"cold-storage",cltvHeight:0,cltvTime:null,csvBlocks:0,allowedOperations:["inspect"]},files:[],audit:[],createdAt:new Date().toISOString()}}function need(){if(!state.vault)throw new Error("Create or unlock a vault first.")}function dl(t,n){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}async function audit(type,data){await CryptainerCore.append(state.vault.audit,{type,data});renderAudit()}
function render(){const ids=$("id-list");ids.replaceChildren();for(const x of state.vault?.identities||[]){const e=document.createElement("article");e.className="z-list-item";e.innerHTML="<strong></strong><p></p>";e.querySelector("strong").textContent=x.name;e.querySelector("p").textContent=`${x.fingerprint||"no fingerprint"} · ${x.note||""}`;ids.append(e)}if(!state.vault?.identities?.length)ids.innerHTML='<div class="z-list-item"><p>No identity references.</p></div>';const fs=$("file-list");fs.replaceChildren();for(const x of state.vault?.files||[]){const e=document.createElement("article");e.className="z-list-item";e.innerHTML="<strong></strong><p></p>";e.querySelector("strong").textContent=x.name;e.querySelector("p").textContent=`${x.bytes} bytes · SHA256 ${x.sha256.slice(0,20)}… · encrypted payload`;fs.append(e)}if(!state.vault?.files?.length)fs.innerHTML='<div class="z-list-item"><p>No encrypted files in vault.</p></div>';renderAudit()}
function renderAudit(){$("audit-output").textContent=JSON.stringify(state.vault?.audit||[],null,2)}
$("create").onclick=async()=>{try{state.password=$("password").value;if(!state.password)throw new Error("Password required.");state.vault=empty();await audit("vault-created",{label:state.vault.label,network:state.vault.network});render();$("vault-output").textContent=`Created in-memory vault ${state.vault.label}. Export it to persist the encrypted container.`}catch(e){$("vault-output").textContent=`ERROR: ${e.message}`}};
$("lock").onclick=()=>{state.vault=null;state.password="";$("password").value="";render();$("vault-output").textContent="Vault locked; decrypted state removed from application memory."};
$("add-id").onclick=async()=>{try{need();const fpr=$("id-fpr").value.replace(/\s+/g,"").toUpperCase();if(fpr&&!/^[0-9A-F]{16,64}$/.test(fpr))throw new Error("Fingerprint should be hexadecimal.");const x={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name:$("id-name").value.trim(),fingerprint:fpr,note:$("id-note").value.trim()};state.vault.identities.push(x);await audit("identity-added",{id:x.id,name:x.name,fingerprint:x.fingerprint});render()}catch(e){alert(e.message)}};
$("save-policy").onclick=async()=>{try{need();const threshold=Math.max(1,+$("threshold").value||1),approvers=Math.max(1,+$("approvers").value||1);if(threshold>approvers)throw new Error("Threshold M cannot exceed approvers N.");state.vault.policy={threshold,approvers,mode:$("policy-mode").value,cltvHeight:Math.max(0,+$("cltv-height").value||0),cltvTime:$("cltv-time").value?new Date($("cltv-time").value).toISOString():null,csvBlocks:Math.max(0,+$("csv-blocks").value||0),allowedOperations:$("ops").value.split(",").map(x=>x.trim()).filter(Boolean)};await audit("policy-updated",state.vault.policy);$("policy-output").textContent=JSON.stringify(state.vault.policy,null,2)}catch(e){$("policy-output").textContent=`ERROR: ${e.message}`}};
$("add-file").onchange=async()=>{try{need();const fs=[...$("add-file").files];for(const f of fs){const bytes=new Uint8Array(await f.arrayBuffer()),sha=await CryptainerCore.sha256(bytes),payload=await CryptainerCore.encryptBytes(bytes,state.password),rec={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),name:f.name,type:f.type,bytes:f.size,sha256:sha,payload};state.vault.files.push(rec);await audit("file-added",{id:rec.id,name:rec.name,bytes:rec.bytes,sha256:rec.sha256})}$("files-output").textContent=`Encrypted ${fs.length} file(s) into the in-memory container.`;render()}catch(e){$("files-output").textContent=`ERROR: ${e.message}`}$("add-file").value=""};
$("verify-audit").onclick=async()=>{$("audit-output").textContent=JSON.stringify({verification:await CryptainerCore.verify(state.vault?.audit||[]),audit:state.vault?.audit||[]},null,2)};
$("export-vault").onclick=async()=>{try{need();const envelope=await CryptainerCore.encryptJSON(state.vault,state.password),outer={schema:"zzx.cryptainer.container.v1",version:"0.1.0-alpha",label:state.vault.label,network:state.vault.network,exportedAt:new Date().toISOString(),envelope};dl(JSON.stringify(outer,null,2),`${state.vault.label}.cryptainer.json`);$("export-output").textContent=JSON.stringify({...outer,envelope:{...envelope,ciphertext:`${envelope.ciphertext.slice(0,72)}…`}},null,2)}catch(e){$("export-output").textContent=`ERROR: ${e.message}`}};
$("import-vault").onchange=async()=>{const f=$("import-vault").files?.[0];if(!f)return;try{const j=JSON.parse(await f.text());if(j.schema!=="zzx.cryptainer.container.v1")throw new Error("Unsupported container schema.");state.imported=j;$("export-output").textContent=`Loaded encrypted container ${j.label}. Enter its password and unlock.`}catch(e){$("export-output").textContent=`ERROR: ${e.message}`}$("import-vault").value=""};
$("unlock-import").onclick=async()=>{try{if(!state.imported)throw new Error("Load an encrypted container first.");const pass=$("import-password").value;state.vault=await CryptainerCore.decryptJSON(state.imported.envelope,pass);state.password=pass;await audit("container-imported",{label:state.vault.label});render();$("vault-output").textContent=`Unlocked ${state.vault.label}.`;$("export-output").textContent="Authenticated AES-GCM decryption succeeded."}catch(e){$("export-output").textContent=`ERROR: ${e.message}`}};
render();window.Cryptainer=Object.freeze({version:"0.1.0-alpha-web",encryptJSON:CryptainerCore.encryptJSON,decryptJSON:CryptainerCore.decryptJSON,verifyAudit:CryptainerCore.verify,isUnlocked:()=>Boolean(state.vault),getVaultMetadata:()=>state.vault?{label:state.vault.label,network:state.vault.network,files:state.vault.files.length,identities:state.vault.identities.length}:null});window.ZZXHooks?.emit("cryptainer:ready",{version:"0.1.0-alpha-web"})})();
