(()=>{"use strict";const $=id=>document.getElementById(id);let audio,gain,node,noise,raf=0,timer=0,remaining=0,running=false,last=0,mantraElapsed=0,mantraCount=0;
function ensureAudio(){audio??=new AudioContext();gain??=audio.createGain();gain.connect(audio.destination);gain.gain.value=+$("volume").value}
function stopSound(){try{node?.stop?.()}catch{};try{noise?.stop?.()}catch{};node=noise=null}
function startSound(){stopSound();ensureAudio();gain.gain.cancelScheduledValues(audio.currentTime);gain.gain.setValueAtTime(0,audio.currentTime);gain.gain.linearRampToValueAtTime(+$("volume").value,audio.currentTime+Math.max(0,+$("fade-in").value));const kind=$("sound-kind").value;if(kind==="tone"){node=audio.createOscillator();node.type="sine";node.frequency.value=+$("tone-hz").value;node.connect(gain);node.start()}else if(kind!=="none"){const len=audio.sampleRate*2,b=audio.createBuffer(1,len,audio.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<len;i++){const w=Math.random()*2-1;if(kind==="brown"){last=(last+0.02*w)/1.02;d[i]=last*3.5}else{d[i]=(w+(i?d[i-1]:0)*0.6)*0.45}}noise=audio.createBufferSource();noise.buffer=b;noise.loop=true;noise.connect(gain);noise.start()}}
function fmt(ms){const s=Math.max(0,Math.ceil(ms/1000));return`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`}
function tick(now){if(!running)return;if(!last)last=now;const dt=now-last;last=now;remaining-=dt;mantraElapsed+=dt;const int=Math.max(3000,+$("mantra-interval").value*1000);if(mantraElapsed>=int){mantraElapsed%=int;mantraCount++;$("mantra-count").textContent=mantraCount;$("mantra-display").textContent=$("mantra").value;if($("mantra-beep").checked)beep()}$("remaining").textContent=fmt(remaining);draw(now);if(remaining<=0){finish();return}raf=requestAnimationFrame(tick)}
function beep(){try{ensureAudio();const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=660;g.gain.value=.025;o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+.1)}catch{}}
function finish(){running=false;cancelAnimationFrame(raf);$("status").textContent="COMPLETE";$("remaining").textContent="00:00";if(gain&&audio){const f=Math.max(0,+$("fade-out").value);gain.gain.cancelScheduledValues(audio.currentTime);gain.gain.setValueAtTime(gain.gain.value,audio.currentTime);gain.gain.linearRampToValueAtTime(0,audio.currentTime+f);setTimeout(stopSound,(f+0.1)*1000)}}
$("start").onclick=()=>{if(running)return;if(remaining<=0)remaining=Math.max(60000,+$("minutes").value*60000);running=true;last=0;$("status").textContent="RUNNING";startSound();raf=requestAnimationFrame(tick)};
$("pause").onclick=()=>{running=false;cancelAnimationFrame(raf);$("status").textContent="PAUSED";stopSound()};
$("reset").onclick=()=>{running=false;cancelAnimationFrame(raf);stopSound();remaining=Math.max(60000,+$("minutes").value*60000);last=0;mantraElapsed=0;mantraCount=0;$("mantra-count").textContent="0";$("status").textContent="READY";$("remaining").textContent=fmt(remaining);draw(performance.now())};
$("volume").oninput=()=>{if(gain)gain.gain.value=+$("volume").value};$("mantra").oninput=()=>{$("mantra-display").textContent=$("mantra").value};
function draw(t){const c=$("visual"),x=c.getContext("2d"),w=c.width,h=c.height;x.clearRect(0,0,w,h);const n=Math.max(3,+$("symmetry").value),dens=Math.max(1,+$("density").value),period=Math.max(2,+$("pulse").value)*1000,p=(1+Math.sin(t/period*Math.PI*2))/2,cx=w/2,cy=h/2,R=80+p*130;x.save();x.translate(cx,cy);x.strokeStyle="#c0d674";x.lineWidth=1.5;x.globalAlpha=.7;for(let k=1;k<=dens;k++){const rr=R*k/dens;x.beginPath();for(let i=0;i<=n;i++){const a=i/n*Math.PI*2+0.25*Math.sin(t/5000),rad=rr*(1+0.12*Math.sin(i*3+t/1500));const px=Math.cos(a)*rad,py=Math.sin(a)*rad;i?x.lineTo(px,py):x.moveTo(px,py)}x.closePath();x.stroke()}x.restore()}
document.querySelectorAll(".preset").forEach(b=>b.onclick=()=>{const p={focus:{sound:"brown",vol:.12,pulse:8,sym:8,interval:60},soft:{sound:"pink",vol:.08,pulse:12,sym:6,interval:90},mantra:{sound:"tone",vol:.08,pulse:10,sym:8,interval:20},silent:{sound:"none",vol:0,pulse:14,sym:10,interval:120}}[b.dataset.p];$("sound-kind").value=p.sound;$("volume").value=p.vol;$("pulse").value=p.pulse;$("symmetry").value=p.sym;$("mantra-interval").value=p.interval;$("preset-output").textContent=JSON.stringify(p,null,2);draw(performance.now())});
$("reset").click();window.Dhama=Object.freeze({version:"0.1.0-alpha-web"});window.ZZXHooks?.emit("dhama:ready",{version:"0.1.0-alpha-web"})})();
