window.SCOPE_CONFIG={"slug": "ipscope", "title": "IPScope", "version": "0.1.0-alpha-web", "example": "ip,asn,provider\n203.0.113.10,AS64500,ExampleNet\n192.168.1.4,private,LAN\n2001:db8::1,AS64501,ExampleIPv6", "dataScope": "Public or authorized IP metadata supplied by the user."};

(()=>{"use strict";const $=id=>document.getElementById(id),cfg=window.SCOPE_CONFIG,C=ScopeCore;let rows=[],analysis=null;
const ex=cfg.example||'';$('input').value=ex;
function count(arr,key){const o={};for(const x of arr){const k=key(x)||'(unknown)';o[k]=(o[k]||0)+1}return Object.entries(o).sort((a,b)=>b[1]-a[1]).map(([name,count])=>({name,count}))}
function analyze(slug,r){
 if(slug==='identityscope'){const cases=count(r,x=>x.case_id||x.group||'ungrouped'),types=count(r,x=>x.type);return{rows:r.length,entityTypes:types,cases,interpretation:'Shared case/group labels are correlation context only; not identity proof.'}}
 if(slug==='emailscope'){const v=r.map(x=>C.normEmail(x.email||x.address||x.value)).filter(Boolean);return{valid:v.length,providers:count(v,x=>x.domain),plusAliases:v.filter(x=>x.local.includes('+')).length,dotLocals:v.filter(x=>x.local.includes('.')).length,note:'Address-shape/alias features do not establish real-person identity.'}}
 if(slug==='ipscope'){const xs=r.map(x=>String(x.ip||x.address||x.value||'').trim()).filter(Boolean);return{rows:xs.length,ipv4:xs.filter(C.validIPv4).length,ipv6:xs.filter(x=>x.includes(':')).length,classes:count(xs,x=>C.validIPv4(x)?C.ipv4Class(x):x.includes(':')?'ipv6':'invalid'),asns:count(r,x=>x.asn||x.provider||'unknown'),note:'ASN/provider metadata should come from authorized/public sources supplied by the user.'}}
 if(slug==='macscope'){const xs=r.map(x=>String(x.mac||x.address||x.value||'').replace(/[^0-9a-f]/gi,'').toLowerCase()).filter(Boolean);const valid=xs.filter(x=>/^[0-9a-f]{12}$/.test(x));return{rows:xs.length,valid:valid.length,locallyAdministered:valid.filter(x=>(parseInt(x.slice(0,2),16)&2)!==0).length,multicast:valid.filter(x=>(parseInt(x.slice(0,2),16)&1)!==0).length,ouis:count(valid,x=>x.slice(0,6)),vendors:count(r,x=>x.vendor||'unknown')}}
 if(slug==='telecomscope'){const imei=r.map(x=>String(x.imei||'').replace(/\D/g,'')).filter(Boolean),imsi=r.map(x=>String(x.imsi||'').replace(/\D/g,'')).filter(Boolean),phones=r.map(x=>String(x.phone||x.number||'').replace(/[^\d+]/g,'')).filter(Boolean);return{rows:r.length,phones:phones.length,imei:imei.length,validImeiLuhn:imei.filter(C.luhn).length,imsi:imsi.length,carriers:count(r,x=>x.carrier||'unknown'),note:'No signaling interception or live subscriber lookup is performed.'}}
 if(slug==='geoscope'){const pts=r.map(x=>({label:x.label||x.id||'',lat:+x.lat,lon:+x.lon})).filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon));const center=pts.length?{lat:pts.reduce((s,x)=>s+x.lat,0)/pts.length,lon:pts.reduce((s,x)=>s+x.lon,0)/pts.length}:null;return{points:pts.length,center,geohashes:pts.map(x=>({...x,geohash:C.geohash(x.lat,x.lon,8),distanceFromCenterKm:center?C.dist(center.lat,center.lon,x.lat,x.lon):0})),note:'User-supplied coordinates only.'}}
 if(slug==='bitcoinscope'){const tx=r.map(x=>({txid:x.txid||x.id||'',time:x.time||x.timestamp||'',inputs:+(x.input_btc||x.inputs_btc||0),outputs:+(x.output_btc||x.outputs_btc||0),address:x.address||''}));const fees=tx.map(x=>Math.max(0,x.inputs-x.outputs));return{transactions:tx.length,totalInputBTC:tx.reduce((s,x)=>s+x.inputs,0),totalOutputBTC:tx.reduce((s,x)=>s+x.outputs,0),totalFeeBTC:fees.reduce((s,x)=>s+x,0),addressLabels:count(tx,x=>x.address||'unlabeled'),note:'Address labels are user-supplied references, not claims of real-world ownership.'}}
 if(slug==='domainscope'){return{rows:r.length,tlds:count(r,x=>{const d=String(x.domain||x.name||'').toLowerCase().split('.');return d.length>1?d.at(-1):'unknown'}),recordTypes:count(r,x=>x.type||x.record_type||'unknown'),hosting:count(r,x=>x.provider||x.hosting||x.asn||'unknown'),note:'No hidden WHOIS history or private registrar data is queried.'}}
 if(slug==='userscope'){const xs=r.map(x=>({handle:String(x.handle||x.username||x.value||'').toLowerCase().replace(/^@/,''),platform:x.platform||x.service||'unknown',source:x.source||''})).filter(x=>x.handle);return{rows:xs.length,platforms:count(xs,x=>x.platform),normalizedDuplicates:count(xs,x=>x.handle).filter(x=>x.count>1),note:'Only public/authorized handle observations; leaked credentials are out of scope.'}}
 if(slug==='devicescope'){const xs=r.map(x=>({id:x.id||'',mac:x.mac||'',imei:x.imei||'',os:x.os||'',model:x.model||'',traits:x.traits||''}));return{rows:xs.length,fingerprints:xs.map(x=>({id:x.id,fingerprint:C.fnv([x.mac,x.imei,x.os,x.model,x.traits].join('|'))})),os:count(xs,x=>x.os||'unknown'),models:count(xs,x=>x.model||'unknown'),note:'Fingerprints compare supplied device records; no covert tracking.'}}
 if(slug==='netscope'){const e=r.map(x=>({from:x.from||x.src||'',to:x.to||x.dst||'',protocol:x.protocol||'',bytes:+(x.bytes||0)})).filter(x=>x.from&&x.to),nodes=[...new Set(e.flatMap(x=>[x.from,x.to]))];const deg=Object.fromEntries(nodes.map(n=>[n,0]));e.forEach(x=>{deg[x.from]++;deg[x.to]++});return{nodes:nodes.length,edges:e.length,totalBytes:e.reduce((s,x)=>s+x.bytes,0),degree:Object.entries(deg).sort((a,b)=>b[1]-a[1]),protocols:count(e,x=>x.protocol||'unknown'),note:'Topology analysis only; no packet capture or scanning.'}}
 if(slug==='timescope'){const ev=r.map(x=>new Date(x.timestamp||x.time||x.date)).filter(x=>!Number.isNaN(x.valueOf()));const hrs=Array(24).fill(0),days=Array(7).fill(0);ev.forEach(d=>{hrs[d.getHours()]++;days[d.getDay()]++});return{events:ev.length,hourHistogram:hrs,weekdayHistogram:days,first:ev.length?new Date(Math.min(...ev)).toISOString():null,last:ev.length?new Date(Math.max(...ev)).toISOString():null}}
 if(slug==='behaviorscope'){const ev=r.map(x=>({actor:x.actor||x.user||'unknown',event:x.event||x.action||x.type||'unknown',time:new Date(x.timestamp||x.time||Date.now())}));return{events:ev.length,actors:count(ev,x=>x.actor),eventTypes:count(ev,x=>x.event),note:'Pattern summaries describe supplied event records and are not psychological diagnosis.'}}
 if(slug==='linkscope'){const e=r.map(x=>({from:x.from||x.source||'',to:x.to||x.target||'',type:x.type||'link'})).filter(x=>x.from&&x.to),nodes=[...new Set(e.flatMap(x=>[x.from,x.to]))],adj=Object.fromEntries(nodes.map(n=>[n,new Set()]));e.forEach(x=>{adj[x.from].add(x.to);adj[x.to].add(x.from)});const seen=new Set(),comps=[];for(const n of nodes)if(!seen.has(n)){const q=[n],c=[];seen.add(n);while(q.length){const v=q.shift();c.push(v);for(const w of adj[v])if(!seen.has(w)){seen.add(w);q.push(w)}}comps.push(c)}return{nodes:nodes.length,edges:e.length,components:comps,degree:nodes.map(n=>[n,adj[n].size]).sort((a,b)=>b[1]-a[1])}}
 if(slug==='datascope'){const keys=[...new Set(r.flatMap(x=>Object.keys(x)))];return{rows:r.length,columns:keys.map(k=>{const vals=r.map(x=>x[k]).filter(v=>v!==''&&v!=null),nums=vals.filter(v=>Number.isFinite(+v));return{name:k,nonNull:vals.length,missing:r.length-vals.length,inferredType:vals.length&&nums.length===vals.length?'number':'text',unique:new Set(vals.map(String)).size}})}}
 if(slug==='signalscope'){const vals=r.map(x=>+(x.value??x.sample??x.amplitude)).filter(Number.isFinite).slice(0,256),N=vals.length,spec=[];for(let k=0;k<Math.min(64,Math.floor(N/2));k++){let re=0,im=0;for(let n=0;n<N;n++){const a=2*Math.PI*k*n/N;re+=vals[n]*Math.cos(a);im-=vals[n]*Math.sin(a)}spec.push({bin:k,magnitude:Math.sqrt(re*re+im*im)/(N||1)})}spec.sort((a,b)=>b.magnitude-a.magnitude);return{samples:N,mean:N?vals.reduce((s,x)=>s+x,0)/N:0,rms:N?Math.sqrt(vals.reduce((s,x)=>s+x*x,0)/N):0,dominantBins:spec.slice(0,8),note:'Offline analysis of user-supplied/lab samples only; no RF capture or interception.'}}
 return{rows:r.length};
}
function renderTable(){const e=$('rows');e.replaceChildren();rows.slice(0,100).forEach((r,i)=>{const a=document.createElement('article');a.className='z-list-item';a.innerHTML=`<strong>row ${i+1}</strong><pre>${C.esc(JSON.stringify(r,null,2))}</pre>`;e.append(a)})}
function draw(){const c=$('canvas'),g=c.getContext('2d'),w=c.width,h=c.height;g.clearRect(0,0,w,h);if(!analysis)return;let vals=[];if(cfg.slug==='timescope')vals=analysis.hourHistogram.map((v,i)=>({name:String(i),count:v}));else if(cfg.slug==='signalscope')vals=analysis.dominantBins.map(x=>({name:String(x.bin),count:x.magnitude}));else{for(const k of ['providers','classes','asns','vendors','carriers','tlds','recordTypes','platforms','eventTypes','protocols','entityTypes'])if(Array.isArray(analysis[k])){vals=analysis[k];break}if(!vals.length&&Array.isArray(analysis.degree))vals=analysis.degree.map(x=>({name:String(x[0]),count:+x[1]}))}if(!vals.length){g.fillStyle='#969696';g.font='16px monospace';g.fillText('No chartable categorical metric for this analysis.',30,50);return}vals=vals.slice(0,20);const max=Math.max(1,...vals.map(x=>+x.count||0)),bw=(w-60)/(vals.length||1);vals.forEach((x,i)=>{const bh=(+x.count||0)/max*(h-90);g.fillStyle='#c0d674';g.fillRect(30+i*bw,h-40-bh,bw*.7,bh);g.fillStyle='#e8e8e8';g.font='10px monospace';g.fillText(String(x.name).slice(0,10),30+i*bw,h-15)})}
$('parse').onclick=()=>{try{rows=C.any($('input').value);$('parse-output').textContent=JSON.stringify({rows:rows.length,scope:cfg.dataScope},null,2);renderTable()}catch(e){$('parse-output').textContent='ERROR: '+e.message}};
$('analyze').onclick=()=>{try{if(!rows.length)$('parse').click();analysis=analyze(cfg.slug,rows);$('analysis-output').textContent=JSON.stringify(analysis,null,2);draw()}catch(e){$('analysis-output').textContent='ERROR: '+e.message}};
$('export-json').onclick=()=>{const doc={schema:`zzx.${cfg.slug}.analysis.v1`,generated:new Date().toISOString(),dataScope:cfg.dataScope,inputRows:rows,analysis};const t=JSON.stringify(doc,null,2);C.dl(t,`${cfg.slug}-analysis.json`);$('export-output').textContent=t};
$('parse').click();$('analyze').click();window.ScopeApp=Object.freeze({config:cfg,getRows:()=>rows.slice(),getAnalysis:()=>analysis});window.ZZXHooks?.emit(`${cfg.slug}:ready`,{version:cfg.version})})();
