(() => {
    "use strict";

    const M = window.ZZXCyberChefModules;
    const config = window.ZZX.CYBERCHEF;
    let official = config.officialDownloadUrl;
    let frameObserver = null;

    function normalize(url) {
        try {
            const u = new URL(url);
            return u.hostname === "github.com" && u.pathname.startsWith("/gchq/CyberChef/") ? u.href : null;
        } catch (_) {
            return null;
        }
    }

    function updateOuter() {
        document.querySelectorAll("[data-cz-official-download]").forEach(anchor => {
            anchor.href = official;
            anchor.removeAttribute("download");
            anchor.target = "_blank";
            anchor.rel = "noopener";
        });
    }

    function looksLikeCyberChefDownload(anchor) {
        const text = String(anchor.textContent || anchor.getAttribute("aria-label") || anchor.title || "").trim();
        const raw = anchor.getAttribute("href") || "";
        if (/download\s+cyberchef/i.test(text)) return true;
        if (anchor.closest("#download-modal") && (/\.zip(?:$|[?#])/i.test(raw) || anchor.hasAttribute("download"))) return true;
        return false;
    }

    // IMPORTANT: Never write an observed attribute unconditionally.  Firefox
    // delivers MutationObserver records even when the replacement value is
    // identical.  The earlier observer rewrote href on *every* callback and
    // generated a self-sustaining microtask loop (mobile/desktop freeze).
    function patchAnchor(anchor) {
        if (!anchor || !looksLikeCyberChefDownload(anchor)) return false;
        let changed = false;
        if (anchor.getAttribute("href") !== official) {
            anchor.setAttribute("href", official);
            changed = true;
        }
        if (anchor.hasAttribute("download")) {
            anchor.removeAttribute("download");
            changed = true;
        }
        if (anchor.getAttribute("target") !== "_blank") {
            anchor.setAttribute("target", "_blank");
            changed = true;
        }
        if (anchor.getAttribute("rel") !== "noopener") {
            anchor.setAttribute("rel", "noopener");
            changed = true;
        }
        if (anchor.dataset.zzxOfficialDownload !== "1") {
            anchor.dataset.zzxOfficialDownload = "1";
            changed = true;
        }
        return changed;
    }

    function patchModifiedFrame() {
        if (M.Runtime?.mode() !== "modified") return;
        const doc = M.Runtime?.document();
        if (!doc) return;
        // One bounded scan at frame readiness; subsequent updates are scoped
        // to newly inserted or explicitly changed anchors below.
        doc.querySelectorAll("a[href], a[download]").forEach(patchAnchor);
    }

    function observeModifiedFrame() {
        frameObserver?.disconnect();
        frameObserver = null;
        if (M.Runtime?.mode() !== "modified") return;
        const doc = M.Runtime?.document();
        const Observer = doc?.defaultView?.MutationObserver || window.MutationObserver;
        if (!doc?.body || !Observer) return;
        patchModifiedFrame();
        frameObserver = new Observer(records => {
            for (const record of records) {
                if (record.type === "attributes") {
                    // patchAnchor is idempotent, so at most one follow-up
                    // observer notification is generated by our own rewrite.
                    patchAnchor(record.target);
                } else if (record.type === "childList") {
                    for (const node of record.addedNodes) {
                        if (node.nodeType !== 1) continue;
                        if (node.matches?.("a[href],a[download]")) patchAnchor(node);
                        node.querySelectorAll?.("a[href],a[download]").forEach(patchAnchor);
                    }
                }
            }
        });
        frameObserver.observe(doc.body, {
            childList: true,
            subtree: true,
            attributes: true,
            attributeFilter: ["href", "download"]
        });
    }

    // Opening the unmodified local app must NOT implicitly run the storage
    // repair operation.  A normal link keeps Firefox popup handling and
    // user-controlled storage intact.
    function openNativeSafely() {
        // Native app anchor already has its correct href/target/rel.
    }

    M.Downloads = {
        setManifest(manifest) {
            const candidate = normalize(manifest?.release?.asset_url) || normalize(manifest?.release?.page_url);
            if (candidate) official = candidate;
            config.officialDownloadUrl = official;
            updateOuter();
            patchModifiedFrame();
        },

        boot() {
            updateOuter();
            document.querySelectorAll("[data-cz-open-native]").forEach(link => {
                link.target = "_blank";
                link.rel = "noopener";
            });
            window.addEventListener("zzx-cyberchef-frame-ready", () => {
                observeModifiedFrame();
                setTimeout(patchModifiedFrame, 250);
                setTimeout(patchModifiedFrame, 1000);
            });
            window.addEventListener("zzx-cyberchef-manifest-ready", e => this.setManifest(e.detail?.manifest));
        }
    };
})();
