(()=>{"use strict";const $=id=>document.getElementById(id),te=new TextEncoder(),td=new TextDecoder();const state={people:[],assets:[],sessions:[],credits:[]};const id=()=>crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2);const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
function sync(){for(const [sel,arr,label] of[["session-people",state.people,"name"],["credit-person",state.people,"name"],["credit-asset",state.assets,"title"]]){const e=$(sel),old=[...e.selectedOptions].map(o=>o.value);e.replaceChildren();arr.forEach(x=>{const o=document.createElement("option");o.value=x.id;o.textContent=x[label];o.selected=old.includes(x.id);e.append(o)})}}
function render(){sync();for(const[name,arr,fn]of[["people-list",state.people,x=>`<strong>${esc(x.name)}</strong><p>${esc(x.role)} · ${esc(x.ref)}</p><p>${esc(x.notes)}</p>`],["assets-list",state.assets,x=>`<strong>${esc(x.title)}</strong><p>${esc(x.type)} · ${esc(x.path)}</p><p>${esc(x.meta)}</p>`],["sessions-list",state.sessions,x=>`<strong>${esc(x.date)} · ${esc(x.project)}</strong><p>${x.people.map(i=>esc(state.people.find(p=>p.id===i)?.name||i)).join(", ")}</p><p>${esc(x.notes)}</p>`],["credits-list",state.credits,x=>`<strong>${esc(state.assets.find(a=>a.id===x.asset)?.title||"asset")}</strong><p>${esc(state.people.find(p=>p.id===x.person)?.name||"person")} · ${esc(x.role)}</p>`]]){const e=$(name);e.replaceChildren();arr.forEach(x=>{const a=document.createElement("article");a.className="z-list-item";a.innerHTML=fn(x);e.append(a)})}}
$("add-person").onclick=()=>{const name=$("person-name").value.trim();if(!name)return;state.people.push({id:id(),name,role:$("person-role").value.trim(),ref:$("person-ref").value.trim(),notes:$("person-notes").value.trim()});$("person-name").value="";render()};
$("add-asset").onclick=()=>{const title=$("asset-title").value.trim();if(!title)return;state.assets.push({id:id(),title,type:$("asset-type").value,path:$("asset-path").value.trim(),meta:$("asset-meta").value.trim()});$("asset-title").value="";render()};
$("add-session").onclick=()=>{if(!$("adult-confirm").checked){alert("Only adult professional/studio records belong in this catalog.");return}state.sessions.push({id:id(),date:$("session-date").value,project:$("session-project").value.trim(),people:[...$("session-people").selectedOptions].map(o=>o.value),notes:$("session-notes").value.trim(),adultConfirmed:true,consentRecordHandled:$("consent-confirm").checked});render()};
$("add-credit").onclick=()=>{if(!$("credit-asset").value||!$("credit-person").value)return;state.credits.push({id:id(),asset:$("credit-asset").value,person:$("credit-person").value,role:$("credit-role").value.trim()});render()};
const b64=b=>{let s="";for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(s)},unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function key(pass,salt,it){const base=await crypto.subtle.importKey("raw",te.encode(pass),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",hash:"SHA-256",salt,iterations:it},base,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
async function enc(pass,it){if(pass.length<8)throw new Error("Use at least 8 characters.");const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(pass,salt,it),ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},k,te.encode(JSON.stringify({schema:"zzx.gbb.v1",state}))));return{schema:"zzx.gbb.encrypted.v1",kdf:{name:"PBKDF2",hash:"SHA-256",iterations:it,salt:b64(salt)},cipher:{name:"AES-GCM",iv:b64(iv)},ciphertext:b64(ct)}}
async function dec(doc,pass){const k=await key(pass,unb64(doc.kdf.salt),doc.kdf.iterations),p=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(doc.cipher.iv)},k,unb64(doc.ciphertext));return JSON.parse(td.decode(p))}
$("export-vault").onclick=async()=>{try{const doc=await enc($("pass").value,Math.max(100000,+$("iterations").value||310000)),t=JSON.stringify(doc,null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="gbb-catalog.enc.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800);$("vault-output").textContent="Encrypted catalog exported."}catch(e){$("vault-output").textContent="ERROR: "+e.message}};
$("import-vault").onchange=async()=>{try{const f=$("import-vault").files[0];if(!f)return;const x=await dec(JSON.parse(await f.text()),$("pass").value);Object.assign(state,x.state);render();$("vault-output").textContent="Catalog imported."}catch(e){$("vault-output").textContent="ERROR: "+e.message}finally{$("import-vault").value=""}};
render();window.GBB=Object.freeze({version:"0.1.0-alpha-web",getState:()=>JSON.parse(JSON.stringify(state))});window.ZZXHooks?.emit("gbb:ready",{version:"0.1.0-alpha-web"})})();
