(()=>{"use strict";
const $=id=>document.getElementById(id);let records=[],selected=null,url=null,cuts=[];
function hashFile(f){return f.arrayBuffer().then(b=>crypto.subtle.digest("SHA-256",b)).then(h=>[...new Uint8Array(h)].map(x=>x.toString(16).padStart(2,"0")).join(""))}
$("files").onchange=async()=>{for(const f of [...$("files").files]){records.push({id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2),name:f.name,type:f.type||"video",bytes:f.size,sha256:await hashFile(f),tags:[],notes:"",duration:null,width:null,height:null,_file:f})}render();$("files").value=""};
function strip(r){const {_file,...x}=r;return x}
function render(){const tb=$("body");tb.replaceChildren();records.forEach((r,i)=>{const tr=document.createElement("tr");tr.innerHTML=`<td><button class="btn ghost" data-i="${i}">OPEN</button></td><td>${r.name}</td><td>${r.bytes}</td><td>${r.duration==null?"—":r.duration.toFixed(1)+" s"}</td><td>${r.width?`${r.width}×${r.height}`:"—"}</td><td>${r.sha256.slice(0,16)}…</td>`;tb.append(tr)});tb.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>openRec(+b.dataset.i));$("count").textContent=records.length}
async function openRec(i){selected=records[i];if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(selected._file);const v=$("video");v.src=url;await new Promise(ok=>{v.onloadedmetadata=ok;setTimeout(ok,1000)});selected.duration=v.duration;selected.width=v.videoWidth;selected.height=v.videoHeight;$("tags").value=selected.tags.join(", ");$("notes").value=selected.notes;render();$("selected-output").textContent=JSON.stringify(strip(selected),null,2)}
$("save").onclick=()=>{if(!selected)return;selected.tags=[...new Set($("tags").value.split(",").map(x=>x.trim().toLowerCase()).filter(Boolean))];selected.notes=$("notes").value.trim();$("selected-output").textContent=JSON.stringify(strip(selected),null,2)};
async function frameScore(v,t){
 v.currentTime=Math.min(Math.max(0,t),Math.max(0,v.duration-.05));await new Promise(ok=>{const done=()=>ok();v.addEventListener("seeked",done,{once:true});setTimeout(ok,800)});
 const c=document.createElement("canvas");c.width=160;c.height=90;const x=c.getContext("2d",{willReadFrequently:true});x.drawImage(v,0,0,c.width,c.height);const d=x.getImageData(0,0,c.width,c.height).data;let sum=0;for(let i=0;i<d.length;i+=16)sum+=(d[i]+d[i+1]+d[i+2])/3;return sum/(d.length/16)
}
$("detect").onclick=async()=>{if(!selected)return;const v=$("video"),samples=Math.max(4,Math.min(120,+$("samples").value||24)),threshold=Math.max(1,+$("threshold").value||28);cuts=[];let prev=null;for(let i=0;i<samples;i++){const t=(v.duration||0)*i/(samples-1),score=await frameScore(v,t);if(prev!=null&&Math.abs(score-prev)>=threshold)cuts.push({time:+t.toFixed(3),delta:+Math.abs(score-prev).toFixed(2),method:"sampled-luminance-delta"});prev=score;$("progress").style.width=((i+1)/samples*100).toFixed(1)+"%"}renderCuts()};
function renderCuts(){const e=$("cuts");e.replaceChildren();cuts.forEach(c=>{const d=document.createElement("div");d.className="soiva-cut";d.innerHTML=`<strong>${c.time.toFixed(2)} s</strong><div class="fx-watermark">luminance delta ${c.delta}</div>`;e.append(d)});$("cut-count").textContent=cuts.length}
$("export").onclick=()=>{const t=JSON.stringify({schema:"zzx.soiva.archive.v1",exported:new Date().toISOString(),records:records.map(strip),selectedCuts:cuts,cutDetection:"coarse sampled luminance delta in browser; native OpenCV pipeline provides full implementation"},null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="soiva-archive.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
render();window.SOIVA=Object.freeze({version:"0.3.0-alpha-web"});
})();
