(() => {
  "use strict";
  const $=id=>document.getElementById(id),state={game:null,commitment:null,serverSeed:null,playerSeed:null,draw:null,market:null,proof:null,settlement:null,settlementProvider:null};
  function download(text,name){const b=new Blob([text],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  function game(){state.game={id:$("bg-id").value.trim(),type:$("bg-type").value,max:Math.max(2,+$("bg-max").value||100)};$("bg-output").textContent=JSON.stringify(state.game,null,2);return state.game;}
  async function commit(){state.serverSeed=$("bc-server").value.trim();if(!state.serverSeed)throw new Error("Server seed required.");state.playerSeed=$("bc-player").value;state.commitment=await BitBettingCore.sha256Hex(state.serverSeed);$("bc-output").textContent=JSON.stringify({commitment:state.commitment,serverSeed:"[hidden until reveal]",playerSeed:state.playerSeed},null,2);}
  async function reveal(){if(!state.commitment)throw new Error("Commit server seed first.");state.game=state.game||game();state.playerSeed=$("bc-player").value;state.draw=await BitBettingCore.draw(state.serverSeed,state.playerSeed,state.game);const proof=currentProof();$("bc-output").textContent=JSON.stringify(proof,null,2);$("vr-json").value=JSON.stringify(proof,null,2);}
  function market(){state.market={id:`PM-${Date.now().toString(36).toUpperCase()}`,question:$("pm-q").value.trim(),outcomes:[$("pm-a").value.trim(),$("pm-b").value.trim()],oracleReference:$("pm-oracle").value.trim(),createdAt:new Date().toISOString()};$("pm-output").textContent=JSON.stringify(state.market,null,2);}
  function proofMeta(){state.proof={bitContractId:$("pf-contract").value.trim(),txid:$("pf-txid").value.trim(),blockHash:$("pf-block").value.trim(),recordedAt:new Date().toISOString()};$("pf-output").textContent=JSON.stringify(state.proof,null,2);}
  function settlement(){state.settlement={winner:$("st-winner").value.trim(),amountSats:Math.max(0,+$("st-sats").value||0),paymentReference:$("st-ref").value.trim(),gameId:(state.game||game()).id,createdAt:new Date().toISOString(),status:"instruction-only"};$("st-output").textContent=JSON.stringify(state.settlement,null,2);return state.settlement;}
  function currentProof(){return{schema:"zzx.bitbetting.proof.v1",game:state.game,commitment:state.commitment,serverSeed:state.serverSeed,playerSeed:state.playerSeed,draw:state.draw,predictionMarket:state.market,onChainProof:state.proof,settlement:state.settlement};}
  async function verify(v){const commitment=await BitBettingCore.sha256Hex(v.serverSeed),draw=await BitBettingCore.draw(v.serverSeed,v.playerSeed,v.game),validCommit=commitment===v.commitment,validDraw=draw.digest===v.draw?.digest&&String(draw.result)===String(v.draw?.result);return{valid:validCommit&&validDraw,validCommitment:validCommit,validDraw,recomputed:{commitment,draw}};}
  $("bg-build").addEventListener("click",game);$("bc-random").addEventListener("click",()=>{$("bc-server").value=BitBettingCore.randomHex(32);});$("bc-commit").addEventListener("click",()=>commit().catch(e=>$("bc-output").textContent=`ERROR: ${e.message}`));$("bc-reveal").addEventListener("click",()=>reveal().catch(e=>$("bc-output").textContent=`ERROR: ${e.message}`));$("pm-build").addEventListener("click",market);$("pf-save").addEventListener("click",proofMeta);$("st-build").addEventListener("click",settlement);$("st-send").addEventListener("click",async()=>{try{if(!state.settlementProvider)throw new Error("No settlement provider registered.");const s=state.settlement||settlement(),r=await state.settlementProvider(s);$("st-output").textContent=JSON.stringify({instruction:s,providerResult:r},null,2);}catch(e){$("st-output").textContent=`ERROR: ${e.message}`;}});$("vr-run").addEventListener("click",async()=>{try{$("vr-output").textContent=JSON.stringify(await verify(JSON.parse($("vr-json").value)),null,2);}catch(e){$("vr-output").textContent=`ERROR: ${e.message}`;}});$("vr-export").addEventListener("click",()=>download(JSON.stringify(currentProof(),null,2),`bitbetting-proof-${Date.now()}.json`));$("bc-server").value=BitBettingCore.randomHex(32);game();
  window.BitBetting=Object.freeze({version:"0.1.0-alpha-web",draw:BitBettingCore.draw,verify,registerSettlementProvider(fn){state.settlementProvider=fn;},getProof:currentProof});
  window.ZZXHooks?.emit("bitbetting:ready",{version:"0.1.0-alpha-web"});
})();
