(()=>{"use strict";const $=id=>document.getElementById(id);let x=0,raf=null,last=performance.now(),meta={};
function compose(){const parts=[];if($("title").checked)parts.push($("title-v").value||"Unknown title");if($("artist").checked&&$("artist-v").value)parts.push($("artist-v").value);if($("album").checked&&$("album-v").value)parts.push($("album-v").value);if($("state").checked)parts.push($("state-v").value);$("line").textContent=parts.join("  •  ");style()}
function style(){const l=$("line");l.style.fontSize=(+$("size").value||28)+"px";l.style.color=$("color").value;l.style.opacity=(+$("opacity").value||100)/100;l.style.fontFamily=$("font").value;$("stage").style.background=$("bg").value}
["title-v","artist-v","album-v","state-v","size","color","opacity","font","bg","title","artist","album","state"].forEach(id=>$(id).oninput=compose);
function run(){cancelAnimationFrame(raf);x=$("stage").clientWidth;last=performance.now();const loop=t=>{const dt=(t-last)/1000;last=t;x-=(+$("speed").value||100)*dt;const l=$("line");l.style.left=x+"px";if(x<-l.offsetWidth)x=$("stage").clientWidth;raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop)}
$("start").onclick=run;$("stop").onclick=()=>cancelAnimationFrame(raf);
$("import").onchange=async()=>{const f=$("import").files[0];if(!f)return;try{const j=JSON.parse(await f.text()),info=j.information||{},cat=info.category||{},m=cat.meta||j.meta||{};meta={title:m.title||m.filename||"",artist:m.artist||"",album:m.album||"",state:j.state||""};$("title-v").value=meta.title;$("artist-v").value=meta.artist;$("album-v").value=meta.album;$("state-v").value=meta.state;compose()}catch(e){$("output").textContent="IMPORT ERROR: "+e.message}$("import").value=""};
$("export").onclick=()=>{const cfg={schema:"zzx.vlc-ticker.config.v1",created:new Date().toISOString(),template:$("line").textContent,speed:+$("speed").value,size:+$("size").value,color:$("color").value,background:$("bg").value,opacity:+$("opacity").value,font:$("font").value,fields:{title:$("title").checked,artist:$("artist").checked,album:$("album").checked,state:$("state").checked},vlcHttp:"http://127.0.0.1:8080/requests/status.json",credentials:"external/native only"};const t=JSON.stringify(cfg,null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="vlc-ticker-config.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
compose();run();window.VLCTicker=Object.freeze({version:"0.2.0-alpha-web",liveVLC:false});
})();
