(()=>{"use strict";const $=id=>document.getElementById(id),S=SpeciedexShared;let records=[];
const endpoints=[
["GET","/v1/species","List canonical species records"],["GET","/v1/species/{id}","Fetch one record"],["GET","/v1/search?q=","Search canonical/normalized fields"],["GET","/v1/taxonomy/{id}","Return lineage"],["GET","/v1/stats","Dataset statistics"],["GET","/v1/archives","Archive metadata surface"],["GET","/v1/genetics/{id}","GeneticBank link surface"]
];
function sample(){records=[S.normalize({id:"sp-blue-whale",scientificName:"Balaenoptera musculus",commonName:"Blue whale",kingdom:"Animalia",phylum:"Chordata",class:"Mammalia",order:"Artiodactyla",family:"Balaenopteridae",genus:"Balaenoptera",status:"Endangered",region:"Global oceans"}),S.normalize({id:"sp-tiger",scientificName:"Panthera tigris",commonName:"Tiger",kingdom:"Animalia",phylum:"Chordata",class:"Mammalia",order:"Carnivora",family:"Felidae",genus:"Panthera",status:"Endangered",region:"Asia"})];$("records").textContent=records.length}
$("sample").onclick=sample;$("dataset").onchange=async()=>{const f=$("dataset").files[0];if(!f)return;try{const j=JSON.parse(await f.text()),arr=Array.isArray(j)?j:(j.records||[]);records=arr.map(S.normalize).filter(r=>!S.rejectHuman(r));$("records").textContent=records.length}catch(e){$("response").textContent="IMPORT ERROR: "+e.message}$("dataset").value=""};
function respond(path){let status=200,body;if(path==="/v1/species")body={records};else if(path.startsWith("/v1/search")){const q=(new URL("https://x.invalid"+path)).searchParams.get("q")?.toLowerCase()||"";body={query:q,records:records.filter(r=>JSON.stringify(r).toLowerCase().includes(q))}}else if(path==="/v1/stats")body={records:records.length,kingdoms:new Set(records.map(r=>r.kingdom)).size,genera:new Set(records.map(r=>r.genus)).size};else if(path.startsWith("/v1/taxonomy/")){const id=decodeURIComponent(path.split("/").pop()),r=records.find(x=>x.id===id||x.scientificName===id);if(!r){status=404;body={error:"not_found"}}else body={id:r.id,lineage:Object.fromEntries(S.rankOrder.map(k=>[k,r[k]]))}}else if(path.startsWith("/v1/species/")){const id=decodeURIComponent(path.split("/").pop()),r=records.find(x=>x.id===id||x.scientificName===id);if(!r){status=404;body={error:"not_found"}}else body=r}else if(path==="/v1/archives")body={records:[],note:"attach SpeciedexArchives backend in native deployment"};else if(path.startsWith("/v1/genetics/"))body={records:[],note:"attach SpeciedexGeneticBank backend in native deployment"};else{status=404;body={error:"unknown_endpoint"}}$("response").textContent=JSON.stringify({status,headers:{"content-type":"application/json","x-speciedex-api-version":"v1"},body},null,2)}
$("send").onclick=()=>respond($("path").value.trim());
function renderEndpoints(){const e=$("endpoints");e.replaceChildren();endpoints.forEach(([method,path,desc])=>{const d=document.createElement("div");d.className="endpoint";d.innerHTML=`<span class="method">${method}</span> <code>${path}</code><p>${desc}</p>`;e.append(d)})}
$("openapi").onclick=()=>{const spec={openapi:"3.1.0",info:{title:"SpeciedexAPI",version:"0.1.0-alpha"},servers:[{url:"https://speciedex.org/api"}],paths:Object.fromEntries(endpoints.map(([method,path,desc])=>[path.split("?")[0].replace(/\{id\}/g,"{id}"),{get:{summary:desc,responses:{"200":{description:"JSON response"}}}}]))};S.download(JSON.stringify(spec,null,2),"speciedexapi-openapi.json")};
sample();renderEndpoints();respond("/v1/stats");window.SpeciedexAPI=Object.freeze({version:"0.1.0-alpha-web",opensServer:false});
})();
