(()=>{"use strict";const $=id=>document.getElementById(id);let selected=new Set(["python","git","curl"]);
const catalog={python:["python","python-pip"],git:["git"],curl:["curl"],ffmpeg:["ffmpeg"],bitcoin:["bitcoin"],tor:["tor"],openssh:["openssh"],clang:["clang","cmake","make"],science:["numpy","scipy"]};
document.querySelectorAll("[data-pkg]").forEach(c=>c.onchange=()=>{c.checked?selected.add(c.dataset.pkg):selected.delete(c.dataset.pkg);render()});
function render(){const pkgs=[...new Set([...selected].flatMap(k=>catalog[k]||[]))];$("pkg-count").textContent=pkgs.length;$("packages").textContent=pkgs.join(" ");$("install").textContent=`pkg update && pkg upgrade\npkg install ${pkgs.join(" ")}`;$("backup").textContent=`tar -czf termux-home-backup.tar.gz -C "$HOME" .\nsha256sum termux-home-backup.tar.gz > termux-home-backup.sha256`}
$("wrapper").onclick=()=>{$("wrapper-out").textContent=`#!/data/data/com.termux/files/usr/bin/bash\nset -euo pipefail\nNAME="${$("tool").value}"\nWORK="$HOME/.local/share/zzxtas/$NAME"\nmkdir -p "$WORK"\ncd "$WORK"\nprintf '%s\\n' "Launching $NAME in $WORK"\n# Add the operator-reviewed local command here.\n# Credentials and private keys must be provided outside this wrapper and are not embedded.\n`};
$("env").onclick=()=>{$("env-out").textContent=JSON.stringify({schema:"zzx.tas.environment.v1",termuxHome:"$HOME",storageShared:"$HOME/storage/shared",python:"$PREFIX/bin/python",git:"$PREFIX/bin/git",ffmpeg:"$PREFIX/bin/ffmpeg",credentialPolicy:"environment-or-local-config-only; never embedded",remoteExecution:false},null,2)};
$("export").onclick=()=>{const t=JSON.stringify({schema:"zzx.tas.plan.v1",selected:[...selected],generated:new Date().toISOString(),autoExecute:false,credentials:false},null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="zzxtas-plan.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
render();window.ZZXTAS=Object.freeze({version:"0.2.0-alpha-web",autoExecute:false});
})();
