(()=>{"use strict";const $=id=>document.getElementById(id),routes=[];let ctx,source,gain,pan,devices=[];
async function permission(){const s=await navigator.mediaDevices.getUserMedia({audio:true});s.getTracks().forEach(t=>t.stop());await enumerate()}
async function enumerate(){if(!navigator.mediaDevices?.enumerateDevices){$("preview-output").textContent="MediaDevices API unavailable.";return}devices=await navigator.mediaDevices.enumerateDevices();const tb=$("device-body"),sel=$("output-device");tb.replaceChildren();sel.replaceChildren();for(const d of devices){const tr=document.createElement("tr");tr.innerHTML=`<td>${d.kind}</td><td>${d.label||"(permission required for label)"}</td><td>${d.deviceId?d.deviceId.slice(0,20)+"…":"—"}</td>`;tb.append(tr);if(d.kind==="audiooutput"){const o=document.createElement("option");o.value=d.deviceId;o.textContent=d.label||`Output ${sel.options.length+1}`;sel.append(o)}}}
$("permission").onclick=()=>permission().catch(e=>$("preview-output").textContent="ERROR: "+e.message);$("enumerate").onclick=()=>enumerate().catch(e=>$("preview-output").textContent="ERROR: "+e.message);
$("audio-file").onchange=()=>{const f=$("audio-file").files[0];if(!f)return;$("audio").src=URL.createObjectURL(f);if(!ctx){ctx=new AudioContext();source=ctx.createMediaElementSource($("audio"));gain=ctx.createGain();pan=ctx.createStereoPanner();source.connect(gain).connect(pan).connect(ctx.destination)}};
$("gain").oninput=()=>{if(gain)gain.gain.value=+$("gain").value};$("pan").oninput=()=>{if(pan)pan.pan.value=+$("pan").value};
$("apply-output").onclick=async()=>{const a=$("audio"),id=$("output-device").value;try{if(typeof a.setSinkId!=="function")throw new Error("HTMLMediaElement.setSinkId() is not available in this browser.");await a.setSinkId(id);$("preview-output").textContent=JSON.stringify({applied:true,deviceId:id,gain:+$("gain").value,pan:+$("pan").value},null,2)}catch(e){$("preview-output").textContent="ERROR: "+e.message}};
function renderRoutes(){const e=$("route-list");e.replaceChildren();routes.forEach((r,i)=>{const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${r.pattern}</strong><p>${r.output} · ${r.gainDb} dB</p><button class="btn ghost" data-i="${i}">REMOVE</button>`;e.append(a)});e.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>{routes.splice(+b.dataset.i,1);renderRoutes()})}
$("add-route").onclick=()=>{routes.push({pattern:$("tab-pattern").value.trim(),output:$("route-output").value.trim(),gainDb:+$("route-gain").value||0});renderRoutes()};
$("generate-manifest").onclick=()=>{$("manifest-output").value=JSON.stringify({manifest_version:2,name:"FAR (Firefox Audio Router)",version:"0.1.0",description:"Per-tab audio routing policy and gain-control extension.",permissions:["tabs","activeTab","storage"],browser_action:{default_title:"FAR"},background:{scripts:["background.js"]},applications:{gecko:{id:"far@zzx-labs.io"}},zzx_note:"Actual output-device routing requires supported Firefox/OS APIs or a native companion; do not claim normal webpages can reroute every tab."},null,2)};
function dl(t,n){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("export-routes").onclick=()=>dl(JSON.stringify({schema:"zzx.far.routes.v1",routes},null,2),"far-routes.json");renderRoutes();window.FAR=Object.freeze({version:"0.1.0-alpha-web",getRoutes:()=>routes.slice()});window.ZZXHooks?.emit("far:ready",{version:"0.1.0-alpha-web"})})();
