(()=>{"use strict";const $=id=>document.getElementById(id);let nodes=[];const esc=s=>String(s??"");
function normalize(x){const host=esc(x.host||x.address||x.node||"").trim(),port=Number(x.port||8333),network=(x.network||(/\.onion$/i.test(host)?"tor":"clearnet")).toLowerCase(),country=esc(x.country||x.country_code||"--").toUpperCase();return{host,port:Number.isFinite(port)?port:8333,network:network.includes("tor")?"tor":"clearnet",country,asn:esc(x.asn||""),version:esc(x.version||""),height:Number(x.height||x.block_height||0)||null,seen:esc(x.seen||x.timestamp||"")}}
function parseText(t){let x=JSON.parse(t),arr=Array.isArray(x)?x:(x.nodes||x.results||[]);if(!Array.isArray(arr))throw new Error("Expected an array or object with nodes/results array.");nodes=arr.map(normalize).filter(x=>x.host);render();return nodes}
function render(){const tor=nodes.filter(x=>x.network==="tor").length;$("nodes").textContent=nodes.length;$("tor").textContent=tor;$("clear").textContent=nodes.length-tor;const counts={};nodes.forEach(x=>counts[x.country]=(counts[x.country]||0)+1);const tb=$("countries");tb.replaceChildren();Object.entries(counts).sort((a,b)=>b[1]-a[1]).forEach(([c,n])=>{const tr=document.createElement("tr");tr.innerHTML=`<td>${c}</td><td>${n}</td><td>${nodes.length?(n/nodes.length*100).toFixed(1):0}%</td>`;tb.append(tr)});$("parse-output").textContent=JSON.stringify({nodes:nodes.length,tor,clearnet:nodes.length-tor,countries:Object.keys(counts).length},null,2)}
$("parse").onclick=()=>{try{parseText($("snapshot-text").value)}catch(e){$("parse-output").textContent="ERROR: "+e.message}};
$("snapshot-file").onchange=async()=>{const f=$("snapshot-file").files[0];if(!f)return;$("snapshot-text").value=await f.text();$("parse").click()};
$("load-demo").onclick=()=>{$("snapshot-text").value=JSON.stringify([{host:"alpha.onion",port:8333,country:"--",network:"tor",version:"/Satoshi:28.0/"},{host:"203.0.113.10",port:8333,country:"US",network:"clearnet",version:"/Satoshi:28.0/"},{host:"198.51.100.5",port:8333,country:"CA",network:"clearnet",version:"/Satoshi:27.1/"},{host:"beta.onion",port:8333,country:"--",network:"tor"}],null,2);$("parse").click()};
$("build-plan").onclick=()=>{const h=Math.max(1,+$("interval").value||6),days=Math.max(1,+$("retention").value||30);$("schedule-output").textContent=JSON.stringify({schema:"zzx.fullnode-scraper.collection-plan.v1",source:$("source").value.trim(),intervalHours:h,snapshotsPerDay:24/h,retentionDays:days,approxSnapshotCount:Math.ceil(days*24/h),outputPattern:"nodes-YYYYMMDD-HHMM.json",scope:"public Bitcoin node datasets / authorized collectors only",browserScanning:false},null,2)};
function dl(t,n,type){const b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("export-json").onclick=()=>{const t=JSON.stringify({schema:"zzx.fullnode-scraper.snapshot.v1",generated:new Date().toISOString(),nodes},null,2);dl(t,"fullnode-snapshot.normalized.json","application/json");$("export-output").textContent=t};
$("export-csv").onclick=()=>{const t="host,port,network,country,asn,version,height,seen\n"+nodes.map(x=>[x.host,x.port,x.network,x.country,x.asn,JSON.stringify(x.version),x.height??"",x.seen].join(",")).join("\n");dl(t,"fullnode-snapshot.csv","text/csv");$("export-output").textContent=t};
window.FullNodeScraper=Object.freeze({version:"0.1.0-alpha-web",parseText,networkScanning:false});window.ZZXHooks?.emit("fullnode-scraper:ready",{version:"0.1.0-alpha-web"})})();
