(()=>{"use strict";const $=id=>document.getElementById(id);let entries=[];
const STORE="zzx.trackertally.v1";
function save(){localStorage.setItem(STORE,JSON.stringify(entries))}
function load(){try{entries=JSON.parse(localStorage.getItem(STORE)||"[]");if(!Array.isArray(entries))entries=[]}catch{entries=[]}render()}
function add(){const x={id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2),at:$("at").value||new Date().toISOString().slice(0,16),category:$("category").value.trim(),amount:+$("amount").value||0,unit:$("unit").value.trim()||"count",context:$("context").value.trim(),notes:$("notes").value.trim()};if(!x.category)return;entries.push(x);save();render()}
function render(){const q=$("filter").value.trim().toLowerCase(),list=entries.filter(x=>!q||JSON.stringify(x).toLowerCase().includes(q)).sort((a,b)=>b.at.localeCompare(a.at));const e=$("list");e.replaceChildren();list.forEach(x=>{const d=document.createElement("div");d.className="tt-entry";d.innerHTML=`<strong>${x.category}</strong> · ${x.amount} ${x.unit}<div>${x.at}</div><div class="fx-watermark">${x.context||""} ${x.notes||""}</div><button class="btn ghost" data-id="${x.id}">DELETE</button>`;e.append(d)});e.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>{entries=entries.filter(x=>x.id!==b.dataset.id);save();render()});const today=new Date().toISOString().slice(0,10),todayRows=entries.filter(x=>x.at.startsWith(today)),total=todayRows.reduce((s,x)=>s+x.amount,0);$("count").textContent=entries.length;$("today").textContent=todayRows.length;$("today-total").textContent=total.toLocaleString();$("categories").textContent=new Set(entries.map(x=>x.category)).size;draw()}
function draw(){const c=$("chart"),x=c.getContext("2d"),w=c.width,h=c.height;x.clearRect(0,0,w,h);x.fillStyle="#050505";x.fillRect(0,0,w,h);const days=[];for(let i=13;i>=0;i--){const d=new Date(Date.now()-i*86400000),key=d.toISOString().slice(0,10),v=entries.filter(e=>e.at.startsWith(key)).reduce((s,e)=>s+e.amount,0);days.push({key,v})}const max=Math.max(1,...days.map(d=>d.v));x.strokeStyle="#343434";for(let i=0;i<=4;i++){let yy=20+i*(h-50)/4;x.beginPath();x.moveTo(35,yy);x.lineTo(w-15,yy);x.stroke()}x.strokeStyle="#c0d674";x.lineWidth=2;x.beginPath();days.forEach((d,i)=>{const px=35+i*(w-55)/13,py=h-30-d.v/max*(h-55);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke();x.fillStyle="#e8e8e8";x.font="11px monospace";x.fillText(days[0].key.slice(5),35,h-10);x.fillText(days[13].key.slice(5),w-55,h-10)}
function dl(text,name,type="application/json"){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("add").onclick=add;$("filter").oninput=render;$("clear").onclick=()=>{if(confirm("Clear local TrackerTally records in this browser?")){entries=[];save();render()}};
$("export-json").onclick=()=>dl(JSON.stringify({schema:"zzx.trackertally.export.v1",exported:new Date().toISOString(),entries},null,2),"trackertally.json");
$("export-csv").onclick=()=>{const esc=s=>`"${String(s??"").replace(/"/g,'""')}"`,rows=[["at","category","amount","unit","context","notes"],...entries.map(x=>[x.at,x.category,x.amount,x.unit,x.context,x.notes])];dl(rows.map(r=>r.map(esc).join(",")).join("\n"),"trackertally.csv","text/csv")};
$("import").onchange=async()=>{const f=$("import").files[0];if(!f)return;try{const j=JSON.parse(await f.text()),arr=Array.isArray(j)?j:(j.entries||[]);entries=arr.map(x=>({...x,id:x.id||Math.random().toString(36).slice(2)}));save();render()}catch(e){$("status").textContent="IMPORT ERROR: "+e.message}$("import").value=""};
$("at").value=new Date().toISOString().slice(0,16);load();window.TrackerTally=Object.freeze({version:"1.0.0-web",storage:"localStorage"});
})();
