(()=>{"use strict";const te=new TextEncoder(),td=new TextDecoder();
function hex(b){return[...b].map(x=>x.toString(16).padStart(2,"0")).join("")}
function unhex(s){s=String(s||"").replace(/\\s+/g,"");if(s.length%2||!/^[0-9a-f]*$/i.test(s))throw new Error("Invalid hex.");return Uint8Array.from(s.match(/../g)||[],x=>parseInt(x,16))}
function b64(b){let s="";for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(s)}
function ub64(s){return Uint8Array.from(atob(String(s||"").replace(/\\s+/g,"")),c=>c.charCodeAt(0))}
function rot13(s){return String(s).replace(/[A-Za-z]/g,c=>String.fromCharCode((c<="Z"?65:97)+(c.charCodeAt(0)-(c<="Z"?65:97)+13)%26))}
function htmlEscape(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;")}
function htmlUnescape(s){const e=document.createElement("textarea");e.innerHTML=String(s);return e.value}
async function digest(s,a="SHA-256"){const d=await crypto.subtle.digest(a,te.encode(String(s)));return hex(new Uint8Array(d))}
async function gzip(s){if(!("CompressionStream" in window))throw new Error("CompressionStream unavailable.");const st=new Blob([te.encode(s)]).stream().pipeThrough(new CompressionStream("gzip"));return new Uint8Array(await new Response(st).arrayBuffer())}
async function gunzip(b){if(!("DecompressionStream" in window))throw new Error("DecompressionStream unavailable.");const st=new Blob([b]).stream().pipeThrough(new DecompressionStream("gzip"));return td.decode(await new Response(st).arrayBuffer())}
async function op(name,input,args={}){switch(name){case"toBase64":return b64(te.encode(input));case"fromBase64":return td.decode(ub64(input));case"toHex":return hex(te.encode(input));case"fromHex":return td.decode(unhex(input));case"urlEncode":return encodeURIComponent(input);case"urlDecode":return decodeURIComponent(input);case"rot13":return rot13(input);case"htmlEscape":return htmlEscape(input);case"htmlUnescape":return htmlUnescape(input);case"upper":return String(input).toUpperCase();case"lower":return String(input).toLowerCase();case"reverse":return [...String(input)].reverse().join("");case"jsonPretty":return JSON.stringify(JSON.parse(input),null,Number(args.indent||2));case"jsonMinify":return JSON.stringify(JSON.parse(input));case"sha1":return digest(input,"SHA-1");case"sha256":return digest(input,"SHA-256");case"sha384":return digest(input,"SHA-384");case"sha512":return digest(input,"SHA-512");case"gzipBase64":return b64(await gzip(input));case"gunzipBase64":return gunzip(ub64(input));default:throw new Error(`Unknown operation ${name}`)}}
function parseRecipe(text){const x=JSON.parse(text);if(!Array.isArray(x))throw new Error("Recipe must be a JSON array.");return x.map(s=>{if(!s||typeof s.op!=="string")throw new Error("Each recipe step requires op.");return{op:s.op,args:s.args||{}}})}
async function recipe(input,steps){let out=String(input),trace=[];for(const s of steps){const before=out,t0=performance.now();out=await op(s.op,out,s.args||{});trace.push({op:s.op,beforeBytes:te.encode(before).length,afterBytes:te.encode(out).length,elapsedMs:+(performance.now()-t0).toFixed(3)})}return{output:out,trace}}
function stats(text){const b=te.encode(String(text)),freq={};for(const x of b)freq[x]=(freq[x]||0)+1;let h=0;for(const n of Object.values(freq)){const p=n/b.length;h-=p*Math.log2(p)}return{characters:String(text).length,utf8Bytes:b.length,uniqueBytes:Object.keys(freq).length,shannonBitsPerByte:b.length?h:0}}
window.ChefCore=Object.freeze({te,td,hex,unhex,b64,ub64,rot13,digest,op,parseRecipe,recipe,stats})})();