(() => {
"use strict";
const $=id=>document.getElementById(id),state={source:OpticalCore.te.encode("BlinkeeQR optical encoding test."),name:"text.txt",frames:[],digest:null,timer:null,index:0};
function dl(t,n){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function build(){if($("qe-type").value==="text")state.source=OpticalCore.te.encode($("qe-text").value);const size=Math.max(32,Math.min(4096,+$("qe-size").value||256)),group=Math.max(2,Math.min(16,+$("qe-group").value||4));state.frames=OpticalCore.buildFrames(state.source,{chunkSize:size,groupSize:group});state.digest=await OpticalCore.sha256(state.source);state.index=0;$("qe-output").textContent=JSON.stringify({schema:"BQRES-alpha-1",sourceName:state.name,sourceBytes:state.source.length,sha256:state.digest,chunkSize:size,parityGroup:group,frames:state.frames.length},null,2);renderIndex();show(0);}
function packetBytes(f){const header=OpticalCore.te.encode(`BQ1|${f.index}|${f.total}|${f.kind}|${f.group}|${f.slot}|${f.length}|${f.crc32}|`);return OpticalCore.concat(header,OpticalCore.ub64(f.payload));}
function show(i){if(!state.frames.length)return;state.index=((i%state.frames.length)+state.frames.length)%state.frames.length;$("qp-frame").value=state.index;const f=state.frames[state.index];OpticalCore.drawFrame($("qp-canvas"),packetBytes(f),f);$("qp-output").textContent=JSON.stringify({...f,payload:`${f.payload.slice(0,64)}…`},null,2);}
function renderIndex(){const b=$("qf-body");b.replaceChildren();for(const f of state.frames){const tr=document.createElement("tr");[f.index,f.kind,f.group,f.slot,f.length,f.crc32.toString(16).padStart(8,"0")].forEach(x=>{const td=document.createElement("td");td.textContent=x;tr.appendChild(td);});b.appendChild(tr);}if(!state.frames.length)b.innerHTML='<tr><td colspan="6">No frames.</td></tr>';}
function toggle(){if(state.timer){clearInterval(state.timer);state.timer=null;$("qp-toggle").textContent="PLAY";}else{const fps=Math.max(1,Math.min(60,+$("qp-fps").value||6));state.timer=setInterval(()=>show(state.index+1),1000/fps);$("qp-toggle").textContent="STOP";}}
$("qe-file").addEventListener("change",async()=>{const f=$("qe-file").files?.[0];if(!f)return;state.source=new Uint8Array(await f.arrayBuffer());state.name=f.name;$("qe-type").value="binary";$("qe-output").textContent=`Loaded ${f.name} (${f.size} bytes).`;});
$("qe-build").addEventListener("click",()=>build().catch(e=>$("qe-output").textContent=`ERROR: ${e.message}`));$("qp-toggle").addEventListener("click",toggle);$("qp-frame").addEventListener("change",()=>show(+$("qp-frame").value||0));
$("qf-export").addEventListener("click",()=>{const x={schema:"zzx.bqres.sequence.v1",sourceName:state.name,sourceBytes:state.source.length,sha256:state.digest,chunkSize:+$("qe-size").value||256,parityGroup:+$("qe-group").value||4,frames:state.frames};dl(JSON.stringify(x,null,2),`bqres-${Date.now()}.json`);});
$("qr-run").addEventListener("click",async()=>{try{const drop=+$("qr-drop").value,frames=state.frames.filter(f=>f.index!==drop),bytes=OpticalCore.recover(frames,+$("qe-size").value||256).slice(0,state.source.length),hash=await OpticalCore.sha256(bytes);$("qr-output").textContent=JSON.stringify({droppedFrame:drop,recoveredBytes:bytes.length,sha256:hash,expectedSha256:state.digest,match:hash===state.digest,textPreview:$("qe-type").value==="text"?OpticalCore.td.decode(bytes).slice(0,500):null},null,2);}catch(e){$("qr-output").textContent=`ERROR: ${e.message}`;}});
build();
window.BlinkeeQR=Object.freeze({version:"0.1.0-alpha-web",buildFrames:OpticalCore.buildFrames,recover:OpticalCore.recover,crc32:OpticalCore.crc32,getSequence:()=>({frames:state.frames,sha256:state.digest})});
window.ZZXHooks?.emit("blinkeeqr:ready",{version:"0.1.0-alpha-web"});
})();
