(()=>{"use strict";const $=id=>document.getElementById(id);let rows=[],normalized=[];
const ranks=new Set(["domain","superkingdom","kingdom","subkingdom","infrakingdom","superphylum","phylum","subphylum","infraphylum","superclass","class","subclass","infraclass","superorder","order","suborder","infraorder","parvorder","superfamily","family","subfamily","tribe","subtribe","genus","subgenus","section","subsection","series","subseries","species","subspecies","variety","subvariety","form","subform","strain","cultivar","pathovar","serovar","biovar","isolate","hybrid","virus","clade","unranked"]);
function csv(text){const out=[];let row=[],v="",q=false;for(let i=0;i<text.length;i++){const c=text[i];if(q){if(c=='"'&&text[i+1]=='"'){v+='"';i++}else if(c=='"')q=false;else v+=c}else{if(c=='"')q=true;else if(c==","){row.push(v);v=""}else if(c=="\n"){row.push(v);out.push(row);row=[];v=""}else if(c!="\r")v+=c}}row.push(v);if(row.some(x=>x!==""))out.push(row);if(!out.length)return[];const h=out.shift().map(x=>x.trim());return out.map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]??""])))}
function canonical(name){return String(name||"").replace(/\s+/g," ").trim()}
function normalize(x,i){
 const scientific=canonical(x.scientific_name||x.scientificName||x.title||x.name),rank=canonical(x.rank||"unranked").toLowerCase(),pid=String(x.provider_id||x.page_id||x.pageid||x.id||i);
 return{provider:"wikispecies",provider_id:pid,scientific_name:scientific,canonical_name:canonical(x.canonical_name||x.canonicalName||scientific),rank:ranks.has(rank)?rank:"unranked",status:canonical(x.status||"accepted"),authorship:canonical(x.authorship||x.author||""),kingdom:canonical(x.kingdom),phylum:canonical(x.phylum),class_name:canonical(x.class_name||x.class),order:canonical(x.order),family:canonical(x.family),genus:canonical(x.genus),source_url:canonical(x.source_url||x.fullurl||x.url),source_modified:canonical(x.source_modified||x.timestamp),retrieved_at:canonical(x.retrieved_at||new Date().toISOString()),synonyms:Array.isArray(x.synonyms)?x.synonyms:[],extra:{source:"Wikispecies",reference_only:true,raw:x}}
}
function loadData(data){rows=Array.isArray(data)?data:(data.records||data.taxa||data.pages||[]);normalized=rows.map(normalize);render()}
$("file").onchange=async()=>{const f=$("file").files[0];if(!f)return;try{const t=await f.text();loadData(f.name.toLowerCase().endsWith(".csv")?csv(t):JSON.parse(t));$("status").textContent=`Loaded ${rows.length} record(s) from ${f.name}`}catch(e){$("status").textContent="IMPORT ERROR: "+e.message}$("file").value=""};
$("parse").onclick=()=>{try{loadData(JSON.parse($("paste").value));$("status").textContent=`Parsed ${rows.length} record(s)`}catch(e){$("status").textContent="PARSE ERROR: "+e.message}};
function render(){const q=$("search").value.trim().toLowerCase(),rank=$("rank").value;const list=normalized.filter(x=>(!q||JSON.stringify(x).toLowerCase().includes(q))&&(!rank||x.rank===rank));const e=$("rows");e.replaceChildren();list.slice(0,500).forEach(x=>{const d=document.createElement("div");d.className="ws-row";d.innerHTML=`<strong>${x.scientific_name||"(unnamed)"}</strong> <span class="rank">${x.rank}</span><div>${[x.kingdom,x.phylum,x.class_name,x.order,x.family,x.genus].filter(Boolean).join(" › ")}</div><div class="fx-watermark">provider_id ${x.provider_id}${x.source_url?` · ${x.source_url}`:""}</div>`;e.append(d)});$("raw-count").textContent=rows.length;$("norm-count").textContent=normalized.length;$("rank-count").textContent=new Set(normalized.map(x=>x.rank)).size;$("invalid").textContent=normalized.filter(x=>!x.scientific_name).length}
$("search").oninput=render;$("rank").oninput=render;
$("sample").onclick=()=>{loadData([{pageid:123,title:"Panthera leo",rank:"species",kingdom:"Animalia",phylum:"Chordata",class:"Mammalia",order:"Carnivora",family:"Felidae",genus:"Panthera",status:"accepted",fullurl:"https://species.wikimedia.org/wiki/Panthera_leo",timestamp:"2026-08-01T00:00:00Z"},{pageid:124,title:"Panthera tigris",rank:"species",kingdom:"Animalia",phylum:"Chordata",class:"Mammalia",order:"Carnivora",family:"Felidae",genus:"Panthera",status:"accepted"}])};
function dl(text,name,type="application/json"){const b=new Blob([text],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("export").onclick=()=>dl(JSON.stringify({schema:"speciedex.wikispecies.normalized.v1",exported:new Date().toISOString(),provider:"wikispecies",records:normalized},null,2),"wikispecies-normalized.json");
$("sync").onclick=()=>dl(JSON.stringify({schema:"speciedex.provider.sync-plan.v1",provider:"wikispecies",api_url:"https://species.wikimedia.org/w/api.php",site_url:"https://species.wikimedia.org/wiki/",batch_size:100,max_page_size:500,discovery:"generator=allpages",enrichment:"page-id chunks",continuation:"MediaWiki continue token",preserve_raw_payload:true,emit:"normalized Taxon objects",networkExecutedByBrowser:false},null,2),"wikispecies-sync-plan.json");
$("provider-info").onclick=()=>{$("provider-output").textContent=`Preserved provider source: provider/wikispecies.py\n\nCapabilities:\n- MediaWiki generator=allpages discovery\n- resumable continuation cursor\n- page-ID chunk enrichment\n- taxonomy rank normalization\n- title/prefix exclusions\n- source URL + revision timestamp provenance\n- raw page payload preservation in Taxon.extra.raw\n- normalized Taxon emission for reconciliation\n`};
$("sample").click();window.WikiSpeciesCore=Object.freeze({version:"0.2.0-alpha-web",preservedProvider:true});
})();
