(() => {
  "use strict";
  const $=id=>document.getElementById(id),state={escrow:null,milestones:[],arbitration:null,evidence:null,audit:[]};
  function log(type,data={}){state.audit.push({at:new Date().toISOString(),type,...data});}
  function dl(text,name){const b=new Blob([text],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  function escrow(){let m=Math.max(1,+$("es-m").value||2),n=Math.max(2,+$("es-n").value||3);if(m>n)m=n;state.escrow={id:$("es-id").value.trim(),threshold:{m,n},roles:[$("es-buyer").value,$("es-seller").value,$("es-arb").value],descriptorTemplate:`wsh(sortedmulti(${m},<buyer>,<seller>,<arbitrator>${n>3?",...":""}))`};log("escrow-build",{id:state.escrow.id});$("es-output").textContent=JSON.stringify(state.escrow,null,2);}
  function addMilestone(){const x={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),label:$("ms-label").value.trim(),amountSats:Math.max(1,+$("ms-sats").value||1),dueDate:$("ms-date").value,status:"pending"};state.milestones.push(x);log("milestone-add",{id:x.id});renderMilestones();}
  function renderMilestones(){const root=$("ms-list");root.replaceChildren();for(const x of state.milestones){const e=document.createElement("article");e.className="z-list-item";const h=document.createElement("strong");h.textContent=`${x.label} · ${x.amountSats.toLocaleString()} sats`;const p=document.createElement("p");p.textContent=`due ${x.dueDate||"unspecified"} · ${x.status}`;const r=document.createElement("div");r.className="button-row";r.style.justifyContent="flex-start";for(const st of ["pending","approved","disputed","released"]){const b=document.createElement("button");b.className="btn ghost";b.textContent=st.toUpperCase();b.addEventListener("click",()=>{x.status=st;log("milestone-status",{id:x.id,status:st});renderMilestones();});r.appendChild(b);}e.append(h,p,r);root.appendChild(e);}if(!state.milestones.length)root.innerHTML='<div class="z-list-item"><p>No milestones.</p></div>';}
  function saveArb(){state.arbitration={status:$("ar-status").value,reason:$("ar-reason").value.trim(),notes:$("ar-notes").value.trim(),updatedAt:new Date().toISOString()};log("arbitration",{status:state.arbitration.status});$("ar-output").textContent=JSON.stringify(state.arbitration,null,2);}
  async function buildEvidence(){const files=[];for(const f of [...$("ev-files").files]){const d=await crypto.subtle.digest("SHA-256",await f.arrayBuffer());files.push({name:f.name,size:f.size,sha256:[...new Uint8Array(d)].map(b=>b.toString(16).padStart(2,"0")).join("")});}state.evidence={escrowId:state.escrow?.id||$("es-id").value,narrative:$("ev-notes").value,files,createdAt:new Date().toISOString()};$("ev-output").textContent=JSON.stringify(state.evidence,null,2);return state.evidence;}
  function snapshot(){return{schema:"zzx.bitescrow.state.v1",exportedAt:new Date().toISOString(),escrow:state.escrow,milestones:state.milestones,arbitration:state.arbitration,evidence:state.evidence,audit:state.audit};}
  $("es-build").addEventListener("click",escrow);$("ms-add").addEventListener("click",addMilestone);$("ar-save").addEventListener("click",saveArb);$("ev-build").addEventListener("click",()=>buildEvidence().catch(e=>$("ev-output").textContent=`ERROR: ${e.message}`));$("ev-encrypt").addEventListener("click",async()=>{try{const pack=state.evidence||await buildEvidence(),env=await BitEscrowCore.encrypt(pack,$("ev-pass").value);dl(JSON.stringify(env,null,2),`bitescrow-evidence-${Date.now()}.encrypted.json`);$("ev-output").textContent=JSON.stringify({encrypted:true,...env,ciphertext:`${env.ciphertext.slice(0,48)}…`},null,2);}catch(e){$("ev-output").textContent=`ERROR: ${e.message}`;}});$("au-hash").addEventListener("click",async()=>{$("au-output").textContent=JSON.stringify({sha256:await BitEscrowCore.sha256Hex(JSON.stringify(snapshot())),state:snapshot()},null,2);});$("au-export").addEventListener("click",()=>dl(JSON.stringify(snapshot(),null,2),`bitescrow-${Date.now()}.json`));escrow();renderMilestones();saveArb();
  window.BitEscrow=Object.freeze({version:"0.1.0-alpha-web",getState:snapshot,encryptEvidence:BitEscrowCore.encrypt});
  window.ZZXHooks?.emit("bitescrow:ready",{version:"0.1.0-alpha-web"});
})();
