(()=>{"use strict";const $=id=>document.getElementById(id),state={project:null,provider:null};function dl(t,n){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}function cfg(){return{seed:$("seed").value.trim()||"0",name:$("name").value,archetype:$("archetype").value.trim(),age:$("age").value,setting:$("setting").value.trim(),framing:$("framing").value}}function style(){return{artStyle:$("art-style").value.trim(),palette:$("palette").value.trim(),lighting:$("lighting").value.trim(),camera:$("camera").value.trim(),environment:$("environment").value.trim(),modelId:$("model-id").value.trim(),negative:$("negative").value}}
async function build(){const c=CharacterRNGCore.base(cfg()),s=style(),fingerprint=await CharacterRNGCore.sha256(JSON.stringify({character:c,style:s})),job=CharacterRNGCore.prompt(c,s,CharacterRNGCore.h32(c.seed));state.project={schema:"zzx.character-rng.project.v1",version:"0.1.0-alpha",character:c,style:s,styleFingerprint:fingerprint,primaryJob:job,variations:[],createdAt:new Date().toISOString()};$("generator-output").textContent=JSON.stringify(state.project,null,2);$("style-output").textContent=JSON.stringify({style:s,fingerprint},null,2)}
$("build").onclick=()=>build().catch(e=>$("generator-output").textContent=`ERROR: ${e.message}`);
$("lock-style").onclick=async()=>{if(!state.project)await build();state.project.style=style();state.project.styleFingerprint=await CharacterRNGCore.sha256(JSON.stringify({character:state.project.character,style:state.project.style}));state.project.primaryJob=CharacterRNGCore.prompt(state.project.character,state.project.style,CharacterRNGCore.h32(state.project.character.seed));$("style-output").textContent=JSON.stringify({style:state.project.style,fingerprint:state.project.styleFingerprint},null,2)};
$("make-vars").onclick=async()=>{if(!state.project)await build();const n=Math.max(1,Math.min(16,+$("var-count").value||6));state.project.variations=[];for(let i=0;i<n;i++){const seed=CharacterRNGCore.h32(`${state.project.character.seed}|variation|${i}`);state.project.variations.push({...CharacterRNGCore.prompt(state.project.character,state.project.style,seed),variation:i})}const r=$("var-list");r.replaceChildren();for(const j of state.project.variations){const e=document.createElement("article");e.className="z-list-item";e.innerHTML="<strong></strong><p></p>";e.querySelector("strong").textContent=`Variation ${j.variation+1} · seed ${j.seed}`;e.querySelector("p").textContent=j.prompt;r.append(e)}};
$("generate-portrait").onclick=async()=>{try{if(!state.project)await build();if(!state.provider)throw new Error("No image provider registered.");const result=await state.provider(JSON.parse(JSON.stringify(state.project.primaryJob)));$("portrait-output").textContent=JSON.stringify(result,null,2);const root=$("portrait-result");root.replaceChildren();if(result?.url){const img=document.createElement("img");img.src=result.url;img.alt="Generated character portrait";img.style.maxWidth="100%";root.append(img)}}catch(e){$("portrait-output").textContent=`ERROR: ${e.message}`}};
$("export-project").onclick=()=>{if(state.project)dl(JSON.stringify(state.project,null,2),`character-rng-${state.project.character.name.replace(/[^\w.-]+/g,"_")}.json`)};
$("import-project").onchange=async()=>{const f=$("import-project").files?.[0];if(!f)return;try{state.project=JSON.parse(await f.text());$("generator-output").textContent=JSON.stringify(state.project,null,2);$("export-output").textContent=`Imported project for ${state.project.character?.name||"character"}.`}catch(e){$("export-output").textContent=`ERROR: ${e.message}`}$("import-project").value=""};
build();window.CharacterRNG=Object.freeze({version:"0.1.0-alpha-web",registerImageProvider(fn){state.provider=fn},getProject:()=>state.project,buildJob:CharacterRNGCore.prompt});window.ZZXHooks?.emit("character-rng:ready",{version:"0.1.0-alpha-web"})})();
