(() => {
"use strict";const $=id=>document.getElementById(id),state={rows:[],result:null};
function cfg(){return{kind:$("bs-kind").value,baseBuy:Math.max(1,+$("bs-base").value||100),trigger:Math.max(.1,+$("bs-trigger").value||5),period:Math.max(2,+$("bs-period").value||30),maxMultiplier:Math.max(1,+$("bs-mult").value||4),initialCash:Math.max(1,+$("bs-cash").value||25000)};}
function risk(){return{maxDeployPct:Math.max(.1,+$("rk-deploy").value||5),portfolioStopPct:Math.max(1,+$("rk-stop").value||30),maxVenuePct:Math.max(1,+$("rk-venue").value||50)};}
function dl(t,n,type){const b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function parse(text){const ls=text.trim().split(/\r?\n/),h=ls.shift().split(",").map(x=>x.trim().toLowerCase()),ci=h.indexOf("close"),ti=Math.max(h.indexOf("time"),h.indexOf("date"));if(ci<0)throw new Error("CSV requires close column.");return ls.map((l,i)=>{const c=l.split(",");return{time:ti>=0?c[ti]:String(i),close:+c[ci]};}).filter(x=>Number.isFinite(x.close));}
function sample(){let p=65000;state.rows=Array.from({length:500},(_,i)=>{const cyc=Math.sin(i/27)*.008,shock=(i%113===0?-0.08:0),drift=.0007;p=Math.max(1000,p*(1+drift+cyc+(Math.random()-.5)*.025+shock));return{time:new Date(Date.now()-(499-i)*86400000).toISOString().slice(0,10),close:p};});renderData();}
function renderData(){const r=state.rows;$("bb-bars").textContent=r.length;$("bb-start").textContent=r[0]?.close?`$${r[0].close.toFixed(0)}`:"—";$("bb-end").textContent=r.at(-1)?.close?`$${r.at(-1).close.toFixed(0)}`:"—";$("bb-data-dd").textContent=r.length?`${BlackBatCore.maxDrawdown(r.map(x=>x.close)).toFixed(2)}%`:"—";draw("bb-price-canvas",r.map(x=>x.close));}
function draw(id,v){const c=$(id),ctx=c.getContext("2d"),dpr=Math.max(1,Math.min(2,devicePixelRatio||1)),r=c.getBoundingClientRect(),w=Math.max(320,Math.round(r.width)),h=Math.max(260,Math.round(r.height||330));c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#050505";ctx.fillRect(0,0,w,h);if(v.length<2)return;const lo=Math.min(...v),hi=Math.max(...v),rg=hi-lo||1,pad=40;ctx.strokeStyle="#c0d674";ctx.lineWidth=2;ctx.beginPath();v.forEach((y,i)=>{const x=pad+(w-pad*2)*i/(v.length-1),py=h-30-(y-lo)/rg*(h-60);i?ctx.lineTo(x,py):ctx.moveTo(x,py);});ctx.stroke();}
function preview(){const s=BlackBatCore.signals(state.rows,cfg()),active=s.filter(x=>x.multiplier>0);$("bs-output").textContent=JSON.stringify({config:cfg(),bars:state.rows.length,activeBuyBars:active.length,maxMultiplierSeen:Math.max(0,...s.map(x=>x.multiplier)),maxMarketDrawdown:Math.max(0,...s.map(x=>x.drawdownPct))},null,2);}
function run(){state.result=BlackBatCore.backtest(state.rows,cfg(),risk());$("bt-btc").textContent=state.result.btcAccumulated.toFixed(8);$("bt-cash").textContent=`$${state.result.cashRemaining.toFixed(2)}`;$("bt-equity").textContent=`$${state.result.finalEquity.toFixed(2)}`;$("bt-dd").textContent=`${state.result.maxDrawdownPct.toFixed(2)}%`;$("bt-output").textContent=JSON.stringify({...state.result,equity:`${state.result.equity.length} rows`},null,2);draw("bt-canvas",state.result.equity.map(x=>x.equity));}
function venues(){const a=JSON.parse($("vn-json").value),enabled=a.filter(x=>x.enabled),sum=enabled.reduce((s,x)=>s+(+x.weight||0),0),max=Math.max(0,...enabled.map(x=>(+x.weight||0)*100)),limit=risk().maxVenuePct;$("vn-output").textContent=JSON.stringify({validWeights:Math.abs(sum-1)<1e-9,totalWeight:sum,maxEnabledVenuePct:max,withinConfiguredVenueLimit:max<=limit,configuredLimitPct:limit,venues:a},null,2);}
$("bb-file").addEventListener("change",async()=>{const f=$("bb-file").files?.[0];if(!f)return;try{state.rows=parse(await f.text());renderData();}catch(e){alert(e.message);}$("bb-file").value="";});$("bb-sample").addEventListener("click",sample);$("bs-preview").addEventListener("click",preview);for(const id of ["rk-deploy","rk-stop","rk-venue"])$(id).addEventListener("input",()=>{$("rk-output").textContent=JSON.stringify(risk(),null,2);});$("bt-run").addEventListener("click",()=>{try{run();}catch(e){$("bt-output").textContent=`ERROR: ${e.message}`;}});$("vn-check").addEventListener("click",()=>{try{venues();}catch(e){$("vn-output").textContent=`ERROR: ${e.message}`;}});$("bx-json").addEventListener("click",()=>{if(state.result)dl(JSON.stringify({schema:"zzx.blackbat.internal-backtest.v1",status:"INTERNAL – Not for public distribution.",result:state.result},null,2),`blackbat-internal-${Date.now()}.json`,"application/json");});$("bx-csv").addEventListener("click",()=>{if(state.result)dl("time,price,buy_usd,btc,cash,equity,stopped\n"+state.result.equity.map(x=>`${x.time},${x.price},${x.buyUsd},${x.btc},${x.cash},${x.equity},${x.stopped}`).join("\n")+"\n",`blackbat-equity-${Date.now()}.csv`,"text/csv");});sample();$("rk-output").textContent=JSON.stringify(risk(),null,2);
window.BlackBat=Object.freeze({version:"0.1.0-alpha-web",status:"INTERNAL – Not for public distribution.",signals:BlackBatCore.signals,backtest:BlackBatCore.backtest,getResult:()=>state.result});
window.ZZXHooks?.emit("blackbat:ready",{version:"0.1.0-alpha-web",internal:true});
})();
