(() => {
"use strict";
const $=id=>document.getElementById(id),state={hosts:[],tasks:[],status:[],audit:[]};
function dl(t,n){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function audit(type,data){await BlekRATCore.appendAudit(state.audit,{type,data});renderAudit();}
function renderHosts(){const root=$("rh-list"),sel=$("rt-host");root.replaceChildren();sel.replaceChildren();for(const h of state.hosts){const e=document.createElement("article");e.className="z-list-item";e.innerHTML="<strong></strong><p></p>";e.querySelector("strong").textContent=`${h.label} · ${h.platform}`;e.querySelector("p").textContent=`${h.hostRef} · ${h.environment} · authorized owner: ${h.owner}`;root.appendChild(e);const o=document.createElement("option");o.value=h.id;o.textContent=h.label;sel.appendChild(o);}if(!state.hosts.length)root.innerHTML='<div class="z-list-item"><p>No hosts in inventory.</p></div>';}
function renderTasks(){const root=$("rt-list");root.replaceChildren();for(const t of state.tasks){const e=document.createElement("article");e.className="z-list-item";e.innerHTML="<strong></strong><p></p>";e.querySelector("strong").textContent=`${t.actionLabel} · ${t.hostLabel}`;e.querySelector("p").textContent=`parameter: ${t.parameter||"none"} · status: planned only`;root.appendChild(e);}if(!state.tasks.length)root.innerHTML='<div class="z-list-item"><p>No task plans.</p></div>';}
function renderAudit(){$("ra-output").textContent=JSON.stringify(state.audit,null,2);}
$("rh-add").addEventListener("click",async()=>{const h={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),label:$("rh-label").value.trim(),hostRef:$("rh-host").value.trim(),platform:$("rh-os").value,environment:$("rh-env").value.trim(),owner:$("rh-owner").value.trim(),tags:$("rh-tags").value.split(",").map(x=>x.trim()).filter(Boolean)};state.hosts.push(h);await audit("host-added",{id:h.id,label:h.label,platform:h.platform,environment:h.environment});renderHosts();});
$("rt-plan").addEventListener("click",async()=>{const h=state.hosts.find(x=>x.id===$("rt-host").value);if(!h)return;const a=BlekRATCore.ACTIONS[$("rt-action").value],t={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),hostId:h.id,hostLabel:h.label,action:$("rt-action").value,actionLabel:a.label,purpose:a.purpose,parameter:$("rt-param").value.trim(),createdAt:new Date().toISOString(),execution:"not implemented in browser"};state.tasks.push(t);await audit("task-planned",{taskId:t.id,host:h.label,action:t.action,parameter:t.parameter});renderTasks();});
$("rs-import").addEventListener("click",async()=>{try{const j=JSON.parse($("rs-json").value),r={importedAt:new Date().toISOString(),telemetry:j};state.status.push(r);await audit("status-imported",{host:j.host||"unknown",fields:Object.keys(j)});$("rs-output").textContent=JSON.stringify(r,null,2);}catch(e){$("rs-output").textContent=`ERROR: ${e.message}`;}});
$("ra-verify").addEventListener("click",async()=>{$("ra-output").textContent=JSON.stringify({verification:await BlekRATCore.verify(state.audit),audit:state.audit},null,2);});
$("rx-json").addEventListener("click",()=>{const x={schema:"zzx.blekrat.browser-plan.v1",status:"INTERNAL – Not for public distribution.",exportedAt:new Date().toISOString(),hosts:state.hosts,tasks:state.tasks,statusImports:state.status,audit:state.audit};dl(JSON.stringify(x,null,2),`blekrat-internal-plan-${Date.now()}.json`);$("rx-output").textContent=JSON.stringify({...x,statusImports:`${state.status.length} item(s)`,audit:`${state.audit.length} item(s)`},null,2);});
renderHosts();renderTasks();renderAudit();
window.BlekRAT=Object.freeze({version:"0.1.0-alpha-web",status:"INTERNAL – Not for public distribution.",allowedActions:BlekRATCore.ACTIONS,verifyAudit:()=>BlekRATCore.verify(state.audit),getState:()=>JSON.parse(JSON.stringify(state))});
window.ZZXHooks?.emit("blekrat:ready",{version:"0.1.0-alpha-web",internal:true});
})();
