(()=>{"use strict";const $=id=>document.getElementById(id),c=$("canvas"),x=c.getContext("2d");let ctx=null,src=null,filter=null,gain=null,lfo=null,lfoGain=null,analyser=null,data=null,raf=null,presets=[];
function noiseBuffer(type,duration=3,sr=44100){const n=Math.floor(duration*sr),buf=new Float32Array(n);if(type==="white"){for(let i=0;i<n;i++)buf[i]=Math.random()*2-1}else if(type==="pink"){let b0=0,b1=0,b2=0,b3=0,b4=0,b5=0,b6=0;for(let i=0;i<n;i++){const w=Math.random()*2-1;b0=.99886*b0+w*.0555179;b1=.99332*b1+w*.0750759;b2=.969*b2+w*.153852;b3=.8665*b3+w*.3104856;b4=.55*b4+w*.5329522;b5=-.7616*b5-w*.016898;buf[i]=(b0+b1+b2+b3+b4+b5+b6+w*.5362)*.11;b6=w*.115926}}else{let last=0;for(let i=0;i<n;i++){const w=Math.random()*2-1;last=(last+.02*w)/1.02;buf[i]=last*3.5}}return buf}
function start(){stop();ctx=new (window.AudioContext||window.webkitAudioContext)();const raw=noiseBuffer($("noise").value,4,ctx.sampleRate),b=ctx.createBuffer(1,raw.length,ctx.sampleRate);b.copyToChannel(raw,0);src=ctx.createBufferSource();src.buffer=b;src.loop=true;filter=ctx.createBiquadFilter();gain=ctx.createGain();lfo=ctx.createOscillator();lfoGain=ctx.createGain();analyser=ctx.createAnalyser();data=new Uint8Array(analyser.frequencyBinCount);src.connect(filter).connect(gain).connect(analyser).connect(ctx.destination);lfo.connect(lfoGain).connect(gain.gain);src.start();lfo.start();apply();draw();$("state").textContent="PLAYING"}
function stop(){cancelAnimationFrame(raf);try{src?.stop();lfo?.stop();ctx?.close()}catch{}ctx=src=lfo=null;$("state").textContent="STOPPED"}
function apply(){if(!ctx)return;filter.type=$("filter").value;filter.frequency.value=+$("freq").value;filter.Q.value=+$("q").value;gain.gain.value=+$("volume").value;lfo.type=$("lfo-shape").value;lfo.frequency.value=+$("lfo-rate").value;lfoGain.gain.value=+$("lfo-depth").value}
["filter","freq","q","volume","lfo-shape","lfo-rate","lfo-depth"].forEach(id=>$(id).oninput=apply);$("start").onclick=start;$("stop").onclick=stop;
function draw(){if(!analyser)return;analyser.getByteFrequencyData(data);const w=c.width,h=c.height;x.fillStyle="#040404";x.fillRect(0,0,w,h);const n=120,bw=w/n;x.fillStyle="#c0d674";for(let i=0;i<n;i++){const v=data[Math.floor(i*data.length/n)]/255,bh=v*(h-20);x.fillRect(i*bw,h-bh,bw*.7,bh)}raf=requestAnimationFrame(draw)}
function savePreset(){presets.push({name:$("preset-name").value.trim()||`Preset ${presets.length+1}`,noise:$("noise").value,filter:$("filter").value,freq:+$("freq").value,q:+$("q").value,volume:+$("volume").value,lfoShape:$("lfo-shape").value,lfoRate:+$("lfo-rate").value,lfoDepth:+$("lfo-depth").value});renderPresets()}
function renderPresets(){const e=$("presets");e.replaceChildren();presets.forEach((p,i)=>{const d=document.createElement("div");d.className="preset-row";d.innerHTML=`<strong>${p.name}</strong> · ${p.noise} · ${p.filter} ${p.freq}Hz · LFO ${p.lfoRate}Hz <button class="btn ghost" data-i="${i}">LOAD</button>`;e.append(d)});e.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>{const p=presets[+b.dataset.i];$("noise").value=p.noise;$("filter").value=p.filter;$("freq").value=p.freq;$("q").value=p.q;$("volume").value=p.volume;$("lfo-shape").value=p.lfoShape;$("lfo-rate").value=p.lfoRate;$("lfo-depth").value=p.lfoDepth;apply()})}
$("save-preset").onclick=savePreset;
$("midi").onclick=async()=>{if(!navigator.requestMIDIAccess){$("midi-status").textContent="Web MIDI unavailable.";return}try{const a=await navigator.requestMIDIAccess();$("midi-status").textContent=`MIDI inputs: ${a.inputs.size}`;for(const input of a.inputs.values())input.onmidimessage=e=>{const [st,d1,d2]=e.data;if((st&0xF0)===0xB0){if(d1===1)$("freq").value=100+Math.round(d2/127*11900);if(d1===2)$("volume").value=(d2/127*.8).toFixed(2);apply()}}}catch(e){$("midi-status").textContent="MIDI ERROR: "+e.message}};
function wav(samples,sr){const b=new ArrayBuffer(44+samples.length*2),v=new DataView(b);const str=(o,s)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));str(0,"RIFF");v.setUint32(4,36+samples.length*2,true);str(8,"WAVE");str(12,"fmt ");v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,sr,true);v.setUint32(28,sr*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,"data");v.setUint32(40,samples.length*2,true);for(let i=0;i<samples.length;i++)v.setInt16(44+i*2,Math.max(-1,Math.min(1,samples[i]))*32767,true);return b}
$("wav").onclick=()=>{const sec=Math.max(1,Math.min(60,+$("wav-sec").value||10)),sr=44100,s=noiseBuffer($("noise").value,sec,sr),b=new Blob([wav(s,sr)],{type:"audio/wav"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=`woise-${$("noise").value}-${sec}s.wav`;a.click();setTimeout(()=>URL.revokeObjectURL(u),1500)};
$("export").onclick=()=>{const t=JSON.stringify({schema:"zzx.woise.presets.v1",exported:new Date().toISOString(),presets},null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="woise-presets.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
presets=[{name:"Soft Pink",noise:"pink",filter:"lowpass",freq:4600,q:.7,volume:.18,lfoShape:"sine",lfoRate:.08,lfoDepth:.02},{name:"Brown Focus",noise:"brown",filter:"lowpass",freq:2200,q:.8,volume:.2,lfoShape:"sine",lfoRate:.05,lfoDepth:.01}];renderPresets();window.Woise=Object.freeze({version:"0.3.0-alpha-web"});
})();
