(()=>{"use strict";const $=id=>document.getElementById(id);function hash(s){let h=2166136261>>>0;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}function rng(seed){let x=hash(seed)||1;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function params(){return{width:Math.max(256,Math.min(4096,+$("width").value||1200)),height:Math.max(256,Math.min(4096,+$("height").value||1600)),seed:$("seed").value,mode:$("mode").value,symmetry:Math.max(3,+$("symmetry").value||8),density:Math.max(2,+$("density").value||10),lineWidth:Math.max(.5,+$("line-width").value||3),scale:+$("scale").value||1,rotation:+$("rotation").value||0,headline:$("headline").value,subhead:$("subhead").value,headlineSize:+$("headline-size").value||92,margin:+$("margin").value||72}}
function tess(x,p,r){const w=p.width,h=p.height,step=Math.max(30,Math.min(w,h)/(p.density*.65));x.save();x.translate(w/2,h/2);x.rotate(p.rotation*Math.PI/180);x.scale(p.scale,p.scale);x.strokeStyle="#c0d674";x.lineWidth=p.lineWidth;for(let yy=-h;yy<h;yy+=step){for(let xx=-w;xx<w;xx+=step){const rr=step*(.25+r()*.28),sides=3+Math.floor(r()*6);x.beginPath();for(let i=0;i<=sides;i++){const a=i/sides*Math.PI*2+(r()-.5)*.15,px=xx+Math.cos(a)*rr,py=yy+Math.sin(a)*rr;i?x.lineTo(px,py):x.moveTo(px,py)}x.stroke()}}x.restore()}
function radial(x,p,r){const w=p.width,h=p.height,cx=w/2,cy=h/2,R=Math.min(w,h)*.42*p.scale;x.save();x.translate(cx,cy);x.rotate(p.rotation*Math.PI/180);x.strokeStyle="#e6a42b";x.lineWidth=p.lineWidth;for(let ring=1;ring<=p.density;ring++){const rr=R*ring/p.density;x.beginPath();for(let i=0;i<=p.symmetry;i++){const a=i/p.symmetry*Math.PI*2,mod=1+.14*Math.sin(i*3+ring*.8),px=Math.cos(a)*rr*mod,py=Math.sin(a)*rr*mod;i?x.lineTo(px,py):x.moveTo(px,py)}x.closePath();x.stroke()}x.restore()}
function branch(x,x0,y0,len,a,d,r,p){if(d<=0)return;const x1=x0+Math.cos(a)*len,y1=y0+Math.sin(a)*len;x.beginPath();x.moveTo(x0,y0);x.lineTo(x1,y1);x.stroke();const spread=.35+r()*.45,shrink=.62+r()*.1;branch(x,x1,y1,len*shrink,a-spread,d-1,r,p);branch(x,x1,y1,len*shrink,a+spread,d-1,r,p)}
function fractal(x,p,r){x.save();x.strokeStyle="#c0d674";x.globalAlpha=.72;x.lineWidth=Math.max(1,p.lineWidth*.7);for(let i=0;i<p.symmetry;i++){const a=i/p.symmetry*Math.PI*2+p.rotation*Math.PI/180;branch(x,p.width/2,p.height/2,Math.min(p.width,p.height)*.16*p.scale,a,Math.min(8,3+Math.floor(p.density/3)),r,p)}x.restore()}
function drawText(x,p){x.save();x.fillStyle="#121212";x.fillRect(p.margin,p.height-p.margin-p.headlineSize*1.75,p.width-p.margin*2,p.headlineSize*1.6);x.fillStyle="#e8e8e8";x.font=`700 ${p.headlineSize}px "IBM Plex Mono", monospace`;x.textBaseline="top";x.fillText(p.headline,p.margin,p.height-p.margin-p.headlineSize*1.55,p.width-p.margin*2);x.fillStyle="#c0d674";x.font=`500 ${Math.max(18,p.headlineSize*.28)}px "IBM Plex Mono", monospace`;x.fillText(p.subhead,p.margin,p.height-p.margin-p.headlineSize*.45,p.width-p.margin*2);x.restore()}
function render(){const p=params(),c=$("poster");c.width=p.width;c.height=p.height;const x=c.getContext("2d"),r=rng(p.seed);x.fillStyle="#121212";x.fillRect(0,0,p.width,p.height);x.strokeStyle="#343434";x.lineWidth=1;for(let i=0;i<70;i++){x.beginPath();x.moveTo(r()*p.width,r()*p.height);x.lineTo(r()*p.width,r()*p.height);x.globalAlpha=.08;x.stroke()}x.globalAlpha=1;if(p.mode==="tessellation")tess(x,p,r);else if(p.mode==="radial")radial(x,p,r);else if(p.mode==="fractal")fractal(x,p,r);else{tess(x,p,r);radial(x,p,r);fractal(x,p,r)}drawText(x,p);return p}
$("render").onclick=render;$("randomize").onclick=()=>{$("seed").value=crypto.getRandomValues(new Uint32Array(2)).join("-");render()};
document.querySelectorAll(".preset").forEach(b=>b.onclick=()=>{const p={poster:{w:1200,h:1600,m:"hybrid",s:8,d:10},square:{w:1400,h:1400,m:"radial",s:12,d:12},story:{w:1080,h:1920,m:"fractal",s:10,d:14},dense:{w:1200,h:1600,m:"tessellation",s:8,d:22}}[b.dataset.p];$("width").value=p.w;$("height").value=p.h;$("mode").value=p.m;$("symmetry").value=p.s;$("density").value=p.d;$("preset-output").textContent=JSON.stringify(p,null,2);render()});
$("png").onclick=()=>{render();const a=document.createElement("a");a.download="flyr-design.png";a.href=$("poster").toDataURL("image/png");a.click()};
function dl(t,n){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("json").onclick=()=>{const t=JSON.stringify({schema:"zzx.flyr.design.v1",parameters:render()},null,2);dl(t,"flyr-design.json");$("export-output").textContent=t};render();window.flyr=Object.freeze({version:"0.1.0-alpha-web",render,params});window.ZZXHooks?.emit("flyr:ready",{version:"0.1.0-alpha-web"})})();
