(()=>{"use strict";const $=id=>document.getElementById(id),S=SpeciedexShared;let records=[],selected=[];
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function sample(){records=[
S.normalize({scientificName:"Balaenoptera musculus",commonName:"Blue whale",kingdom:"Animalia",phylum:"Chordata",class:"Mammalia",order:"Artiodactyla",family:"Balaenopteridae",genus:"Balaenoptera",status:"Endangered",habitat:"Marine",region:"Global oceans",source:"synthetic-demo"}),
S.normalize({scientificName:"Panthera tigris",commonName:"Tiger",kingdom:"Animalia",phylum:"Chordata",class:"Mammalia",order:"Carnivora",family:"Felidae",genus:"Panthera",status:"Endangered",habitat:"Forest / grassland",region:"Asia",source:"synthetic-demo"}),
S.normalize({scientificName:"Quercus alba",commonName:"White oak",kingdom:"Plantae",phylum:"Tracheophyta",class:"Magnoliopsida",order:"Fagales",family:"Fagaceae",genus:"Quercus",status:"Least Concern",habitat:"Temperate forest",region:"Eastern North America",source:"synthetic-demo"})
];render()}
$("sample").onclick=sample;$("dataset").onchange=async()=>{const f=$("dataset").files[0];if(!f)return;try{const j=JSON.parse(await f.text()),arr=Array.isArray(j)?j:(j.records||[]);records=arr.map(S.normalize).filter(r=>!S.rejectHuman(r));render()}catch(e){$("status").textContent="IMPORT ERROR: "+e.message}$("dataset").value=""};
function render(){const q=$("search").value.trim().toLowerCase(),rank=$("rank").value,val=$("rank-value").value.trim().toLowerCase(),list=records.filter(r=>(!q||JSON.stringify(r).toLowerCase().includes(q))&&(!rank||!val||String(r[rank]||"").toLowerCase().includes(val)));const e=$("records");e.replaceChildren();list.forEach(r=>{const d=document.createElement("div");d.className="web-record";d.innerHTML=`<strong>${esc(r.scientificName)}</strong> · ${esc(r.commonName)}<div class="fx-watermark">${esc(r.family)} · ${esc(r.status)} · ${esc(r.region)}</div><button class="btn ghost" data-id="${r.id}">COMPARE</button>`;e.append(d)});e.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>{const r=records.find(x=>x.id===b.dataset.id);selected=[...selected.filter(x=>x.id!==r.id),r].slice(-2);compare()});$("count").textContent=records.length;$("visible").textContent=list.length;$("kingdoms").textContent=new Set(records.map(r=>r.kingdom)).size;$("selected").textContent=selected.length}
function compare(){const e=$("compare");e.replaceChildren();selected.forEach(r=>{const d=document.createElement("div");d.className="fx-card";d.innerHTML=`<h3>${esc(r.scientificName)}</h3><p>${esc(r.commonName)}</p><pre class="z-log">${esc(JSON.stringify(r,null,2))}</pre>`;e.append(d)});$("selected").textContent=selected.length}
$("search").oninput=render;$("rank").onchange=render;$("rank-value").oninput=render;
$("export-selection").onclick=()=>S.download(JSON.stringify({schema:"zzx.speciedexweb.selection.v1",records:selected},null,2),"speciedexweb-selection.json");
$("export-all").onclick=()=>S.download(JSON.stringify({schema:"zzx.speciedex.dataset.v1",records},null,2),"speciedexweb-open-data.json");
sample();window.SpeciedexWeb=Object.freeze({version:"0.1.0-alpha-web",liveApi:false});
})();
