(()=>{"use strict";const $=id=>document.getElementById(id),enc=new TextEncoder(),dec=new TextDecoder();let encrypted=null,profile=null;
const ALPH58="123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz";
function b32(bytes){const A="ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";let bits=0,val=0,out="";for(const b of bytes){val=(val<<8)|b;bits+=8;while(bits>=5){out+=A[(val>>>(bits-5))&31];bits-=5}}if(bits)out+=A[(val<<(5-bits))&31];return out}
function b58(bytes){let x=0n;for(const b of bytes)x=(x<<8n)|BigInt(b);let out="";while(x>0n){const r=Number(x%58n);out=ALPH58[r]+out;x/=58n}for(const b of bytes){if(b===0)out="1"+out;else break}return out||"1"}
const hex=b=>[...b].map(x=>x.toString(16).padStart(2,"0")).join("");
const unhex=s=>new Uint8Array((s.match(/../g)||[]).map(x=>parseInt(x,16)));
async function derive(pass,salt,usages){const base=await crypto.subtle.importKey("raw",enc.encode(pass),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:250000,hash:"SHA-256"},base,{name:"AES-GCM",length:256},false,usages)}
$("profile").onclick=()=>{const rnd=crypto.getRandomValues(new Uint8Array(24));profile={schema:"zzx.0gp.profile.v1",name:$("name").value.trim()||"identity",profileId:b32(rnd.slice(0,10)),fingerprint58:b58(rnd),encoding:$("encoding").value,created:new Date().toISOString(),privateKeyIncluded:false,notes:$("notes").value.trim()};$("profile-out").textContent=JSON.stringify(profile,null,2)};
$("encode").onclick=()=>{const bytes=enc.encode($("plain-encode").value),mode=$("encoding").value;$("encoded").textContent=mode==="base32"?b32(bytes):b58(bytes)};
$("encrypt").onclick=async()=>{const pass=$("pass").value;if(pass.length<10){$("crypto-status").textContent="Use a local passphrase of at least 10 characters.";return}const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),key=await derive(pass,salt,["encrypt"]),ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},key,enc.encode($("message").value)));encrypted={schema:"zzx.0gp.envelope.v1",cipher:"AES-256-GCM",kdf:"PBKDF2-SHA256",iterations:250000,salt:hex(salt),iv:hex(iv),ciphertext:hex(ct),created:new Date().toISOString()};$("envelope").textContent=JSON.stringify(encrypted,null,2);$("crypto-status").textContent="Encrypted locally."};
$("decrypt").onclick=async()=>{try{const e=encrypted||JSON.parse($("envelope").textContent),key=await derive($("pass").value,unhex(e.salt),["decrypt"]),pt=await crypto.subtle.decrypt({name:"AES-GCM",iv:unhex(e.iv)},key,unhex(e.ciphertext));$("decrypted").textContent=dec.decode(pt)}catch(err){$("decrypted").textContent="DECRYPT ERROR: "+err.message}};
$("digest").onclick=async()=>{const d=new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode($("message").value)));$("digest-out").textContent=`SHA-256 ${hex(d)}\nBase32 ${b32(d)}\nBase58 ${b58(d)}`};
function dl(text,name){const b=new Blob([text],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("export-profile").onclick=()=>{if(!profile)$("profile").click();dl(JSON.stringify(profile,null,2),"zzx0gp-profile.json")};$("export-envelope").onclick=()=>{if(encrypted)dl(JSON.stringify(encrypted,null,2),"zzx0gp-envelope.json")};
window.ZZX0GP=Object.freeze({version:"0.3.0-alpha-web",cipher:"AES-256-GCM",existingSecretsRequested:false});
})();
