#!/usr/bin/env python3
from pathlib import Path
ROOT=Path(__file__).resolve().parent
PARTS=[
    "js/sources.js",
    "js/fetch.js",
    "js/analyzer.js",
    "js/provider.js",
    "js/live.js",
    "js/model.js",
    "js/sorter.js",
    "js/mosaic-packer.js",
    "js/layout.js",
    "js/animation.js",
    "js/renderer.js",
    "js/txfetcher.js",
    "js/reader-store.js",
    "js/inspector.js",
    "js/controller.js",
]
banner="""/*\n * Mempool Mosaic — production bundle\n * ZZX-Labs / 0xdeadbeef\n * Generated by build.py. Source modules remain under js/.\n */\n\n"""
body=banner+"\n\n".join((ROOT/part).read_text(encoding="utf-8") for part in PARTS)+"\n"
(ROOT/"widget.js").write_text(body,encoding="utf-8")
print(f"built widget.js: {len(body.encode('utf-8')):,} bytes")
