(()=>{"use strict";const $=id=>document.getElementById(id),te=new TextEncoder(),td=new TextDecoder();const b64=b=>{let s="";for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(s)},ub64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
function phaseEncode(bytes,phase,interval,salt){const out=[];let si=0;for(let i=0;i<bytes.length;i++){out.push((bytes[i]+phase+i)%256);if(interval>0&&(i+1)%interval===0){out.push(salt[si++%salt.length])}}return new Uint8Array(out)}
function phaseDecode(bytes,phase,interval,plainLength){const out=[];let j=0;for(let i=0;i<plainLength;i++){out.push((bytes[j]-phase-i+512)%256);j++;if(interval>0&&(i+1)%interval===0)j++}return new Uint8Array(out)}
async function key(pass,salt,it=310000){const b=await crypto.subtle.importKey("raw",te.encode(pass),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",hash:"SHA-256",salt,iterations:it},b,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
async function build(text,phase,interval,pass){const plain=te.encode(text),salt=crypto.getRandomValues(new Uint8Array(16)),layer=phaseEncode(plain,phase,interval,salt),base={schema:"zzx.fcpc.v1",phase,interval,plainLength:plain.length,nullSalt:b64(salt),layer:b64(layer),security:"phase/null layer is obfuscation only"};if(!pass)return{...base,wrapper:"none"};const kdfSalt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(pass,kdfSalt),ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},k,te.encode(JSON.stringify(base))));return{schema:"zzx.fcpc.aesgcm.v1",wrapper:"AES-256-GCM",kdf:{name:"PBKDF2",hash:"SHA-256",iterations:310000,salt:b64(kdfSalt)},iv:b64(iv),ciphertext:b64(ct)}}
async function unwrap(doc,pass){if(doc.wrapper==="AES-256-GCM"||doc.schema==="zzx.fcpc.aesgcm.v1"){if(!pass)throw new Error("Passphrase required.");const k=await key(pass,ub64(doc.kdf.salt),doc.kdf.iterations),p=await crypto.subtle.decrypt({name:"AES-GCM",iv:ub64(doc.iv)},k,ub64(doc.ciphertext));doc=JSON.parse(td.decode(p))}const bytes=phaseDecode(ub64(doc.layer),doc.phase,doc.interval,doc.plainLength);return td.decode(bytes)}
$("encode").onclick=async()=>{try{const d=await build($("plain").value,Math.max(0,Math.min(255,+$("phase").value||0)),Math.max(0,+$("null-every").value||0),$("pass").value);const t=JSON.stringify(d,null,2);$("encoded").value=t;$("decode-input").value=t;$("decode-pass").value=$("pass").value}catch(e){$("encoded").value="ERROR: "+e.message}};
$("decode").onclick=async()=>{try{$("decoded").value=await unwrap(JSON.parse($("decode-input").value),$("decode-pass").value)}catch(e){$("decoded").value="ERROR: "+e.message}};
$("gpg-command").onclick=()=>{const r=$("recipient").value.trim()||"RECIPIENT_FINGERPRINT",f=$("filename").value.trim()||"fcpc-envelope.json";$("gpg-output").value=`# Native GPG wrap after generating the FCPC envelope\n\ngpg --encrypt --armor --recipient "${r.replaceAll('"','\\"')}" --output "${f}.asc" "${f}"\n\n# Decrypt later\ngpg --decrypt --output "${f}.decrypted" "${f}.asc"`};
$("run-vector").onclick=async()=>{const text="FCPC vector 123 !",d=await build(text,37,3,""),back=await unwrap(d,"");$("vector-output").textContent=JSON.stringify({input:text,decoded:back,pass:back===text,envelope:d},null,2)};
window.FCPC=Object.freeze({version:"0.1.0-alpha-web",phaseEncode,phaseDecode,build,unwrap});window.ZZXHooks?.emit("fcpc:ready",{version:"0.1.0-alpha-web"})})();
