(()=>{"use strict";const $=id=>document.getElementById(id);const logs=[],checks=[];let timer={running:false,kind:"work",remaining:20*60*1000,last:0,raf:0,cycles:0};
const fmt=ms=>{const s=Math.max(0,Math.ceil(ms/1000));return`${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`};
function log(type,detail={}){logs.unshift({at:new Date().toISOString(),type,...detail});renderLogs()}
function notify(title,body){if(!$("notify").checked)return;if(Notification.permission==="granted")new Notification(title,{body});else if(Notification.permission!=="denied")Notification.requestPermission().then(p=>{if(p==="granted")new Notification(title,{body})})}
function tick(now){if(!timer.running)return;if(!timer.last)timer.last=now;timer.remaining-=now-timer.last;timer.last=now;renderTimer();if(timer.remaining<=0){timer.running=false;cancelAnimationFrame(timer.raf);if(timer.kind==="work"){log("break_due",{cycle:timer.cycles+1});notify("EyeBreaker","Screen break due.");beginBreak()}else{completeBreak(true)}return}timer.raf=requestAnimationFrame(tick)}
function renderTimer(){$("remaining").textContent=fmt(timer.remaining);$("state").textContent=timer.running?(timer.kind==="work"?"WORKING":"BREAK"):timer.kind==="work"?"READY / PAUSED":"BREAK PAUSED";$("cycles").textContent=timer.cycles;if(timer.kind==="break")$("break-remaining").textContent=fmt(timer.remaining)}
$("start").onclick=()=>{if(timer.kind!=="work"||timer.remaining<=0)timer.remaining=Math.max(60000,+$("work-minutes").value*60000);timer.kind="work";timer.running=true;timer.last=0;log("work_started",{minutes:+$("work-minutes").value});timer.raf=requestAnimationFrame(tick)};
$("pause").onclick=()=>{timer.running=false;cancelAnimationFrame(timer.raf);log("timer_paused",{kind:timer.kind,remainingMs:timer.remaining});renderTimer()};
$("reset").onclick=()=>{timer.running=false;cancelAnimationFrame(timer.raf);timer.kind="work";timer.remaining=Math.max(60000,+$("work-minutes").value*60000);timer.last=0;log("timer_reset");renderTimer()};
function beginBreak(){timer.running=false;cancelAnimationFrame(timer.raf);timer.kind="break";const longEvery=Math.max(1,+$("long-every").value||4),isLong=(timer.cycles+1)%longEvery===0;timer.remaining=(isLong?Math.max(60,+$("break-seconds").value*5):Math.max(10,+$("break-seconds").value))*1000;timer.last=0;timer.running=true;$("break-title").textContent=isLong?"Long eye break":"Eye break";$("break-instruction").textContent="Look away from the screen, blink naturally, relax your focus, and change posture if comfortable.";log("break_started",{long:isLong,durationSeconds:timer.remaining/1000});timer.raf=requestAnimationFrame(tick)}
function completeBreak(auto=false){if(timer.kind!=="break")return;timer.running=false;cancelAnimationFrame(timer.raf);timer.cycles++;log("break_completed",{automatic:auto});timer.kind="work";timer.remaining=Math.max(60000,+$("work-minutes").value*60000);timer.last=0;$("break-title").textContent="Break complete";$("break-remaining").textContent="—";renderTimer()}
$("begin-break").onclick=beginBreak;$("complete-break").onclick=()=>completeBreak(false);$("skip-break").onclick=()=>{if(timer.kind==="break"){timer.running=false;cancelAnimationFrame(timer.raf);log("break_skipped",{remainingMs:timer.remaining});timer.kind="work";timer.remaining=Math.max(60000,+$("work-minutes").value*60000);timer.last=0;renderTimer()}};
function draw(){const c=$("fatigue-chart"),x=c.getContext("2d"),w=c.width,h=c.height;x.clearRect(0,0,w,h);if(!checks.length)return;for(const [key,col] of [["eye","#c0d674"],["focus","#e6a42b"]]){x.beginPath();checks.forEach((p,i)=>{const px=30+i/(checks.length-1||1)*(w-60),py=h-30-p[key]/10*(h-60);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle=col;x.lineWidth=2;x.stroke()}}
function stats(){const mean=k=>checks.length?checks.reduce((s,p)=>s+p[k],0)/checks.length:null;const e=mean("eye"),f=mean("focus");$("mean-eye").textContent=e===null?"—":e.toFixed(2);$("mean-focus").textContent=f===null?"—":f.toFixed(2);$("checkins").textContent=checks.length;draw()}
$("record-fatigue").onclick=()=>{checks.push({at:new Date().toISOString(),eye:+$("eye-fatigue").value,headache:+$("headache").value,focus:+$("focus-fatigue").value,note:$("fatigue-note").value.trim()});log("fatigue_checkin",{eye:+$("eye-fatigue").value,headache:+$("headache").value,focus:+$("focus-fatigue").value});$("fatigue-note").value="";stats()};
function renderLogs(){const e=$("log-list");e.replaceChildren();logs.forEach(x=>{const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${x.type}</strong><p>${new Date(x.at).toLocaleString()}</p><pre>${JSON.stringify(x,null,2)}</pre>`;e.append(a)})}
function dl(t,n,type){const b=new Blob([t],{type}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("export-json").onclick=()=>{const t=JSON.stringify({schema:"zzx.eyebreaker.v1",exported:new Date().toISOString(),settings:{workMinutes:+$("work-minutes").value,breakSeconds:+$("break-seconds").value,longEvery:+$("long-every").value},logs,checkins:checks},null,2);dl(t,"eyebreaker-log.json","application/json");$("export-output").textContent=t};
$("export-csv").onclick=()=>{const t="timestamp,eye,headache,focus,note\n"+checks.map(x=>[x.at,x.eye,x.headache,x.focus,JSON.stringify(x.note)].join(",")).join("\n");dl(t,"eyebreaker-fatigue.csv","text/csv");$("export-output").textContent=t};
timer.remaining=+$("work-minutes").value*60000;renderTimer();stats();window.EyeBreaker=Object.freeze({version:"1.0.0-web",getLogs:()=>logs.slice(),getCheckins:()=>checks.slice()});window.ZZXHooks?.emit("eyebreaker:ready",{version:"1.0.0-web"})})();
