(()=>{"use strict";
function month(d,n){const x=new Date(d),day=x.getDate();x.setDate(1);x.setMonth(x.getMonth()+n);x.setDate(Math.min(day,new Date(x.getFullYear(),x.getMonth()+1,0).getDate()));return x}
function year(d,n){const x=new Date(d),m=x.getMonth(),day=x.getDate();x.setFullYear(x.getFullYear()+n,0,1);x.setMonth(m);x.setDate(Math.min(day,new Date(x.getFullYear(),m+1,0).getDate()));return x}
function expand(e,from,to){const out=[],base=new Date(e.start),count=Math.max(1,+e.count||1);for(let i=0;i<count;i++){let d;if(e.repeat==="daily")d=new Date(base.getTime()+i*86400000);else if(e.repeat==="weekly")d=new Date(base.getTime()+i*604800000);else if(e.repeat==="monthly")d=month(base,i);else if(e.repeat==="yearly")d=year(base,i);else d=new Date(base);const t=d.getTime();if(t>=from&&t<=to)out.push({...e,occurrence:i,start:d.toISOString(),end:new Date(t+(+e.durationMinutes||60)*60000).toISOString()});if(e.repeat==="none")break}return out}
function all(events,from,to){return events.flatMap(e=>expand(e,from,to)).sort((a,b)=>new Date(a.start)-new Date(b.start))}
const esc=s=>String(s??"").replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;");
const dt=s=>new Date(s).toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"Z");
function ics(events){const l=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//ZZX-Labs//CalSched//EN"];for(const e of events){l.push("BEGIN:VEVENT",`UID:${e.id}@calsched.zzx`,`DTSTAMP:${dt(new Date().toISOString())}`,`DTSTART:${dt(e.start)}`,`DTEND:${dt(new Date(new Date(e.start).getTime()+(+e.durationMinutes||60)*60000))}`,`SUMMARY:${esc(e.title)}`,`DESCRIPTION:${esc(e.notes||"")}`);if(e.repeat&&e.repeat!=="none")l.push(`RRULE:FREQ=${{daily:"DAILY",weekly:"WEEKLY",monthly:"MONTHLY",yearly:"YEARLY"}[e.repeat]};COUNT=${Math.max(1,+e.count||1)}`);if(+e.reminderMinutes>0)l.push("BEGIN:VALARM",`TRIGGER:-PT${Math.floor(+e.reminderMinutes)}M`,"ACTION:DISPLAY",`DESCRIPTION:${esc(e.title)}`,"END:VALARM");l.push("END:VEVENT")}l.push("END:VCALENDAR");return l.join("\r\n")+"\r\n"}
window.CalSchedCore=Object.freeze({expand,all,ics})})();
