(() => {
"use strict";
const $=id=>document.getElementById(id);
const state={server:null,commitment:null,bankroll:{start:100000,balance:100000,rounds:0},lastProof:null,reserve:null,settlement:null,settlementProvider:null};
function dl(t,n){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
function bankrollRender(){const b=state.bankroll,maxPct=Math.max(.1,+$("cb-maxstake").value||1);$("cb-balance").textContent=b.balance.toFixed(2);$("cb-rounds").textContent=b.rounds;$("cb-net").textContent=(b.balance-b.start).toFixed(2);$("cb-limit").textContent=(b.balance*maxPct/100).toFixed(2);}
async function commit(){state.server=$("cf-server").value.trim();if(!state.server)throw new Error("Server seed required.");state.commitment=await BitCasinoCore.sha256(state.server);$("cf-output").textContent=JSON.stringify({commitment:state.commitment,serverSeed:"hidden",playerSeed:$("cf-player").value},null,2);}
async function play(){if(!state.commitment)throw new Error("Commit a server seed first.");const game=$("cs-game").value,max=Math.max(2,+$("cs-max").value||100),stake=Math.max(1,+$("cs-stake").value||1),limit=state.bankroll.balance*(Math.max(.1,+$("cb-maxstake").value||1)/100);if(stake>limit)throw new Error(`Stake exceeds simulated bankroll limit ${limit.toFixed(2)} credits.`);const r=await BitCasinoCore.round(state.server,$("cf-player").value,game,max),edge=Math.max(0,+$("cb-edge").value||0)/100;let win;if(game==="coin")win=r.result==="HEADS";else if(game==="dice")win=Number(r.result)>=4;else win=Number(r.result)>max/2;const payout=win?stake*(1-edge):0;state.bankroll.balance+=payout-stake;state.bankroll.rounds++;state.lastProof={schema:"zzx.bitcasino.round.v1",game:{type:game,max},stakeCredits:stake,commitment:state.commitment,serverSeed:state.server,playerSeed:$("cf-player").value,draw:r,win,payoutCredits:payout,bankrollAfter:state.bankroll.balance};$("cs-output").textContent=JSON.stringify(state.lastProof,null,2);$("cv-json").value=JSON.stringify(state.lastProof,null,2);bankrollRender();}
async function verify(v){const c=await BitCasinoCore.sha256(v.serverSeed),r=await BitCasinoCore.round(v.serverSeed,v.playerSeed,v.game.type,v.game.max);return{valid:c===v.commitment&&r.digest===v.draw.digest&&String(r.result)===String(v.draw.result),commitmentValid:c===v.commitment,recomputed:r};}
$("cf-random").addEventListener("click",()=>{$("cf-server").value=BitCasinoCore.randomHex();});$("cf-commit").addEventListener("click",()=>commit().catch(e=>$("cf-output").textContent=`ERROR: ${e.message}`));$("cs-play").addEventListener("click",()=>play().catch(e=>$("cs-output").textContent=`ERROR: ${e.message}`));
$("cb-reset").addEventListener("click",()=>{const x=Math.max(1,+$("cb-start").value||100000);state.bankroll={start:x,balance:x,rounds:0};bankrollRender();});
$("cr-save").addEventListener("click",()=>{state.reserve={policy:$("cr-policy").value.trim(),descriptorReference:$("cr-desc").value.trim(),attestedReserveSats:Math.max(0,+$("cr-sats").value||0),recordedAt:new Date().toISOString()};$("cr-output").textContent=JSON.stringify(state.reserve,null,2);});
$("cl-build").addEventListener("click",()=>{state.settlement={player:$("cl-player").value.trim(),amountSats:Math.max(0,+$("cl-sats").value||0),paymentReference:$("cl-ref").value.trim(),createdAt:new Date().toISOString(),status:"instruction-only"};$("cl-output").textContent=JSON.stringify(state.settlement,null,2);});
$("cl-send").addEventListener("click",async()=>{try{if(!state.settlementProvider)throw new Error("No settlement provider registered.");const r=await state.settlementProvider(state.settlement);$("cl-output").textContent=JSON.stringify({instruction:state.settlement,providerResult:r},null,2);}catch(e){$("cl-output").textContent=`ERROR: ${e.message}`;}});
$("cv-run").addEventListener("click",async()=>{try{$("cv-output").textContent=JSON.stringify(await verify(JSON.parse($("cv-json").value)),null,2);}catch(e){$("cv-output").textContent=`ERROR: ${e.message}`;}});$("cv-export").addEventListener("click",()=>{if(state.lastProof)dl(JSON.stringify(state.lastProof,null,2),`bitcasino-proof-${Date.now()}.json`);});
$("cf-server").value=BitCasinoCore.randomHex();bankrollRender();
window.BitCasino=Object.freeze({version:"0.1.0-alpha-web",verify,registerSettlementProvider(fn){state.settlementProvider=fn;},registerGamePlugin(name,fn){window.BitCasinoPlugins??={};window.BitCasinoPlugins[name]=fn;},getState:()=>({bankroll:state.bankroll,reserve:state.reserve,lastProof:state.lastProof})});
window.ZZXHooks?.emit("bitcasino:ready",{version:"0.1.0-alpha-web"});
})();
