(()=>{"use strict";const $=id=>document.getElementById(id),logs=[];let allowed=null,ctx=null,src=null,gainNode=null;
function log(type,detail={}){logs.unshift({at:new Date().toISOString(),type,...detail});render()}
function render(){const e=$("log");e.replaceChildren();logs.forEach(x=>{const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${x.type}</strong><p>${new Date(x.at).toLocaleString()}</p><pre>${JSON.stringify(x,null,2)}</pre>`;e.append(a)})}
$("lock").onclick=()=>{try{allowed=new URL($("origin").value).origin;const start=new URL($("url").value);if(start.origin!==allowed)throw new Error("Start URL is outside the allowed origin.");$("site-output").textContent=JSON.stringify({allowedOrigin:allowed,startUrl:start.href,sandboxProfile:$("sandbox").value},null,2);log("origin_locked",{allowed})}catch(e){$("site-output").textContent="ERROR: "+e.message}};
$("navigate").onclick=()=>{try{if(!allowed)$("lock").click();const u=new URL($("url").value);if(u.origin!==allowed)throw new Error("Navigation blocked: URL is outside the locked origin.");$("frame").sandbox=$("sandbox").value==="media"?"allow-scripts allow-forms allow-presentation allow-same-origin":"allow-scripts allow-forms allow-presentation";$("frame").src=u.href;log("navigate",{url:u.href})}catch(e){log("navigation_blocked",{error:e.message})}};
$("reload").onclick=()=>{try{$("frame").contentWindow.location.reload();log("reload")}catch{const s=$("frame").src;$("frame").src=s;log("reload")}};
$("media-file").onchange=()=>{const f=$("media-file").files[0];if(!f)return;const u=URL.createObjectURL(f),isVideo=f.type.startsWith("video/"),el=isVideo?$("video"):$("audio");el.src=u;el.hidden=false;(isVideo?$("audio"):$("video")).hidden=true;el.playbackRate=+$("rate").value;try{ctx??=new AudioContext();if(src)src.disconnect();src=ctx.createMediaElementSource(el);gainNode=ctx.createGain();gainNode.gain.value=+$("gain").value;src.connect(gainNode).connect(ctx.destination)}catch{}log("local_media_opened",{name:f.name,type:f.type,size:f.size})};
$("gain").oninput=()=>{if(gainNode)gainNode.gain.value=+$("gain").value};$("rate").oninput=()=>{for(const e of[$("video"),$("audio")])e.playbackRate=+$("rate").value};
function dl(t){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="gomle-session.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("export-session").onclick=()=>dl(JSON.stringify({schema:"zzx.gomle.session.v1",allowedOrigin:allowed,logs},null,2));$("clear-session").onclick=()=>{logs.length=0;render()};render();window.Gomle=Object.freeze({version:"0.2.0-web",getLogs:()=>logs.slice()});window.ZZXHooks?.emit("gomle:ready",{version:"0.2.0-web"})})();
