(()=>{"use strict";const $=id=>document.getElementById(id);let entries=[],pkg=null;
const enc=new TextEncoder(),hex=b=>[...b].map(x=>x.toString(16).padStart(2,"0")).join("");
$("quick").onclick=()=>{const x={id:crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2),at:new Date().toISOString(),category:$("category").value.trim(),amount:+$("amount").value||0,unit:$("unit").value.trim()||"count",note:$("note").value.trim()};if(!x.category)return;entries.push(x);render()};
function render(){const e=$("list");e.replaceChildren();entries.slice().reverse().forEach(x=>{const d=document.createElement("div");d.className="mobile-row";d.innerHTML=`<strong>${x.category}</strong> · ${x.amount} ${x.unit}<div class="fx-watermark">${x.at} · ${x.note}</div>`;e.append(d)});$("count").textContent=entries.length}
$("encrypt").onclick=async()=>{const pass=$("pass").value;if(pass.length<8){$("output").textContent="Use a passphrase of at least 8 characters.";return}const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),base=await crypto.subtle.importKey("raw",enc.encode(pass),"PBKDF2",false,["deriveKey"]),key=await crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:220000,hash:"SHA-256"},base,{name:"AES-GCM",length:256},false,["encrypt"]),plain=enc.encode(JSON.stringify({schema:"zzx.trackertally.mobile.v1",entries})),ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},key,plain));pkg={schema:"zzx.trackertally.mobile.encrypted.v1",cipher:"AES-256-GCM",kdf:"PBKDF2-SHA256-220000",salt:hex(salt),iv:hex(iv),ciphertext:hex(ct),entries:entries.length,created:new Date().toISOString()};$("output").textContent=JSON.stringify(pkg,null,2)};
$("export").onclick=()=>{if(!pkg){$("output").textContent="Encrypt a package first.";return}const t=JSON.stringify(pkg,null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="trackertally-mobile-encrypted.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
$("plain").onclick=()=>{const t=JSON.stringify({schema:"zzx.trackertally.mobile.v1",entries},null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="trackertally-mobile.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
render();window.TrackerTallyAPKCompanion=Object.freeze({version:"1.0.0-web-companion",apkBinaryIncluded:false});
})();
