(() => {
  "use strict";
  const $=id=>document.getElementById(id),KEY="zzx-bitcontractor-state-v1";
  const templates={
    services:{title:"Bitcoin Services Agreement",body:"1. Scope\nDescribe services.\n\n2. Payment\nPayment is due according to the structured Bitcoin action metadata.\n\n3. Acceptance\nDefine acceptance criteria.\n\n4. Disputes\nDisputes may be referred to the linked BitEscrow workflow."},
    escrow:{title:"Bitcoin Escrow Milestone Agreement",body:"1. Escrow\nFunds are controlled by the referenced multisig escrow policy.\n\n2. Milestones\nDefine milestone amounts, evidence, and acceptance criteria.\n\n3. Release\nRelease requires the agreed authorization state.\n\n4. Arbitration\nDisputes follow the linked BitEscrow record."},
    retainer:{title:"Bitcoin Retainer Agreement",body:"1. Term\nDefine retainer term.\n\n2. Retainer\nPayment is denominated in sats and linked to the invoice/payment metadata.\n\n3. Services\nDefine included services and response terms.\n\n4. Termination\nDefine termination and final settlement."},
    nda:{title:"Mutual NDA",body:"1. Confidential Information\nDefine protected information.\n\n2. Duties\nEach party will protect confidential material.\n\n3. Exclusions\nDefine standard exclusions.\n\n4. Term\nDefine duration and survival."}
  };
  const state=Object.assign({versions:[],signatures:[],reviews:[],notaries:[]},JSON.parse(localStorage.getItem(KEY)||"null")||{});
  function persist(){localStorage.setItem(KEY,JSON.stringify(state));}
  function current(){return{id:$("co-id").value.trim(),title:$("co-title").value.trim(),jurisdiction:$("co-jur").value.trim(),parties:$("co-parties").value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),body:$("co-body").value,payment:{amountSats:Math.max(0,+$("co-sats").value||0),reference:$("co-payref").value.trim()},bitEscrowId:$("co-escrow").value.trim()};}
  async function hashCurrent(){const h=await BitContractorCore.sha256Hex(current());$("co-output").textContent=JSON.stringify({sha256:h,contract:current()},null,2);return h;}
  async function saveVersion(){const doc=current(),hash=await BitContractorCore.sha256Hex(doc),v={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),number:state.versions.length+1,savedAt:new Date().toISOString(),hash,doc};state.versions.push(v);persist();renderVersions();$("co-output").textContent=JSON.stringify(v,null,2);}
  function restore(v){$("co-id").value=v.doc.id;$("co-title").value=v.doc.title;$("co-jur").value=v.doc.jurisdiction;$("co-parties").value=v.doc.parties.join("\n");$("co-body").value=v.doc.body;$("co-sats").value=v.doc.payment.amountSats;$("co-payref").value=v.doc.payment.reference;$("co-escrow").value=v.doc.bitEscrowId;}
  function renderVersions(){const root=$("ver-list");root.replaceChildren();const a=$("rd-base"),b=$("rd-next");a.replaceChildren();b.replaceChildren();for(const v of state.versions){const e=document.createElement("article");e.className="z-list-item";const h=document.createElement("strong");h.textContent=`v${v.number} · ${v.hash.slice(0,16)}…`;const p=document.createElement("p");p.textContent=`${v.savedAt} · ${v.doc.title}`;const btn=document.createElement("button");btn.className="btn ghost";btn.textContent="RESTORE";btn.addEventListener("click",()=>restore(v));e.append(h,p,btn);root.appendChild(e);for(const sel of [a,b]){const o=document.createElement("option");o.value=v.id;o.textContent=`v${v.number} · ${v.savedAt}`;sel.appendChild(o);}}if(!state.versions.length)root.innerHTML='<div class="z-list-item"><p>No saved versions.</p></div>';if(state.versions.length>1)b.value=state.versions.at(-1).id;}
  function renderReviews(){const root=$("cb-list");root.replaceChildren();for(const r of state.reviews){const e=document.createElement("article");e.className="z-list-item";e.innerHTML="<strong></strong><p></p>";e.querySelector("strong").textContent=`${r.name} · ${r.role} · ${r.status}`;e.querySelector("p").textContent=r.comment;root.appendChild(e);}if(!state.reviews.length)root.innerHTML='<div class="z-list-item"><p>No review records.</p></div>';}
  function download(data,name,type){const blob=data instanceof Uint8Array?new Blob([data],{type}):new Blob([data],{type}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
  function bundle(){return{schema:"zzx.bitcontractor.bundle.v1",exportedAt:new Date().toISOString(),contract:current(),versions:state.versions,signatures:state.signatures,reviews:state.reviews,notaries:state.notaries};}

  $("co-save-version").addEventListener("click",()=>saveVersion().catch(e=>$("co-output").textContent=`ERROR: ${e.message}`));$("co-hash").addEventListener("click",()=>hashCurrent());
  $("tpl-apply").addEventListener("click",()=>{const t=templates[$("tpl-select").value];$("co-title").value=t.title;$("co-body").value=t.body;$("tpl-preview").textContent=t.body;});
  $("tpl-select").addEventListener("change",()=>{$("tpl-preview").textContent=templates[$("tpl-select").value].body;});$("tpl-preview").textContent=templates.services.body;
  $("ver-export").addEventListener("click",()=>download(JSON.stringify(state.versions,null,2),`bitcontractor-history-${Date.now()}.json`,"application/json"));$("ver-clear").addEventListener("click",()=>{state.versions=[];persist();renderVersions();});
  $("rd-run").addEventListener("click",()=>{const a=state.versions.find(v=>v.id===$("rd-base").value),b=state.versions.find(v=>v.id===$("rd-next").value);$("rd-output").textContent=a&&b?BitContractorCore.lineDiff(a.doc.body,b.doc.body):"Select two saved versions.";});
  $("sg-bind").addEventListener("click",async()=>{const h=await hashCurrent();state.signatures.push({signer:$("sg-name").value.trim(),method:$("sg-method").value.trim(),reference:$("sg-ref").value.trim(),contractHash:h,recordedAt:new Date().toISOString()});persist();$("sg-output").textContent=JSON.stringify(state.signatures,null,2);});
  $("sg-notary").addEventListener("click",async()=>{const h=await hashCurrent(),n={contractHash:h,createdAt:new Date().toISOString(),scope:"contract + structured Bitcoin/BitEscrow metadata"};state.notaries.push(n);persist();$("sg-output").textContent=JSON.stringify(n,null,2);});
  $("cb-add").addEventListener("click",()=>{state.reviews.push({name:$("cb-name").value.trim(),role:$("cb-role").value.trim(),status:$("cb-status").value,comment:$("cb-comment").value.trim(),recordedAt:new Date().toISOString()});persist();renderReviews();});
  $("ex-json").addEventListener("click",()=>{const x=JSON.stringify(bundle(),null,2);download(x,`bitcontractor-${Date.now()}.json`,"application/json");$("ex-output").textContent=x;});
  $("ex-text").addEventListener("click",()=>{const d=current(),x=`${d.title}\nContract ID: ${d.id}\nJurisdiction note: ${d.jurisdiction}\nParties: ${d.parties.join(", ")}\n\n${d.body}\n\nBitcoin amount: ${d.payment.amountSats} sats\nPayment reference: ${d.payment.reference}\nBitEscrow: ${d.bitEscrowId}\n`;download(x,`bitcontractor-${Date.now()}.txt`,"text/plain");$("ex-output").textContent=x;});
  $("ex-pdf").addEventListener("click",()=>{const d=current(),lines=[`Contract ID: ${d.id}`,`Jurisdiction: ${d.jurisdiction}`,`Parties: ${d.parties.join(", ")}`,"",...d.body.split(/\r?\n/),"",`Bitcoin amount: ${d.payment.amountSats} sats`,`Payment reference: ${d.payment.reference}`,`BitEscrow: ${d.bitEscrowId}`];download(BitContractorCore.pdfBytes(d.title,lines),`bitcontractor-${Date.now()}.pdf`,"application/pdf");$("ex-output").textContent="Generated a local single-page PDF document.";});
  renderVersions();renderReviews();
  window.BitContractor=Object.freeze({version:"0.1.0-alpha-web",getContract:current,hashCurrent,saveVersion,getBundle:bundle});
  window.ZZXHooks?.emit("bitcontractor:ready",{version:"0.1.0-alpha-web"});
})();
