(() => {
  "use strict";
  const $=id=>document.getElementById(id);

  function build() {
    const lines=["# Generated by BitFig",""];
    const net=$("bf-network").value;
    if(net!=="main")lines.push(`${net}=1`);
    lines.push(`prune=${Math.max(0,Number($("bf-prune").value)||0)}`);
    lines.push(`dbcache=${Math.max(4,Number($("bf-dbcache").value)||450)}`);
    lines.push(`maxconnections=${Math.max(0,Number($("bf-maxconn").value)||125)}`);
    lines.push(`server=${$("bf-rpc").value}`);
    lines.push(`txindex=${$("bf-txindex").value}`);
    lines.push(`listen=${$("bf-listen").value}`);
    lines.push(`blocksonly=${$("bf-blocksonly").value}`);
    const proxy=$("bf-proxy").value.trim();if(proxy)lines.push(`proxy=${proxy}`);
    const text=lines.join("\n")+"\n";
    $("bf-raw").value=text;$("bf-builder-output").textContent=text;$("bf-current-copy").value=text;return text;
  }

  function validate() {
    const result=BitFigCore.validate($("bf-raw").value);
    $("bf-validation").textContent=JSON.stringify(result,null,2);return result;
  }

  function privacyPreset() {
    $("bf-listen").value="0";$("bf-blocksonly").value="1";$("bf-rpc").value="0";$("bf-proxy").value="127.0.0.1:9050";build();
  }

  function plan() {
    const cfg=$("bf-raw").value,check=BitFigCore.validate(cfg),target=$("bf-target").value,path=$("bf-path").value.trim(),service=$("bf-service").value.trim();
    const steps=[
      "Validate the candidate configuration.",
      `Create a timestamped backup of ${path}.`,
      target==="remote"?"Transfer through the trusted native SSH/Paramiko deployment channel.":"Write the candidate to a temporary local file.",
      "Run node configuration validation / startup check appropriate to the installed Core/Knots version.",
      `Replace ${path} only after validation passes.`,
      `Restart or reload ${service} using the host's service manager.`,
      "Check logs, chain state, peers, RPC availability, and expected network/proxy behavior.",
      "Rollback from the timestamped backup if health checks fail."
    ];
    $("bf-plan-output").textContent=JSON.stringify({target,path,service,configValid:check.valid,steps},null,2);
  }

  function download() {
    const b=new Blob([$("bf-raw").value],{type:"text/plain"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="bitcoin.conf";a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);
  }

  $("bf-build").addEventListener("click",build);
  $("bf-preset-privacy").addEventListener("click",privacyPreset);
  $("bf-validate").addEventListener("click",validate);
  $("bf-diff").addEventListener("click",()=>{$("bf-current-copy").value=$("bf-raw").value;$("bf-diff-output").textContent=JSON.stringify(BitFigCore.diff($("bf-baseline").value,$("bf-raw").value),null,2);});
  $("bf-plan").addEventListener("click",plan);
  $("bf-export").addEventListener("click",download);
  $("bf-import").addEventListener("change",async()=>{const f=$("bf-import").files?.[0];if(!f)return;$("bf-raw").value=await f.text();$("bf-current-copy").value=$("bf-raw").value;$("bf-export-output").textContent=`Imported ${f.name}`;$("bf-import").value="";});
  $("bf-raw").addEventListener("input",()=>{$("bf-current-copy").value=$("bf-raw").value;});
  build();

  window.BitFig=Object.freeze({version:"0.2.0-alpha-web",build,validate,parse:BitFigCore.parse,diff:BitFigCore.diff,getConfig:()=>$("bf-raw").value});
  window.ZZXHooks?.emit("bitfig:ready",{version:"0.2.0-alpha-web"});
})();
