(()=>{"use strict";const $=id=>document.getElementById(id);let services=[];
$("add").onclick=()=>{services.push({name:$("name").value.trim(),kind:$("kind").value,host:$("host").value.trim()||"127.0.0.1",port:+$("port").value||8000,route:$("route").value.trim()||"/",enabled:$("enabled").checked});render()};
function render(){const e=$("services");e.replaceChildren();services.forEach(s=>{const d=document.createElement("div");d.className="svc";d.innerHTML=`<strong>${s.name}</strong> · ${s.kind} · ${s.host}:${s.port}${s.route} · ${s.enabled?"enabled":"disabled"}`;e.append(d)});$("count").textContent=services.length}
$("nginx").onclick=()=>{$("output").textContent=services.filter(s=>s.enabled).map(s=>`# ${s.name}\nlocation ${s.route} {\n  proxy_pass http://${s.host}:${s.port};\n  proxy_set_header Host $host;\n  proxy_set_header X-Forwarded-Proto $scheme;\n}`).join("\n")};
$("systemd").onclick=()=>{$("output").textContent=services.filter(s=>s.enabled&&s.kind==="gunicorn").map(s=>`[Unit]\nDescription=${s.name}\nAfter=network.target\n\n[Service]\nWorkingDirectory=/srv/${s.name}\nExecStart=/usr/bin/gunicorn --bind ${s.host}:${s.port} app:app\nRestart=on-failure\n\n[Install]\nWantedBy=multi-user.target\n`).join("\n")};
$("firewall").onclick=()=>{$("output").textContent=["# REVIEW-ONLY UFW PLAN","# Do not execute without operator review.",...services.filter(s=>s.enabled&&s.host!=="127.0.0.1").map(s=>`allow ${s.port}/tcp # ${s.name}`)].join("\n")};
$("stack").onclick=()=>{$("output").textContent=JSON.stringify({schema:"zzx.sss.stack.v1",generated:new Date().toISOString(),docker:false,containers:false,services,controls:{applyAutomatically:false,remoteShell:false,credentialsEmbedded:false,reviewRequired:true}},null,2)};
$("export").onclick=()=>{const t=JSON.stringify({schema:"zzx.sss.stack.v1",docker:false,containers:false,services},null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="zzxsss-stack.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
[["site-api","flask","127.0.0.1",8100,"/api/",true],["worker-api","gunicorn","127.0.0.1",8101,"/worker/",true],["onion-mirror","nginx","127.0.0.1",8180,"/",true]].forEach(([name,kind,host,port,route,enabled])=>services.push({name,kind,host,port,route,enabled}));render();window.ZZXSSS=Object.freeze({version:"0.1.0-alpha-web",docker:false,autoApply:false,remoteShell:false});
})();
