(()=>{"use strict";const $=id=>document.getElementById(id),te=new TextEncoder(),td=new TextDecoder();const state={people:[],logs:[],plans:[],cycles:{},agreements:[]};const uid=()=>crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2)+Date.now();const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));const person=id=>state.people.find(p=>p.id===id);const selected=id=>[...$(id).selectedOptions].map(o=>o.value);
function syncSelects(){for(const id of["balance-person","cycle-person","plan-person","agreement-person"]){const el=$(id),multi=el.multiple,old=multi?selected(id):el.value;el.replaceChildren();for(const p of state.people){const o=document.createElement("option");o.value=p.id;o.textContent=p.name;el.append(o)}if(multi)[...el.options].forEach(o=>o.selected=old.includes(o.value));else if(old)el.value=old}}
function renderPeople(){const el=$("people-list");el.replaceChildren();for(const p of state.people){const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${esc(p.name)}</strong><p>${esc(p.role||"partner")} ${p.pronouns?"· "+esc(p.pronouns):""}</p><p>${esc(p.notes||"")}</p><button class="btn ghost" data-remove="${p.id}">REMOVE</button>`;el.append(a)}el.querySelectorAll("[data-remove]").forEach(b=>b.onclick=()=>{state.people=state.people.filter(p=>p.id!==b.dataset.remove);state.logs=state.logs.filter(x=>x.personId!==b.dataset.remove);delete state.cycles[b.dataset.remove];renderAll()});syncSelects();$("people-count").textContent=state.people.length;renderBalance()}
function addPerson(name,role="",pronouns="",notes=""){name=String(name).trim();if(!name)return;state.people.push({id:uid(),name,role,pronouns,notes});renderPeople()}
$("add-person").onclick=()=>{addPerson($("person-name").value,$("person-role").value,$("person-pronouns").value,$("person-notes").value);$("person-name").value="";$("person-notes").value=""};$("reset-demo").onclick=()=>{Object.assign(state,{people:[],logs:[],plans:[],cycles:{},agreements:[]});addPerson("You","central member");["Partner A","Partner B","Partner C","Partner D"].forEach(n=>addPerson(n,"partner"));renderAll()};$("clear-all").onclick=()=>{Object.assign(state,{people:[],logs:[],plans:[],cycles:{},agreements:[]});renderAll()};
function renderBalance(){const sums=Object.fromEntries(state.people.map(p=>[p.id,0]));for(const x of state.logs)if(x.personId in sums)sums[x.personId]+=x.minutes;const total=Object.values(sums).reduce((a,b)=>a+b,0),n=state.people.length,equal=n?1/n:0;let dev=0;$("total-time").textContent=`${total} min`;const tb=$("balance-table");tb.replaceChildren();for(const p of state.people){const mins=sums[p.id]||0,share=total?mins/total:0;dev+=Math.abs(share-equal);const tr=document.createElement("tr");tr.innerHTML=`<td>${esc(p.name)}</td><td>${mins}</td><td>${(share*100).toFixed(1)}%</td><td>${((share-equal)*100).toFixed(1)} pp</td>`;tb.append(tr)}$("balance-index").textContent=n&&total?Math.max(0,100-(dev/2)*100).toFixed(1)+"/100":"—"}
$("log-time").onclick=()=>{const id=$("balance-person").value,min=Math.max(0,+$("balance-minutes").value||0);if(!id||!min)return;state.logs.push({id:uid(),personId:id,minutes:min,category:$("balance-category").value,at:new Date().toISOString()});renderBalance()};
function renderPlans(){const el=$("plans-list");el.replaceChildren();for(const x of state.plans){const names=x.participants.map(id=>person(id)?.name).filter(Boolean).join(", ");const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${esc(x.type)} · ${esc(names)}</strong><p>${esc(x.when||"unscheduled")}</p><p>${esc(x.text)}</p><p>consent ${x.consent?"yes":"not marked"} · limits ${x.limits?"reviewed":"not marked"} · follow-up ${x.aftercare?"planned":"not marked"}</p>`;el.append(a)}}
$("add-plan").onclick=()=>{const p=selected("plan-person");if(!p.length||!$("plan-text").value.trim())return;state.plans.push({id:uid(),type:$("plan-type").value,participants:p,when:$("plan-when").value,text:$("plan-text").value.trim(),consent:$("consent-check").checked,limits:$("limits-check").checked,aftercare:$("aftercare-check").checked});$("plan-text").value="";renderPlans()};
function renderCycles(){const el=$("cycle-list");el.replaceChildren();for(const[id,x]of Object.entries(state.cycles)){const p=person(id);if(!p)continue;const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>${esc(p.name)}</strong><p>${esc(x.sign||"no sign")} · ${esc(x.stage||"not tracked")}</p><p>mood ${x.mood}/5 · energy ${x.energy}/5 · interest ${x.interest}/5</p><p>${esc(x.notes||"")}</p>`;el.append(a)}}
$("save-cycle").onclick=()=>{const id=$("cycle-person").value;if(!id)return;state.cycles[id]={sign:$("sign").value,stage:$("cycle-stage").value,mood:+$("mood").value,energy:+$("energy").value,interest:+$("interest").value,notes:$("cycle-notes").value.trim(),updated:new Date().toISOString()};renderCycles()};
function agreementText(){const names=selected("agreement-person").map(id=>person(id)?.name).filter(Boolean),type=$("agreement-type").value,review=$("agreement-review").value||"not specified",terms=$("agreement-terms").value.trim();return`${type.toUpperCase()}

Participants: ${names.join(", ")||"Not specified"}
Review date: ${review}

Purpose
This document records the participants' current mutual understanding. It does not create entitlement to another person's body, time, attention, affection, property, or participation.

Terms
${terms||"[Add terms, boundaries, logistics, expectations, privacy rules, and follow-up conditions.]"}

Consent
${$("revocable").checked?"Consent is voluntary, specific, informed, and revocable at any time. A prior yes does not imply a future yes.":"Participants should explicitly define revocation and consent terms before using this agreement."}

Change control
Any participant may request a pause, revision, or review. Material changes should be discussed and recorded before relying on the revised terms.

Acknowledgment
This template is a coordination record, not legal advice and not a substitute for professional medical, legal, or mental-health guidance where those are needed.
`}
$("build-agreement").onclick=()=>{$("agreement-output").value=agreementText()};$("save-agreement").onclick=()=>{const t=agreementText();$("agreement-output").value=t;state.agreements.push({id:uid(),type:$("agreement-type").value,participants:selected("agreement-person"),text:t,created:new Date().toISOString()})};
const b64=b=>{let s="";for(let i=0;i<b.length;i+=32768)s+=String.fromCharCode(...b.subarray(i,i+32768));return btoa(s)},ub64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
async function key(pass,salt,it){const base=await crypto.subtle.importKey("raw",te.encode(pass),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",hash:"SHA-256",salt,iterations:it},base,{name:"AES-GCM",length:256},false,["encrypt","decrypt"])}
async function encrypt(pass,it){if(pass.length<8)throw new Error("Use at least 8 characters.");const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(pass,salt,it),plain=te.encode(JSON.stringify({schema:"zzx.cyberconcubine.v1",exported:new Date().toISOString(),state})),ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},k,plain));return{schema:"zzx.cyberconcubine.encrypted.v1",kdf:{name:"PBKDF2",hash:"SHA-256",iterations:it,salt:b64(salt)},cipher:{name:"AES-GCM",iv:b64(iv)},ciphertext:b64(ct)}}
async function decrypt(doc,pass){const k=await key(pass,ub64(doc.kdf.salt),doc.kdf.iterations),plain=await crypto.subtle.decrypt({name:"AES-GCM",iv:ub64(doc.cipher.iv)},k,ub64(doc.ciphertext));return JSON.parse(td.decode(plain))}
$("export-vault").onclick=async()=>{try{const doc=await encrypt($("vault-pass").value,Math.max(100000,+$("vault-iter").value||310000)),t=JSON.stringify(doc,null,2),blob=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(blob),a=document.createElement("a");a.href=u;a.download="cyberconcubine-project.enc.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),900);$("vault-output").textContent="Encrypted project exported."}catch(e){$("vault-output").textContent="ERROR: "+e.message}};
$("import-vault").onchange=async()=>{try{const f=$("import-vault").files[0];if(!f)return;const x=await decrypt(JSON.parse(await f.text()),$("vault-pass").value);Object.assign(state,x.state);renderAll();$("vault-output").textContent="Encrypted project imported."}catch(e){$("vault-output").textContent="ERROR: "+e.message}finally{$("import-vault").value=""}};
function renderAll(){renderPeople();renderPlans();renderCycles()}renderAll();window.CyberConcubine=Object.freeze({version:"0.1.0-alpha-web",getState:()=>JSON.parse(JSON.stringify(state)),agreementText});window.ZZXHooks?.emit("cyberconcubine:ready",{version:"0.1.0-alpha-web"})})();
