(()=>{"use strict";const $=id=>document.getElementById(id);let services=[];
const uid=()=>crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2);
$("add").onclick=()=>{const s={id:uid(),name:$("name").value.trim(),module:$("module").value.trim(),host:$("host").value.trim()||"127.0.0.1",port:Math.max(1,Math.min(65535,+$("port").value||8000)),kind:$("kind").value,enabled:$("enabled").checked,healthPath:$("health").value.trim()||"/health",notes:$("notes").value.trim()};if(!s.name)return;services.push(s);render()};
function render(){const e=$("services");e.replaceChildren();services.forEach(s=>{const d=document.createElement("div");d.className="service-row";d.innerHTML=`<strong><i class="status-dot ${s.enabled?"":"off"}"></i>${s.name}</strong> · ${s.kind}<div>${s.host}:${s.port}${s.healthPath}</div><div class="fx-watermark">${s.module} · ${s.notes}</div><button class="btn ghost" data-id="${s.id}">${s.enabled?"DISABLE":"ENABLE"}</button>`;e.append(d)});e.querySelectorAll("[data-id]").forEach(b=>b.onclick=()=>{const s=services.find(x=>x.id===b.dataset.id);s.enabled=!s.enabled;render()});$("count").textContent=services.length;$("enabled-count").textContent=services.filter(s=>s.enabled).length;$("ports").textContent=new Set(services.map(s=>s.port)).size}
$("plan").onclick=()=>{const plan={schema:"zzx.core.stack.v1",generated:new Date().toISOString(),containers:false,docker:false,services,launchModel:"direct local processes under explicit operator control",credentialsIncluded:false,remoteShell:false};$("output").textContent=JSON.stringify(plan,null,2)};
$("nginx").onclick=()=>{$("adapter").textContent=services.filter(s=>s.enabled).map(s=>`# ${s.name}\nlocation /${s.name.toLowerCase().replace(/[^a-z0-9]+/g,"-")}/ {\n    proxy_pass http://${s.host}:${s.port}/;\n    proxy_set_header Host $host;\n}`).join("\n")};
$("flask").onclick=()=>{$("adapter").textContent=`# ZZX-Core Flask registry adapter (reference)\n# services are loaded from stack.json; no shell commands or credentials are accepted from HTTP clients.\nGET /api/status\nGET /api/services\nGET /api/services/<id>\nPOST /api/reload-config   # local operator auth should be added by deployment\n`};
$("export").onclick=()=>{const t=JSON.stringify({schema:"zzx.core.stack.v1",containers:false,docker:false,services},null,2),b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="zzxcore-stack.json";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
[["Website API","site-api",8081,"flask"],["Bitcoin Data","bitcoin-data",8082,"api"],["Research Mirror","research-mirror",8083,"mirror"]].forEach(([name,module,port,kind])=>services.push({id:uid(),name,module,host:"127.0.0.1",port,kind,enabled:true,healthPath:"/health",notes:"local service profile"}));render();window.ZZXCore=Object.freeze({version:"0.4.0-alpha-web",docker:false,remoteShell:false});
})();
