(()=>{"use strict";const $=id=>document.getElementById(id),enc=new TextEncoder(),dec=new TextDecoder();let docs=[{id:"main",name:"main.txt",text:"ZZX++ offline editor\n"}],active="main",vault=null;
const cur=()=>docs.find(d=>d.id===active);
function render(){const e=$("docs");e.replaceChildren();docs.forEach(d=>{const b=document.createElement("button");b.className="btn ghost doc";b.textContent=d.name;b.onclick=()=>{saveCurrent();active=d.id;$("editor").value=d.text;render()};e.append(b)});$("doc-count").textContent=docs.length}
function saveCurrent(){const d=cur();if(d)d.text=$("editor").value}
$("editor").oninput=saveCurrent;
$("new").onclick=()=>{saveCurrent();const id=crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2);docs.push({id,name:`untitled-${docs.length+1}.txt`,text:""});active=id;$("editor").value="";render()};
$("open").onchange=async()=>{const f=$("open").files[0];if(!f)return;saveCurrent();const id=crypto.randomUUID?crypto.randomUUID():Math.random().toString(36).slice(2);docs.push({id,name:f.name,text:await f.text()});active=id;$("editor").value=cur().text;$("open").value="";render()};
$("save").onclick=()=>{saveCurrent();const d=cur(),b=new Blob([d.text],{type:"text/plain"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=d.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
$("find").onclick=()=>{const q=$("query").value,repl=$("replace").value,rx=$("regex").checked?new RegExp(q,"g"):null;saveCurrent();let t=cur().text;const hits=$("regex").checked?[...t.matchAll(rx)].length:t.split(q).length-1;$("find-out").textContent=`matches: ${hits}`;if($("do-replace").checked){t=$("regex").checked?t.replace(rx,repl):t.split(q).join(repl);cur().text=t;$("editor").value=t}};
$("transform").onclick=async()=>{let t=$("editor").value;switch($("op").value){case"base64-enc":t=btoa(unescape(encodeURIComponent(t)));break;case"base64-dec":t=decodeURIComponent(escape(atob(t)));break;case"hex":t=[...enc.encode(t)].map(x=>x.toString(16).padStart(2,"0")).join("");break;case"upper":t=t.toUpperCase();break;case"lower":t=t.toLowerCase();break;case"json":try{t=JSON.stringify(JSON.parse(t),null,2)}catch(e){t="JSON ERROR: "+e.message}break;case"sha256":t=[...new Uint8Array(await crypto.subtle.digest("SHA-256",enc.encode(t)))].map(x=>x.toString(16).padStart(2,"0")).join("");break}$("transform-out").textContent=t};
async function key(pass,salt,uses){const b=await crypto.subtle.importKey("raw",enc.encode(pass),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:250000,hash:"SHA-256"},b,{name:"AES-GCM",length:256},false,uses)}
const hex=b=>[...b].map(x=>x.toString(16).padStart(2,"0")).join(""),unhex=s=>new Uint8Array((s.match(/../g)||[]).map(x=>parseInt(x,16)));
$("encrypt").onclick=async()=>{const pass=$("pass").value;if(pass.length<10){$("vault-out").textContent="Use a local passphrase of at least 10 characters.";return}saveCurrent();const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(pass,salt,["encrypt"]),ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},k,enc.encode(cur().text)));vault={schema:"zzxpp.vault.v1",cipher:"AES-256-GCM",kdf:"PBKDF2-SHA256",iterations:250000,salt:hex(salt),iv:hex(iv),ciphertext:hex(ct)};$("vault-out").textContent=JSON.stringify(vault,null,2)};
$("decrypt").onclick=async()=>{try{const k=await key($("pass").value,unhex(vault.salt),["decrypt"]),pt=await crypto.subtle.decrypt({name:"AES-GCM",iv:unhex(vault.iv)},k,unhex(vault.ciphertext));$("vault-out").textContent=dec.decode(pt)}catch(e){$("vault-out").textContent="DECRYPT ERROR: "+e.message}};
$("plugin").onclick=()=>{$("plugin-out").textContent=JSON.stringify({schema:"zzxpp.plugin.v1",name:$("plugin-name").value||"example",trigger:$("plugin-trigger").value,operations:$("plugin-ops").value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean),network:false,externalExecution:false},null,2)};
$("editor").value=cur().text;render();window.ZZXPP=Object.freeze({version:"0.6.0-alpha-web",offline:true,externalExecution:false});
})();
