(()=>{"use strict";const $=id=>document.getElementById(id),state={enabled:false,jobs:[],emotion:{warmth:.6,playfulness:.5,calm:.7}};
function requireAdult(){if(!state.enabled)throw new Error("Enable the adult workspace first.")}
$("enable").onclick=()=>{state.enabled=$("adult").checked;$("gate-output").textContent=state.enabled?"Adult workspace enabled for consensual adult use.":"Adult confirmation required."};
function render(){const e=$("conversation");e.replaceChildren();state.jobs.filter(x=>x.modality==="text").slice().reverse().forEach(j=>{const a=document.createElement("article");a.className="z-list-item";a.innerHTML=`<strong>planned text job</strong><p>${GPWebCore.esc(j.prompt)}</p>`;e.append(a)})}
$("queue-text").onclick=()=>{try{requireAdult();const p=$("prompt").value.trim();if(!p)return;state.jobs.push(GPWebCore.job("text",p,{scope:"consensual-adult",emotion:state.emotion,identityCloning:false}));render()}catch(e){alert(e.message)}};
$("tts").onclick=()=>{try{requireAdult();GPWebCore.speak($("prompt").value)}catch(e){alert(e.message)}};$("stt").onclick=()=>{try{requireAdult();const r=GPWebCore.recognition();if(!r)throw new Error("Speech recognition unavailable.");r.onresult=e=>$("prompt").value=e.results[0][0].transcript;r.start()}catch(e){alert(e.message)}};
$("queue-media").onclick=()=>{try{requireAdult();const j=GPWebCore.job($("modality").value,$("media-prompt").value,{scope:"consensual-adult",adapter:$("adapter").value,seed:+$("seed").value||0,identityCloning:false});state.jobs.push(j);$("media-output").textContent=JSON.stringify(j,null,2)}catch(e){$("media-output").textContent="ERROR: "+e.message}};
$("emotion").onclick=()=>{state.emotion={warmth:+$("warmth").value,playfulness:+$("play").value,calm:+$("calm").value};$("emotion-output").textContent=JSON.stringify({...state.emotion,note:"Conversational state only; not sentience."},null,2)};
$("export").onclick=()=>{try{requireAdult();const doc={schema:"zzx.cgai.session.v1",exported:new Date().toISOString(),adultScope:"consensual adults only",identityCloning:false,state},t=JSON.stringify(doc,null,2);GPWebCore.dl(t,"cgai-session.json");$("export-output").textContent=t}catch(e){$("export-output").textContent="ERROR: "+e.message}};
window.CyberGeishaAI=Object.freeze({version:"0.1.0-alpha-web",adultOnly:true});window.ZZXHooks?.emit("cgai:ready",{version:"0.1.0-alpha-web"})})();
