(() => {
  "use strict";
  const $=id=>document.getElementById(id),DEFAULT="https://mempool.space/api";
  const app={api:localStorage.getItem("zzx-bitcoin-mined-api")||DEFAULT,height:null,timer:null};
  function status(t,k){const e=$("bm-net");e.textContent=t;e.className=`runtime-badge ${k}`;}
  function apply(h){if(!Number.isFinite(+h)||+h<0)throw new Error("Invalid height.");app.height=Math.floor(+h);render();}
  async function refresh(){status("HEIGHT: FETCHING","partial");try{const r=await fetch(`${app.api}/blocks/tip/height`,{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);apply(Number(await r.text()));status("HEIGHT: LIVE","ok");}catch(e){status("HEIGHT: ERROR","bad");$("mi-output").textContent=`ERROR: ${e.message}`;}}
  function render(){if(app.height==null)return;const s=BitcoinMinedCore.state(app.height);$("mi-height").textContent=s.height.toLocaleString();$("mi-issued").textContent=`${s.issuedBtc.toLocaleString(undefined,{maximumFractionDigits:8})} BTC`;$("mi-remain").textContent=`${s.remainingTo21mBtc.toLocaleString(undefined,{maximumFractionDigits:8})} BTC`;$("mi-percent").textContent=`${s.issuedPercent.toFixed(6)}%`;$("mi-output").textContent=JSON.stringify(s,null,2);$("me-epoch").textContent=s.epoch;$("me-subsidy").textContent=`${s.subsidyBtc.toFixed(8)} BTC`;$("me-blocks").textContent=s.blocksRemaining.toLocaleString();$("me-issued").textContent=`${s.epochIssuanceBtc.toLocaleString(undefined,{maximumFractionDigits:8})} BTC`;draw();}
  function projectHeight(h){const s=BitcoinMinedCore.state(Math.max(0,Math.floor(+h||0)));$("mp-output").textContent=JSON.stringify(s,null,2);}
  function projectDays(){if(app.height==null)throw new Error("Set current height.");const days=Math.max(0,+$("mp-days").value||0),blocks=Math.round(days*86400/600);projectHeight(app.height+blocks);}
  function draw(){const c=$("mined-canvas"),ctx=c.getContext("2d"),dpr=Math.max(1,Math.min(2,devicePixelRatio||1)),r=c.getBoundingClientRect(),w=Math.max(320,Math.round(r.width)),h=Math.max(280,Math.round(r.height||380));c.width=w*dpr;c.height=h*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle="#050505";ctx.fillRect(0,0,w,h);const pts=[];for(let e=0;e<=16;e++){const ht=e*BitcoinMinedCore.HALVING;pts.push([ht,BitcoinMinedCore.issued(Math.max(0,ht-1))]);}if(app.height!=null)pts.push([app.height,BitcoinMinedCore.issued(app.height)]);pts.sort((a,b)=>a[0]-b[0]);const maxH=Math.max(...pts.map(x=>x[0]),1),pad=44;ctx.strokeStyle="#c0d674";ctx.lineWidth=2;ctx.beginPath();pts.forEach(([xv,yv],i)=>{const x=pad+(w-pad*2)*xv/maxH,y=h-35-(yv/BitcoinMinedCore.MAX)*(h-70);i?ctx.lineTo(x,y):ctx.moveTo(x,y);});ctx.stroke();ctx.fillStyle="#969696";ctx.font="10px monospace";ctx.fillText("subsidy-only cumulative issuance",pad,18);}
  function auto(){if(app.timer){clearInterval(app.timer);app.timer=null;$("mined-auto").textContent="AUTO: OFF";}else{app.timer=setInterval(refresh,30000);$("mined-auto").textContent="AUTO: 30S";}}
  $("mined-api").value=app.api;$("mined-source-output").textContent=JSON.stringify({api:app.api},null,2);$("mined-refresh").addEventListener("click",refresh);$("mined-auto").addEventListener("click",auto);$("mp-height-run").addEventListener("click",()=>projectHeight($("mp-height").value));$("mp-days-run").addEventListener("click",()=>{try{projectDays();}catch(e){$("mp-output").textContent=`ERROR: ${e.message}`;}});$("mm-apply").addEventListener("click",()=>apply($("mm-height").value));$("mined-save").addEventListener("click",()=>{app.api=$("mined-api").value.trim().replace(/\/+$/,"")||DEFAULT;localStorage.setItem("zzx-bitcoin-mined-api",app.api);$("mined-source-output").textContent=JSON.stringify({api:app.api},null,2);});$("mined-reset").addEventListener("click",()=>{app.api=DEFAULT;$("mined-api").value=DEFAULT;localStorage.removeItem("zzx-bitcoin-mined-api");$("mined-source-output").textContent=JSON.stringify({api:app.api},null,2);});apply($("mm-height").value);
  window.BitcoinMined=Object.freeze({version:"0.1.0-alpha-web",refresh,setHeight:apply,issued:BitcoinMinedCore.issued,subsidy:BitcoinMinedCore.subsidy,getState:()=>BitcoinMinedCore.state(app.height||0)});
  window.ZZXHooks?.emit("bitcoin-mined:ready",{version:"0.1.0-alpha-web"});
})();
