(()=>{"use strict";const $=id=>document.getElementById(id),wc=$("wave"),wx=wc.getContext("2d"),fc=$("fft"),fx=fc.getContext("2d");let ctx=null,source=null,stream=null,an=null,time=null,freq=null,raf=0,capture=[];
async function mic(){stop();stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});ctx=new (window.AudioContext||window.webkitAudioContext)();source=ctx.createMediaStreamSource(stream);setup()}
async function file(){stop();const f=$("audio").files[0];if(!f)return;const buf=await f.arrayBuffer();ctx=new (window.AudioContext||window.webkitAudioContext)();const decoded=await ctx.decodeAudioData(buf);source=ctx.createBufferSource();source.buffer=decoded;source.loop=$("loop").checked;setup();source.start();$("audio").value=""}
function setup(){an=ctx.createAnalyser();an.fftSize=+($("fft-size").value)||2048;an.smoothingTimeConstant=+($("smooth").value)||.2;time=new Uint8Array(an.fftSize);freq=new Uint8Array(an.frequencyBinCount);source.connect(an);if($("monitor").checked)an.connect(ctx.destination);$("state").textContent="RUNNING";draw()}
function stop(){cancelAnimationFrame(raf);try{source?.stop?.()}catch{}stream?.getTracks().forEach(t=>t.stop());try{ctx?.close()}catch{}ctx=source=stream=an=null;$("state").textContent="STOPPED"}
$("mic").onclick=()=>mic().catch(e=>$("state").textContent="MIC ERROR: "+e.message);$("load").onclick=()=>file().catch(e=>$("state").textContent="FILE ERROR: "+e.message);$("stop").onclick=stop;
function draw(){if(!an)return;an.getByteTimeDomainData(time);an.getByteFrequencyData(freq);drawWave();drawFFT();metrics();if($("capture").checked)capture.push({t:performance.now(),wave:[...time]});if(capture.length>600)capture.shift();raf=requestAnimationFrame(draw)}
function grid(g,c){g.fillStyle="#030303";g.fillRect(0,0,c.width,c.height);g.strokeStyle="#1c1c1c";g.lineWidth=1;for(let i=0;i<=10;i++){g.beginPath();g.moveTo(i*c.width/10,0);g.lineTo(i*c.width/10,c.height);g.stroke()}for(let i=0;i<=6;i++){g.beginPath();g.moveTo(0,i*c.height/6);g.lineTo(c.width,i*c.height/6);g.stroke()}}
function drawWave(){grid(wx,wc);wx.strokeStyle="#c0d674";wx.lineWidth=2;wx.beginPath();time.forEach((v,i)=>{const px=i/(time.length-1)*wc.width,py=v/255*wc.height;i?wx.lineTo(px,py):wx.moveTo(px,py)});wx.stroke()}
function drawFFT(){grid(fx,fc);fx.fillStyle="#c0d674";const n=Math.min(256,freq.length),bw=fc.width/n;for(let i=0;i<n;i++){const v=freq[Math.floor(i*freq.length/n)]/255;fx.fillRect(i*bw,fc.height-v*fc.height,bw*.75,v*fc.height)}}
function metrics(){let sum=0,peak=0;for(const v of time){const x=(v-128)/128;sum+=x*x;peak=Math.max(peak,Math.abs(x))}const rms=Math.sqrt(sum/time.length);let mi=0;for(let i=1;i<freq.length;i++)if(freq[i]>freq[mi])mi=i;const hz=mi*ctx.sampleRate/an.fftSize;$("rms").textContent=rms.toFixed(4);$("peak").textContent=peak.toFixed(4);$("peak-hz").textContent=hz.toFixed(1);$("sample-rate").textContent=ctx.sampleRate;$("meter").style.width=Math.min(100,peak*100)+"%"}
$("fft-size").oninput=()=>{if(an){an.fftSize=+$("fft-size").value;time=new Uint8Array(an.fftSize);freq=new Uint8Array(an.frequencyBinCount)}};$("smooth").oninput=()=>{if(an)an.smoothingTimeConstant=+$("smooth").value};
$("clear-capture").onclick=()=>capture=[];
$("csv").onclick=()=>{if(!capture.length)return;const lines=["frame_ms,sample_index,value"];capture.forEach(f=>f.wave.forEach((v,i)=>lines.push(`${f.t.toFixed(3)},${i},${((v-128)/128).toFixed(6)}`)));const b=new Blob([lines.join("\n")],{type:"text/csv"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download="zzxosc-wave-capture.csv";a.click();setTimeout(()=>URL.revokeObjectURL(u),800)};
$("config").onclick=()=>{$("config-out").textContent=JSON.stringify({schema:"zzx.osc.pipeline.v1",source:$("source-kind").value,fftSize:+$("fft-size").value,smoothing:+$("smooth").value,monitor:$("monitor").checked,webAudio:true,sdrLive:false,vstHosting:false,notes:"SDR/VST require native backends such as SoapySDR/host plugin APIs."},null,2)};
window.ZZXOSC=Object.freeze({version:"0.2.0-beta-web",webAudio:true,sdrLive:false,vstHosting:false});
})();
