(()=>{"use strict";const $=id=>document.getElementById(id);let engine=new CEXResearchEngine(42),book=null,lastBacktest=null,lastExecution=null;const region="United States";
function makeBook(){engine=new CEXResearchEngine((+$("seed").value||42)>>>0);book=engine.orderBook(+$("mid").value||60000,Math.max(3,+$("levels").value||12),Math.max(.01,+$("tick").value||10),1.5);const tb=$("book-body");tb.replaceChildren();for(let i=0;i<book.bids.length;i++){const tr=document.createElement("tr");tr.innerHTML=`<td>${book.bids[i].btc.toFixed(6)}</td><td>${book.bids[i].price.toFixed(2)}</td><td>${book.asks[i].price.toFixed(2)}</td><td>${book.asks[i].btc.toFixed(6)}</td>`;tb.append(tr)}}
$("gen-book").onclick=makeBook;
$("simulate-order").onclick=()=>{if(!book)makeBook();lastExecution=engine.execute(book,$("side").value,Math.max(.000001,+$("amount").value||.25),Math.max(0,+$("fee").value||20));$("execution-output").textContent=JSON.stringify(lastExecution,null,2)};
function draw(s){const c=$("chart"),x=c.getContext("2d"),w=c.width,h=c.height;x.clearRect(0,0,w,h);if(!s.length)return;const vals=s.map(v=>v.equity),mn=Math.min(...vals),mx=Math.max(...vals),span=mx-mn||1;x.beginPath();s.forEach((v,i)=>{const px=20+i/(s.length-1||1)*(w-40),py=h-20-(v.equity-mn)/span*(h-40);i?x.lineTo(px,py):x.moveTo(px,py)});x.strokeStyle="#c0d674";x.lineWidth=2;x.stroke()}
$("run-backtest").onclick=()=>{engine=new CEXResearchEngine((+$("seed").value||42)>>>0);lastBacktest=engine.backtest({days:Math.max(10,+$("days").value||180),start:+$("mid").value||60000,vol:Math.max(0,+$("vol").value||.035),drift:+$("drift").value||0,feeBps:Math.max(0,+$("fee").value||20),strategy:$("strategy").value,cash:Math.max(100,+$("cash").value||10000)});draw(lastBacktest.series);$("backtest-output").textContent=JSON.stringify(lastBacktest.summary,null,2)};
$("run-risk").onclick=()=>{const btc=+$("risk-btc").value,entry=+$("risk-entry").value,move=+$("stress").value/100,stressed=entry*(1+move),pnl=btc*(stressed-entry);$("risk-output").textContent=JSON.stringify({region,positionBTC:btc,entryPrice:entry,stressMovePct:move*100,stressedPrice:stressed,pnlQuote:pnl,notionalAtEntry:btc*entry},null,2)};
function dl(t,n){const b=new Blob([t],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("export-json").onclick=()=>{const doc={schema:"zzx.freedomkobracex.research.v1",region,mode:"CEX simulation",book,lastExecution,lastBacktest:lastBacktest?{summary:lastBacktest.summary,series:lastBacktest.series}:null};const t=JSON.stringify(doc,null,2);dl(t,"freedomkobracex-research.json");$("export-output").textContent=t};
makeBook();window.FreedomKobraCEX=Object.freeze({version:"0.1.0-alpha-web",simulationOnly:true});window.ZZXHooks?.emit("freedomkobracex:ready",{version:"0.1.0-alpha-web"})})();
