(()=>{"use strict";const $=id=>document.getElementById(id),enc=new TextEncoder(),dec=new TextDecoder();let nodes=[],envelope=null;
const hex=b=>[...b].map(x=>x.toString(16).padStart(2,"0")).join("");const unhex=s=>new Uint8Array((s.match(/../g)||[]).map(x=>parseInt(x,16)));
function addNode(){const n={id:$("node-id").value.trim()||`node-${nodes.length+1}`,transport:$("transport").value,role:$("role").value,rangeKm:Math.max(0,+$("range").value||0),linkQuality:Math.max(0,Math.min(100,+$("quality").value||0)),authorized:true};if(nodes.some(x=>x.id===n.id))return;nodes.push(n);render()}
$("add-node").onclick=addNode;
function render(){const e=$("nodes");e.replaceChildren();nodes.forEach(n=>{const d=document.createElement("div");d.className="mesh-node";d.innerHTML=`<strong>${n.id}</strong> · ${n.transport} · ${n.role}<div>range ${n.rangeKm} km · link ${n.linkQuality}%</div>`;e.append(d)});$("node-count").textContent=nodes.length;$("transport-count").textContent=new Set(nodes.map(x=>x.transport)).size}
async function key(pass,salt,usages){const base=await crypto.subtle.importKey("raw",enc.encode(pass),"PBKDF2",false,["deriveKey"]);return crypto.subtle.deriveKey({name:"PBKDF2",salt,iterations:200000,hash:"SHA-256"},base,{name:"AES-GCM",length:256},false,usages)}
$("encrypt").onclick=async()=>{const pass=$("pass").value;if(pass.length<10){$("status").textContent="Use a local passphrase of at least 10 characters.";return}const salt=crypto.getRandomValues(new Uint8Array(16)),iv=crypto.getRandomValues(new Uint8Array(12)),k=await key(pass,salt,["encrypt"]),payload={from:$("from").value.trim(),to:$("to").value.trim(),kind:$("kind").value,body:$("body").value,created:new Date().toISOString()},ct=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},k,enc.encode(JSON.stringify(payload))));envelope={schema:"zzx.bbc.envelope.v1",cipher:"AES-256-GCM",kdf:"PBKDF2-SHA256-200000",salt:hex(salt),iv:hex(iv),ciphertext:hex(ct),transportPlan:$("send-transport").value,ttl:Math.max(1,+$("ttl").value||4),storeAndForward:$("store").checked};$("envelope").textContent=JSON.stringify(envelope,null,2);$("status").textContent="Encrypted local message envelope created."};
$("decrypt").onclick=async()=>{try{const k=await key($("pass").value,unhex(envelope.salt),["decrypt"]),pt=await crypto.subtle.decrypt({name:"AES-GCM",iv:unhex(envelope.iv)},k,unhex(envelope.ciphertext));$("plain").textContent=dec.decode(pt)}catch(e){$("plain").textContent="DECRYPT ERROR: "+e.message}};
$("route").onclick=()=>{const src=$("from-node").value.trim(),dst=$("to-node").value.trim(),sorted=nodes.slice().sort((a,b)=>b.linkQuality-a.linkQuality);const path=[];if(src)path.push(src);for(const n of sorted){if(n.id!==src&&n.id!==dst&&path.length<Math.max(1,+$("max-hops").value||4))path.push(n.id)}if(dst)path.push(dst);$("route-out").textContent=JSON.stringify({schema:"zzx.bbc.route-plan.v1",source:src,destination:dst,path,hops:Math.max(0,path.length-1),simulationOnly:true},null,2)};
function dl(text,name){const b=new Blob([text],{type:"application/json"}),u=URL.createObjectURL(b),a=document.createElement("a");a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),800)}
$("export-envelope").onclick=()=>{if(envelope)dl(JSON.stringify(envelope,null,2),"zzxbbc-envelope.json")};$("export-mesh").onclick=()=>dl(JSON.stringify({schema:"zzx.bbc.mesh.v1",nodes,exported:new Date().toISOString()},null,2),"zzxbbc-mesh.json");
[["bbc-1","LoRA","relay",8,78],["bbc-2","Wi-Fi","gateway",.1,92],["bbc-3","5G","client",20,88]].forEach(([id,t,rng,range,q])=>nodes.push({id,transport:t,role:rng,rangeKm:range,linkQuality:q,authorized:true}));render();window.ZZXBBC=Object.freeze({version:"0.2.0-alpha-web",liveRadio:false,credentialsCollected:false});
})();
